### ISSUE TITLE
MegaCoNz fails with non english characters

### ISSUE THREAD

**Issue by Roburetto** [pyload/pyload#2588] opened 2016-09-07 11:10 UTC
[Issue 367](https://github.com/pyload/pyload/issues/367) seems to be back.

"failed'ascii' codec can't encode character u'\xf3' in position 4: ordinal not in range(128) 90.36 MiBMegaCoNz"

LOG here: http://pastebin.com/jmNq1075

Debug Report attached.

[debug_MegaCoNz_07-09-2016_11-39-36.zip](https://github.com/pyload/pyload/files/458905/debug_MegaCoNz_07-09-2016_11-39-36.zip)

Python 2.7.9. PyLoad 4.9

**Comment by GammaC0de** [comment] 2016-09-07 19:37
@Roburetto Unfortunately, the issue is not in but in pyLoad's core.
See https://github.com/pyload/pyload/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ordinal%20not%20in%20range


Hopefully will be fixed iv pyLoad v0,5

**Closed by GammaC0de** 2016-09-07 19:37 UTC
Labels: duplicate

**Comment by Roburetto** [comment] 2016-09-08 01:24
Either of these fix worked for me:

https://github.com/pyload/pyload/issues/2286#issuecomment-215064058
https://github.com/pyload/pyload/issues/2323#issuecomment-178153958

**Comment by GammaC0de** [comment] 2016-09-08 07:40
@Roburetto try fix #2138 (remeber to backup first)

**Comment by Roburetto** [comment] 2016-09-12 10:35
Pull #2346  seems to work fine so far. But the the fixes you reference seem more ambitious. I may give them a try. Thanks for pointing them out,
