### ISSUE TITLE
Storing changes in Plugins 

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1208] opened 2015-02-23 23:49 UTC
Hello,

As many People already know,there are problems with storing changes after a restart in different plugins. 

For example it's not possible to store the change "delete after extract" in ExtarctArchive. 
Another example is that it is not possible to disable Linkdecrypter and there are many more. 
Everytime after a restart the changes are lost. 

It also makes no different if it is changed in plugin.conf directly. 
I also tried to delete the Plugin config in plugin.conf, without any change. 

So please it would be nice if anybody could solve this. 

Thanks & greetz

**Comment by wastez** [comment] 2015-02-25 02:43
This is not a dublicate because #1207 belongs to extractarchive and the request was rejected. 

So please let this issue.

**Comment by stickell** [comment] 2015-02-25 17:41
It's a duplicate of #1157

**Closed by stickell** 2015-02-25 17:41 UTC
Labels: duplicate, plugin issue
