### ISSUE TITLE
Error Filename with uptobox

### ISSUE THREAD

**Issue by Spartanineo** [pyload/pyload#2949] opened 2017-09-02 10:24 UTC
Hi,

I have a problem with pyload. When I launcha download via uptobox this one passes in error with as message " Filename ".

Regards

Spartanineo

**Comment by freud-martinou** [comment] 2017-09-03 10:42
Hi,
I had the same problem.
For me it was caused by a bug on the Alldebrid plugin for premium links: [see here for a bugfix I propose](https://github.com/pyload/pyload/pull/2954)

**Comment by GammaC0de** [comment] 2017-09-03 14:41
@Spartanineo Do you have sample URL?

I tried with a URL I found and worked flawlessly.

**Comment by Spartanineo** [comment] 2017-09-03 15:25
Hi 
Thank you for your answer.
I have just redone several tests and the problem does not seem to settle anymore at the time.
When I brought in a link can import the host I had this message. I have to make a test by naming my file differently and the problem disappeared.
Can the problem come from Alldebrid?

**Comment by GammaC0de** [comment] 2017-09-03 15:35
Well, are you using Alldebrid?

**Comment by Spartanineo** [comment] 2017-09-03 15:45
Yes

**Comment by GammaC0de** [comment] 2017-09-03 19:30
Well, as @freud-martinou mentioned above (thanks), there was a problem with Alldebrid but it is fixed now so I am closing this. 👍

**Closed by GammaC0de** 2017-09-03 19:30 UTC
