### ISSUE TITLE
'NoneType' object has no attribute 'user'

### ISSUE THREAD

**Issue by lorenzobb** [pyload/pyload#1877] opened 2015-09-27 08:10 UTC
Hi All,

would you please help me?
i got error "'NoneType' object has no attribute 'user'" decrypting dlc container.
What i'm doing wrong?
thanks

91	27.09.2015 07:38:22	INFO	Decrypting starts: /mnt/downloads/tmp_San_Andreas_Quake1080p-0jvaavnjxju.dlc
92	27.09.2015 07:38:22	ERROR	Decrypting failed: /mnt/downloads/tmp_San_Andreas_Quake1080p-0jvaavnjxju.dlc | 'NoneType' object has no attribute 'user'
93	27.09.2015 07:38:22	DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/DLC'
94	27.09.2015 07:38:22	INFO	Debug Report written to debug_DLC_27-09-2015_07-38-22.txt
95	27.09.2015 07:40:32	INFO	Added package San Andreas Quake (2015) Bluray RIP 1080p DTS ENG AC3 ITA ENG containing 1 links
96	27.09.2015 07:40:34	INFO	Decrypting starts: /mnt/downloads/tmp_San_Andreas_Quake1080p-0jvaavnjxju.dlc
97	27.09.2015 07:40:34	ERROR	Decrypting failed: /mnt/downloads/tmp_San_Andreas_Quake1080p-0jvaavnjxju.dlc | 'NoneType' object has no attribute 'user'
98	27.09.2015 07:40:34	DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/DLC'
99	27.09.2015 07:40:34	INFO	Debug Report written to debug_DLC_27-09-2015_07-40-34.txt
100	27.09.2015 07:42:26	INFO	Added package Son of God (2014) Bluray Rip 1080p DTS ENG AC3 ITA ENG SUB containing 1 links
101	27.09.2015 07:42:27	INFO	Decrypting starts: /mnt/downloads/tmp_Son_of_god1080p-61i8zunx93yy.dlc
102	27.09.2015 07:42:27	ERROR	Decrypting failed: /mnt/downloads/tmp_Son_of_god1080p-61i8zunx93yy.dlc | 'NoneType' object has no attribute 'user'
103	27.09.2015 07:42:27	DEBUG	Error creating zip file: [Errno 2] No such file or directory: 'tmp/DLC'
104	27.09.2015 07:42:27	INFO	Debug Report written to debug_DLC_27-09-2015_07-42-27.txt

**Comment by joberreiter** [comment] 2015-09-28 01:45
Duplicate of #1874, fixed with #1863.

**Closed** 2015-10-04 19:32 UTC
Labels: duplicate, plugin issue
