### ISSUE TITLE
ddownload.com with free user does not work

### ISSUE THREAD

**Issue by buttermilchmensch** [pyload/pyload#4291] opened 2023-05-08 19:50 UTC
Hello guys, 

on my Raspberry Pi (1 Mod. B) is pyload installed and everything works fine except the ddownload.com download with no premium account (don't know if it's working with the premium account but I don't think so).
I must fill the capture and then the download fails with the error: 
`failed (60, 'SSL certificate problem: unable to get local issuer certificate')`.
So I don't think it's a problem with pyload but with my system. Have anyone an idea how I can fix this problem? (Reinstall doesn't change anything.)

Many thanks in advance
Andi

**Comment by GammaC0de** [comment] 2023-05-08 20:11
duplicate of #4273

**Closed by GammaC0de** 2023-05-08 20:11 UTC
Labels: question
