### ISSUE TITLE
ShareOnline hoster not working

### ISSUE THREAD

**Issue by wastez** [pyload/pyload#1604] opened 2015-07-29 13:36 UTC
Hello,

Since the updates i got this error and SO isn´t useable anymore.
ACCOUNT ShareonlineBiz: Error loading info for user `XXXXXXXXXXX` | invalid arguments to setopt

**Comment by wweich** [comment] 2015-07-29 14:43
Duplicate of #1589

**Closed** 2015-07-29 15:24 UTC
Labels: duplicate
