### ISSUE TITLE
SSL verification does not work

### ISSUE THREAD

**Issue by kvoit** [pyload/pyload#4307] opened 2023-06-03 11:41 UTC
### Description

There seems to be an issue with SSL verification in my pyload-ng (--pre) installations.
Downloads fail with
`[2023-06-03 13:26:27]  DEBUG               pyload  Chunk 1 failed: (60, 'SSL certificate problem: unable to get local issuer certificate')
`
If I deactivate SSL verification under General settings, it works.

My local certificates seem to be fine, though:
```
>>> import certifi
>>> certifi.where()
'/etc/ssl/certs/ca-certificates.crt'
>>> exit()

~ $ ls /etc/ssl/certs/ca-certificates.crt
/etc/ssl/certs/ca-certificates.crt
~ $ ls /etc/ssl/certs/ca-certificates.crt -la
-rw-r--r-- 1 root root 208567 May 25 06:44 /etc/ssl/certs/ca-certificates.crt

### Additional references
<!-- Any other reference, related issues or pull requests about this report. -->
The only other reference I can find on this is in the reddit thread:
https://www.reddit.com/r/selfhosted/comments/10psp2z/web_based_download_mannager_recommendations/

**Comment by GammaC0de** [comment] 2023-06-03 19:20
Duplicate of #4273

**Closed by GammaC0de** 2023-06-03 19:20 UTC
Labels: bug, pyLoad Next
