### ISSUE TITLE
ExtractArchive only deletes one file

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#1612] opened 2015-07-30 09:00 UTC
```
30.07.2015 11:00:08 DEBUG     EXTRACTOR ExtractArchive: UnRar | unrar vb -o+ -x'*.nfo' -x'*.DS_Store' -x'index.dat' -x'thumb.db' -y -pserienjunkies.org -v Downloads/The.100.S01E04.Murphys.Gesetz.GERMAN.DUBBED.720p.BLURAY.x264-ZZGtv/thd.720p.S01E04.part13.rar
30.07.2015 11:00:21 DEBUG     HOOK ExtractArchive: Would delete: Downloads/The.100.S01E04.Murphys.Gesetz.GERMAN.DUBBED.720p.BLURAY.x264-ZZGtv/thd.720p.S01E04.part13.rar
30.07.2015 11:00:21 INFO      HOOK ExtractArchive: Deleting 1 files
```

**Comment by TodsDeath** [comment] 2015-07-30 09:28
duplicate of #1603

**Closed** 2015-07-30 12:44 UTC
Labels: duplicate, plugin issue
