### ISSUE TITLE
Zippyshare, randomly downloads html (1kB) instead of .rar (200MB)

### ISSUE THREAD

**Issue by blotsome** [pyload/pyload#2962] opened 2017-09-16 23:36 UTC
I just went through a long list of Zippyfile archives, aprox 50 files (links) per package. And every single time, at least 2 or more of the files failed, in that they ended up 1kB instead of 200MB. I opened the file and saw this:

`<!doctype html>
<html class="no-js" lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Zippyshare.com - File download</title>
    </head>
    <body>

        <script type="text/javascript">
            window.opener.location.assign('http://go.oclasrv.com/afu.php?zoneid=####');
            window.location = '/d/gTeGcMmc/27488/FILENAME.part29.rar';
            window.setTimeout(function(){ window.location = '/v/gTeGcMmc/FILENAME.part29.rar'; }, 1500);

        </script>
    </body>
</html>
`
I had to change the setting to skip existing files, and then it created the file again only with FILENAME.part29.rar (2) suffix. So I then had to delete the 1kB file, rename the new download, then turn skip existing back on and restart the package in order to get extraction to start. 

A way to check either the docktype (html) or file size (<4kB) could be an internal check to see if the file download didn't work. Or is something else going on causing these occasional but consistent failures?

**Comment by GammaC0de** [comment] 2017-09-17 00:46
Does this happen after you have downloaded a lot of files? maybe you have reached some limit?

Try waiting some hours (I suggest at lease 24) and then see if it happens again and if yes how much time past since it started again.

Also, please post here one of those HTML files.

Sharing the URLs would also be useful.

**Comment by blotsome** [comment] 2017-09-17 03:24
This is not a limit to my knowledge, because it's not like I get to part 24 then get this file for parts 25-50. It's just randomly interspersed. I posted the text of the HTML files already. It appears the zoneid number  is the same in each file, and it's 1393163. And if I turn off "skip existing" and restart the file from the queue, it has downloaded just fine the second time. Is there a way to get it to check file size before considering it done? Or a way to check for the doctype header?

**Comment by GammaC0de** [comment] 2017-09-17 13:57
Well, I need to work with something..
Please post the URLs, if you don't want to post here, I can give you my email.

**Comment by blotsome** [comment] 2017-09-18 13:34
Sure, that will work. I'm more than happy to provide privately. I do not believe it is the file because it works on the 2nd attempt, and it happens maybe 5-10% of the time, randomly through a set of 50+.

**Comment by GammaC0de** [comment] 2017-09-18 17:40
Please send the links to nitzo2001 at yahoo dot com.

**Comment by GammaC0de** [comment] 2017-09-18 20:53
I have succeeded to reproduce this issue and not the plugin is updated.

Now I have successfully downloaded 60 files (10GB).

Please test also and confirm it works.

**Comment by GammaC0de** [comment] 2017-09-19 13:57
I am pretty sure this is solved after the recent update.

What was happening is that sometimes when you press download with your browser, you will get that HTML page that what it does is display an ad and then redirect you to the actual download.

Ad I said above, successfully download about 60 files and also the files you have sent me.

Please confirm also so we can close this.

**Comment by HenningJW** [comment] 2017-09-19 20:04
Can confirm the update most likely solves the problem (50 files sample size, before i would have had about 5 errors).

**Comment by GammaC0de** [comment] 2017-09-19 23:56
OK, closing then. 👍

**Closed by GammaC0de** 2017-09-19 23:56 UTC
Labels: plugin issue

**Comment by blotsome** [comment] 2017-09-20 04:56
I'll update and try again this weekend. Thanks for your help. 

    On Tuesday, September 19, 2017 4:56 PM, GammaC0de <notifications@github.com> wrote:
 

 Closed #2962.—
