### ISSUE TITLE
[uptobox] first argument must be string or compiled pattern

### ISSUE THREAD

**Issue by pixou80** [pyload/pyload#1859] opened 2015-09-24 11:18 UTC
New error  : 
Warning	Download failed : 
"Name of the file" | first argument must be string or compiled pattern

**Comment by xilmen** [comment] 2015-09-24 11:50
Same error 

WARNING   Download failed : "my file" | first argument must be string or compiled pattern

**Comment by f6fvy** [comment] 2015-09-24 13:50
This issue now supersedes #1819 !

**Comment by tribal123** [comment] 2015-09-24 14:21
Same here with Easybytez

**Comment by jibedo** [comment] 2015-09-24 16:12
Same error

WARNING Download failed : "Name of the file" | first argument must be string or compiled pattern

**Comment by Bambie42** [comment] 2015-09-24 16:13
Post a debug log and a sample file

**Comment by jibedo** [comment] 2015-09-24 16:37
My debug log when I begin my download ( link : http://uptobox.com/pbtfx2t7vtqc) : 

>24.09.2015 18:35:19 DEBUG     HOSTER UptoboxCom[52]: File info: {'status': 2, 'url': u'http://uptobox.com/pbtfx2t7vtqc', 'size': 4724464025.6, 'name': u'Air.2015.FRENCH.720p.BluRay.x264-VENUE.Premium.zone-telechargement.com.mkv', 'pattern': {'S': u'4.4', 'U': u'GB', 'N': u'Air.2015.FRENCH.720p.BluRay.x264-VENUE.Premium.zone-telechargement.com.mkv'}}
24.09.2015 18:35:19 DEBUG     HOSTER UptoboxCom[52]: Previous file info: {}
24.09.2015 18:35:19 INFO      HOSTER UptoboxCom[52]: File name: Air.2015.FRENCH.720p.BluRay.x264-VENUE.Premium.zone-telechargement.com.mkv
24.09.2015 18:35:19 INFO      HOSTER UptoboxCom[52]: File size: 4724464025 bytes
24.09.2015 18:35:19 INFO      HOSTER UptoboxCom[52]: File status: online
24.09.2015 18:35:19 DEBUG     HOSTER UptoboxCom[52]: LOAD URL http://uptobox.com/pbtfx2t7vtqc | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
24.09.2015 18:35:19 INFO      HOSTER UptoboxCom[52]: Processing as free download...
24.09.2015 18:35:19 DEBUG     HOSTER UptoboxCom[52]: Getting download link #1
24.09.2015 18:35:19 DEBUG     HOSTER UptoboxCom[52]: {u'rand': u'3fjd6t6oep4z5ge3wfftkfaskg2jznhi4epbwwy', u'file_size_real': u'4689310186', u'method_premium': '', u'down_direct': u'1', u'referer': '', u'fname': u'Air.2015.FRENCH.720p.BluRay.x264-VENUE.Premium.zone-telechargement.com.mkv', u'method_free': '', u'id': u'pbtfx2t7vtqc', u'op': u'download2'}
24.09.2015 18:35:19 WARNING   Download failed: Air.2015.FRENCH.720p.BluRay.x264-VENUE.Premium.zone-telechargement.com.mkv | first argument must be string or compiled pattern
Traceback (most recent call last):
  File "/usr/local/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/root/pyload/userplugins/internal/Hoster.py", line 184, in preprocessing
    return self._process(*args, **kwargs)
  File "/root/pyload/userplugins/internal/Hoster.py", line 179, in _process
    return self.process(self.pyfile)
  File "/root/pyload/userplugins/internal/SimpleHoster.py", line 284, in process
    self.handle_free(pyfile)
  File "/root/pyload/userplugins/internal/XFSHoster.py", line 101, in handle_free
    data = self.get_post_parameters()
  File "/root/pyload/userplugins/internal/XFSHoster.py", line 209, in get_post_parameters
    self.handle_captcha(inputs)
  File "/root/pyload/userplugins/internal/XFSHoster.py", line 245, in handle_captcha
    captcha_key = re.search(self.RECAPTCHA_PATTERN, self.html).group(1)
  File "/usr/local/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/lib/python2.7/re.py", line 247, in _compile
    raise TypeError, "first argument must be string or compiled pattern"
TypeError: first argument must be string or compiled pattern
24.09.2015 18:35:19 INFO      Debug Report written to debug_UptoboxCom_24-09-2015_18-35-19.zip
24.09.2015 18:35:19 INFO      ADDON UnSkipOnFail: Looking for skipped duplicates of: Air.2015.FRENCH.720p.BluRay.x264-VENUE.Premium.zone-telechargement.com.mkv (pid:34)
24.09.2015 18:35:19 INFO      ADDON UnSkipOnFail: No duplicates found
24.09.2015 18:35:19 DEBUG     All downloads processed

**Comment by damien599901** [comment] 2015-09-25 13:46
Me i have this one : "Required account not found"

**Comment by joberreiter** [comment] 2015-09-25 13:57
Duplicate of #1852

**Comment by damien599901** [comment] 2015-09-25 14:45
@joberreiter  : sorry

**Comment by regpa** [comment] 2015-09-25 19:54
Hello, I have a similar issue, here is my log, looking everywhere on the net, found no hint so far 


332	25.09.2015 21:46:19	INFO	Download starts: filename
333	25.09.2015 21:46:19	INFO	HOSTER UptoboxCom[1]: Updating file info...
334	25.09.2015 21:46:19	INFO	HOSTER UptoboxCom[1]: File name: filename
335	25.09.2015 21:46:19	INFO	HOSTER UptoboxCom[1]: File size: 1503238553 bytes
336	25.09.2015 21:46:19	INFO	HOSTER UptoboxCom[1]: File status: online
337	25.09.2015 21:46:19	INFO	HOSTER UptoboxCom[1]: Processing as free download...
338	25.09.2015 21:46:19	WARNING	Download failed: filename | first argument must be string or compiled pattern
339	25.09.2015 21:46:19	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: filename (pid:1)
340	25.09.2015 21:46:20	INFO	ADDON UnSkipOnFail: No duplicates found

**Comment by FabrizioA** [comment] 2015-09-26 16:01
same issue :(

**Comment by Hadronius** [comment] 2015-09-26 22:14
I manualy made the changes in https://github.com/mationic/pyload/commit/5f9d6f992cb889379dd02fe71fe8c5a4b149fc44
 and the error is gone, I can download normally now as premium.
Try it.

**Comment by FabrizioA** [comment] 2015-09-26 23:21
I've used your Hoster.py file version but now pyLoad crash:
Here the log:
26.09.2015 23:18:51 INFO      Download starts: MyFile.part2.rev
26.09.2015 23:18:51 INFO      HOSTER EasybytezCom[446]: Updating file info...
26.09.2015 23:18:51 INFO      HOSTER EasybytezCom[446]: File name: CMyFile.part2.rev
26.09.2015 23:18:51 INFO      HOSTER EasybytezCom[446]: File size: 110100480 bytes
26.09.2015 23:18:51 INFO      HOSTER EasybytezCom[446]: File status: online
26.09.2015 23:18:51 INFO      HOSTER EasybytezCom[446]: Looking for direct download link...
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file ThreadManager.py, line 146
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file ThreadManager.py, line 146
Traceback (most recent call last):
  File "/usr/bin/pyLoadCore", line 667, in <module>
    main()
  File "/usr/bin/pyLoadCore", line 658, in main
    pyload_core.start()
  File "/usr/bin/pyLoadCore", line 468, in start
    self.threadManager.work()
  File "/home/ubuntu/pyload-stable/module/ThreadManager.py", line 151, in work
    self.assignJob()
  File "/home/ubuntu/pyload-stable/module/ThreadManager.py", line 265, in assignJob
    inuse = set([(x.active.pluginname,self.getLimit(x)) for x in self.threads if x.active and x.active.hasPlugin() and x.active.plugin.account])
  File "/home/ubuntu/pyload-stable/module/ThreadManager.py", line 313, in getLimit
    limit = thread.active.plugin.account.getAccountData(thread.active.plugin.user)["options"].get("limitDL",["0"])[0]
AttributeError: 'EasybytezCom' object has no attribute 'user'

**Comment by FabrizioA** [comment] 2015-09-27 15:50
A short update of my situation:
I've reinstalled pyLoad cli using deb package (before I had installed from git sources). Now all works without particular error.... But I can't get plugin update with the relative easybytez plugin.


152	27.09.2015 10:31:31	INFO	No plugin updates available
153	27.09.2015 13:59:09	INFO	restarting pyLoad
154	27.09.2015 13:59:09	INFO	shutting down...
155	27.09.2015 13:59:12	INFO	Avvio pyLoad 0.4.9
156	27.09.2015 13:59:12	INFO	Uso la cartella home: /home/ubuntu/.pyload
157	27.09.2015 13:59:13	INFO	ExtractArchive: Attivato UnRar UnZip
158	27.09.2015 13:59:13	INFO	Plugins attivati: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
159	27.09.2015 13:59:13	INFO	Plugins disattivati: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
160	27.09.2015 13:59:13	INFO	Tempo di download: True
161	27.09.2015 13:59:13	INFO	Starting builtin webserver: 192.168.1.100:8000
162	27.09.2015 13:59:13	INFO	Free space: 50.16 GiB
163	27.09.2015 13:59:13	INFO	Activating Accounts...
164	27.09.2015 13:59:13	INFO	Activating Plugins...
165	27.09.2015 13:59:13	INFO	pyLoad is up and running
166	27.09.2015 13:59:17	WARNING	Not able to connect server for updates
167	27.09.2015 13:59:17	INFO	No Updates for pyLoad
168	27.09.2015 13:59:17	WARNING	Not able to connect server for updates
169	27.09.2015 13:59:17	INFO	No plugin updates available


152	27.09.2015 10:31:31	INFO	No plugin updates available
153	27.09.2015 13:59:09	INFO	restarting pyLoad
154	27.09.2015 13:59:09	INFO	shutting down...
155	27.09.2015 13:59:12	INFO	Avvio pyLoad 0.4.9
156	27.09.2015 13:59:12	INFO	Uso la cartella home: /home/ubuntu/.pyload
157	27.09.2015 13:59:13	INFO	ExtractArchive: Attivato UnRar UnZip
158	27.09.2015 13:59:13	INFO	Plugins attivati: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
159	27.09.2015 13:59:13	INFO	Plugins disattivati: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
160	27.09.2015 13:59:13	INFO	Tempo di download: True
161	27.09.2015 13:59:13	INFO	Starting builtin webserver: 192.168.1.100:8000
162	27.09.2015 13:59:13	INFO	Free space: 50.16 GiB
163	27.09.2015 13:59:13	INFO	Activating Accounts...
164	27.09.2015 13:59:13	INFO	Activating Plugins...
165	27.09.2015 13:59:13	INFO	pyLoad is up and running
166	27.09.2015 13:59:17	WARNING	Not able to connect server for updates
167	27.09.2015 13:59:17	INFO	No Updates for pyLoad
168	27.09.2015 13:59:17	WARNING	Not able to connect server for updates
169	27.09.2015 13:59:17	INFO	No plugin updates available

**Comment by damien599901** [comment] 2015-09-27 15:59
@Fabrizio Alongi : how to edit this file please ?  Host.py?
thanks

2015-09-27 17:50 GMT+02:00 Fabrizio Alongi <notifications@github.com>:

**Comment by funkyslap** [comment] 2015-09-27 16:02
@Hadronius thanks, mationic@5f9d6f9 commit also fix RealDebrid issue "Required account not found"

**Comment by damien599901** [comment] 2015-09-27 16:04
@funkyslap : could you help me please? how edit this file with  mationic@
<https://github.com/mationic/pyload/commit/5f9d6f9>5f9d6f9
<https://github.com/mationic/pyload/commit/5f9d6f9>?
cheers

2015-09-27 18:02 GMT+02:00 funkyslap <notifications@github.com>:

**Comment by funkyslap** [comment] 2015-09-27 16:16
@damien599901 just read this https://github.com/pyload/pyload/pull/1858#issuecomment-142995115

**Comment by damien599901** [comment] 2015-09-27 16:19
@funkyslap
great but what are the complete linux commands please? i begin in Linux

2015-09-27 18:16 GMT+02:00 funkyslap <notifications@github.com>:

**Comment by FabrizioA** [comment] 2015-09-27 16:58
@damien599901 you don't edit the file, just replace it.
Anyway, at this time, my payload doesn't update plugins and I can't login with my easybytez premium account :(

**Comment by damien599901** [comment] 2015-09-27 17:16
sorry for you @Fabrizio Alongi

2015-09-27 18:58 GMT+02:00 Fabrizio Alongi <notifications@github.com>:

**Comment by joberreiter** [comment] 2015-09-28 01:38
> Anyway, at this time, my payload doesn't update plugins
Yes, this is known and not a bug.
The update server and the format have changed, so v0.4.9 won't get updates anymore.

**Comment by FabrizioA** [comment] 2015-09-28 07:05
@joberreiter Do the server will update?? Do Easybytez will works with future updates? :(

**Comment by joberreiter** [comment] 2015-09-29 14:03
The (new) update server works if you use the version from the stable branch, but unfortunately there were a couple of issues introduced in stable that make it's use a pain in the ass.

You are encouraged to use older snapshot of stable, as 'jcbyem' has figured out in a [thread](http://forum.pyload.org/viewtopic.php?f=12&t=4545&start=20) at the pyload forum, until the issues are resolved.

It seems that, in the moment, the only one to fix this is voulter (at least I don't know another maintainer).

**Comment by joberreiter** [comment] 2015-09-29 16:34
Issue solved with #1883, can be closed.

**Comment by FabrizioA** [comment] 2015-09-29 18:07
Emh... Sorry for my missunderstood... but the issue is resolved or not?

**Closed** 2015-09-29 21:32 UTC
Labels: plugin issue
