### ISSUE TITLE
DlFreeFr - strange behaviour

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#3301] opened 2018-12-31 15:03 UTC
The plugin DlFreeFr works, for the link I've tried before AND after, but not this one: http://dl.free.fr/n4uFkQEV2

The link is working and is **not** offline.

I will provide the debug-log soon, here is the extract of the log :
Line | Date | Type | Data
-- | -- | -- | --
564 | 31.12.2018 15:52:53 | INFO | Added package 2018-12 containing 1 links
565 | 31.12.2018 15:52:54 | INFO | Download starts: http://dl.free.fr/n4uFkQEV2
566 | 31.12.2018 15:52:54 | WARNING | HOSTER DlFreeFr[2839]: Plugin may be unstable
567 | 31.12.2018 15:52:54 | INFO | HOSTER DlFreeFr[2839]: Grabbing link info...
568 | 31.12.2018 15:52:55 | ERROR | <<< UNCAUGHT EXCEPTION >>>
569 | ? | ? | Traceback (most recent call last):
570 | ? | ? | File "/usr/share/pyload-4.9.0b/module/network/HTTPRequest.py", line 306, in write
571 | ? | ? | raise Exception("Loaded Url exceeded limit")
572 | ? | ? | Exception: Loaded Url exceeded limit
573 | 31.12.2018 15:52:55 | INFO | HOSTER DlFreeFr[2839]: Link name: n4uFkQEV2
574 | 31.12.2018 15:52:55 | INFO | HOSTER DlFreeFr[2839]: Link size: N/D
575 | 31.12.2018 15:52:55 | INFO | HOSTER DlFreeFr[2839]: Link status: demarrage
576 | 31.12.2018 15:52:55 | INFO | HOSTER DlFreeFr[2839]: Processing url: http://dl.free.fr/n4uFkQEV2
577 | 31.12.2018 15:52:55 | INFO | HOSTER DlFreeFr[2839]: Looking for direct download link...
578 | 31.12.2018 15:52:56 | INFO | HOSTER DlFreeFr[2839]: Direct download link not found
579 | 31.12.2018 15:52:56 | INFO | HOSTER DlFreeFr[2839]: Checking for link errors...
580 | 31.12.2018 15:52:56 | INFO | HOSTER DlFreeFr[2839]: No errors found
581 | 31.12.2018 15:52:56 | INFO | HOSTER DlFreeFr[2839]: Grabbing link info...
582 | 31.12.2018 15:52:56 | INFO | HOSTER DlFreeFr[2839]: Link name: 4uFkQEV2
583 | 31.12.2018 15:52:56 | INFO | HOSTER DlFreeFr[2839]: Link size: N/D
584 | 31.12.2018 15:52:56 | INFO | HOSTER DlFreeFr[2839]: Link status: temp. hors ligne
585 | 31.12.2018 15:52:56 | WARNING | HOSTER DlFreeFr[2839]: Free download failed \| temp. offline
586 | 31.12.2018 15:52:56 | WARNING | Download is temporary offline: 4uFkQEV2

**Comment by zephura** [comment] 2018-12-31 17:07
Here is the debug extract :


746 | 31.12.2018 18:03:15 | INFO | Added package 2018-12 containing 1 links
-- | -- | -- | --
747 | 31.12.2018 18:03:15 | DEBUG | Redirected import module.plugins.internal.Hoster -> userplugins.internal.Hoster
748 | 31.12.2018 18:03:16 | INFO | Download starts: http://dl.free.fr/n4uFkQEV2
749 | 31.12.2018 18:03:16 | DEBUG | ADDON ExternalScripts: No script found under folder `download_preparing`
750 | 31.12.2018 18:03:16 | DEBUG | ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
751 | 31.12.2018 18:03:16 | DEBUG | ADDON UserAgentSwitcher: Setting maximum redirections to 10
752 | 31.12.2018 18:03:16 | DEBUG | ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0`
753 | 31.12.2018 18:03:16 | DEBUG | HOSTER DlFreeFr[2843]: Plugin version: 0.39
754 | 31.12.2018 18:03:16 | DEBUG | HOSTER DlFreeFr[2843]: Plugin status: testing
755 | 31.12.2018 18:03:16 | WARNING | HOSTER DlFreeFr[2843]: Plugin may be unstable
756 | 31.12.2018 18:03:16 | INFO | HOSTER DlFreeFr[2843]: Grabbing link info...
757 | 31.12.2018 18:03:20 | ERROR | <<< UNCAUGHT EXCEPTION >>>
758 | ? | ? | Traceback (most recent call last):
759 | ? | ? | File "/usr/share/pyload-4.9.0b/module/network/HTTPRequest.py", line 306, in write
760 | ? | ? | raise Exception("Loaded Url exceeded limit")
761 | ? | ? | Exception: Loaded Url exceeded limit
762 | 31.12.2018 18:03:20 | DEBUG | HOSTER DlFreeFr[2843]: Link info: {'status': 7, 'hash': {}, 'name': 'n4uFkQEV2', 'url': u'http://dl.free.fr/getfile.pl?file=/4uFkQEV2', 'pattern': {'ID': u'4uFkQEV2'}, 'size': 0}
763 | 31.12.2018 18:03:20 | DEBUG | HOSTER DlFreeFr[2843]: Previous link info: {}
764 | 31.12.2018 18:03:20 | INFO | HOSTER DlFreeFr[2843]: Link name: n4uFkQEV2
765 | 31.12.2018 18:03:20 | INFO | HOSTER DlFreeFr[2843]: Link size: N/D
766 | 31.12.2018 18:03:20 | INFO | HOSTER DlFreeFr[2843]: Link status: demarrage
-- | -- | -- | --
767 | 31.12.2018 18:03:20 | INFO | HOSTER DlFreeFr[2843]: Processing url: http://dl.free.fr/n4uFkQEV2
768 | 31.12.2018 18:03:20 | INFO | HOSTER DlFreeFr[2843]: Looking for direct download link...
769 | 31.12.2018 18:03:20 | DEBUG | HOSTER DlFreeFr[2843]: LOAD URL http://dl.free.fr/getfile.pl?file=/4uFkQEV2 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=True \| just_header=True
770 | 31.12.2018 18:03:21 | INFO | HOSTER DlFreeFr[2843]: Direct download link not found
771 | 31.12.2018 18:03:21 | DEBUG | HOSTER DlFreeFr[2843]: LOAD URL http://dl.free.fr/getfile.pl?file=/4uFkQEV2 \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=False \| just_header=False
772 | 31.12.2018 18:03:21 | INFO | HOSTER DlFreeFr[2843]: Checking for link errors...
773 | 31.12.2018 18:03:21 | INFO | HOSTER DlFreeFr[2843]: No errors found
774 | 31.12.2018 18:03:21 | INFO | HOSTER DlFreeFr[2843]: Grabbing link info...
775 | 31.12.2018 18:03:21 | DEBUG | HOSTER DlFreeFr[2843]: Link info: {'status': 6, 'hash': {}, 'name': '4uFkQEV2', 'url': u'http://dl.free.fr/getfile.pl?file=/4uFkQEV2', 'pattern': {'ID': u'4uFkQEV2'}, 'size': 0}
776 | 31.12.2018 18:03:21 | DEBUG | HOSTER DlFreeFr[2843]: Previous link info: {'status': 7, 'hash': {}, 'name': 'n4uFkQEV2', 'url': u'http://dl.free.fr/getfile.pl?file=/4uFkQEV2', 'pattern': {'ID': u'4uFkQEV2'}, 'size': 0}
777 | 31.12.2018 18:03:21 | INFO | HOSTER DlFreeFr[2843]: Link name: 4uFkQEV2
778 | 31.12.2018 18:03:21 | INFO | HOSTER DlFreeFr[2843]: Link size: N/D
779 | 31.12.2018 18:03:21 | INFO | HOSTER DlFreeFr[2843]: Link status: temp. hors ligne
780 | 31.12.2018 18:03:21 | WARNING | HOSTER DlFreeFr[2843]: Free download failed \| temp. offline
781 | 31.12.2018 18:03:21 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
782 | 31.12.2018 18:03:21 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
783 | 31.12.2018 18:03:21 | DEBUG | ADDON ExternalScripts: No script found under folder `package_failed`
784 | 31.12.2018 18:03:21 | WARNING | Download is temporary offline: 4uFkQEV2
785 | 31.12.2018 18:03:21 | DEBUG | ADDON ExternalScripts: No script found under folder `all_downloads_processed`
786 | 31.12.2018 18:03:21 | DEBUG | All downloads processed

**Comment by GammaC0de** [comment] 2018-12-31 20:43
https://github.com/pyload/pyload/commit/cdb73c78477959c96ab80767f9404fb879304fcb 
Plugins updated, please confirm the issue is solved.

**Comment by zephura** [comment] 2019-01-01 08:11
It works fine for the "long" files 👍

**Comment by GammaC0de** [comment] 2019-01-01 17:12
> It works fine for the "long" files

:+1: Closing.

**Closed by GammaC0de** 2019-01-01 17:12 UTC
Labels: feedback wanted, plugin bug
