### ISSUE TITLE
Zippyshare 'dict' object has no attribute 'lower'

### ISSUE THREAD

**Issue by hidden-refuge** [pyload/pyload#2301] opened 2016-01-19 13:42 UTC
Hello there,

Originally I've been trying to help someone who is having a issue with "ExtractArchive". When I tried to reproduce the issue they get I didn't even get so far because I have a different error. Before coming to extracting archives the downloads are making as failed with the error message: 'dict' object has no attribute 'lower':

Here is a copy of a log for a Zippyshare download I made for testing:
```
19.01.2016 14:15:10 INFO      Download starts: unrar_5.2.7-0.1_armhf.7z
19.01.2016 14:15:11 WARNING   HOSTER ZippyshareCom[3]: Plugin may be unstable
19.01.2016 14:15:11 INFO      HOSTER ZippyshareCom[3]: Grabbing link info...
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Link name: unrar_5.2.7-0.1_armhf.7z
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Link size: 102.40 KiB (104857 bytes)
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Link status: online
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Processing url: http://www104.zippyshare.com/v/Qla6vBuQ/file.html
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Looking for direct download link...
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Direct download link not found
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Checking for link errors...
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: No errors found
19.01.2016 14:15:12 INFO      HOSTER ZippyshareCom[3]: Processing as free download...
19.01.2016 14:15:12 WARNING   CAPTCHA ZippyshareCom[3]: ReCaptcha | Key pattern not found
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: Downloading file...
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: File saved
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: Checking download...
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: File is OK
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: Checking file (with built-in rules)...
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: Checking file (with custom rules)...
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: Checking for link errors...
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: No errors found
19.01.2016 14:15:22 INFO      HOSTER ZippyshareCom[3]: No errors found
19.01.2016 14:15:22 INFO      Download finished: unrar_5.2.7-0.1_armhf.7z
19.01.2016 14:15:23 WARNING   Download failed: unrar_5.2.7-0.1_armhf.7z | 'dict' object has no attribute 'lower'
```

Any idea how to fix this? I just can't get around this. It also happens when I download a normal file off Zippyshare that isn't inside and archive.

I have compiled unrar-nonfree on my Raspberry Pi and installed it with the compiled package. It's version 5.21 according to unrar output:
```
UNRAR 5.21 freeware      Copyright (c) 1993-2015 Alexander Roshal
```

I checked the ZippyShare plugin but it does not contain any dict function however the ExtractArchive plugin contains this:
```
            matched   = False
            success   = True
            files_ids = dict((fdata['name'], ((fsjoin(dl_folder, pypack.folder, fdata['name'])), fid, out)) for fid, fdata \
                        in sorted(pypack.getChildren().values(), key=lambda k: k['name'])).items()  #: Remove duplicates
```

I'm clueless. Any download is marked as failed with that error. Below is another test with the same file but this time on Uploaded.
```
19.01.2016 14:41:13 INFO      Download starts: http://uploaded.net/file/x9pw9qoq
19.01.2016 14:41:14 WARNING   HOSTER UploadedTo[5]: Plugin may be unstable
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Grabbing link info...
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Link name: unrar_5.2.7-0.1_armhf.7z
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Link size: 105.70 KiB (108235 bytes)
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Link status: online
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Processing url: http://uploaded.net/file/x9pw9qoq
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Looking for direct download link...
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Direct download link not found
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Checking for link errors...
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: No errors found
19.01.2016 14:41:15 INFO      HOSTER UploadedTo[5]: Processing as free download...
19.01.2016 14:41:16 INFO      CAPTCHA UploadedTo[5]: ReCaptcha | Using OCR to decrypt captcha...
19.01.2016 14:41:16 WARNING   CAPTCHA UploadedTo[5]: ReCaptcha | No OCR result
19.01.2016 14:41:29 INFO      CAPTCHA UploadedTo[5]: ReCaptcha | Captcha result: `strictly fhucu`
19.01.2016 14:41:29 INFO      CAPTCHA UploadedTo[5]: ReCaptcha | Path deleted: /pi/.pyload/tmp/captcha_image_UploadedTo_87660.jpg
19.01.2016 14:41:30 INFO      HOSTER UploadedTo[5]: Checking for link errors...
19.01.2016 14:41:30 INFO      HOSTER UploadedTo[5]: No errors found
19.01.2016 14:41:30 INFO      HOSTER UploadedTo[5]: Checking for link errors...
19.01.2016 14:41:30 INFO      HOSTER UploadedTo[5]: No errors found
19.01.2016 14:41:30 INFO      HOSTER UploadedTo[5]: Downloading file...
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: File saved
19.01.2016 14:41:32 INFO      CAPTCHA UploadedTo[5]: ReCaptcha | Correct captcha | strictly fhucu
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: Checking download...
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: File is OK
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: Checking file (with built-in rules)...
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: Checking file (with custom rules)...
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: Checking for link errors...
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: No errors found
19.01.2016 14:41:32 INFO      HOSTER UploadedTo[5]: No errors found
19.01.2016 14:41:32 INFO      Download finished: unrar_5.2.7-0.1_armhf.7z
19.01.2016 14:41:32 WARNING   Download failed: unrar_5.2.7-0.1_armhf.7z | 'dict' object has no attribute 'lower'
```

**Comment by manacker** [comment] 2016-01-19 13:51
This seems to be a duplicate of #2258

**Comment by hidden-refuge** [comment] 2016-01-19 14:41
So it's a bug. I thought it was only me because the installation on the Raspberry Pi of the person I tried to help didn't have this issue but it had https://github.com/pyload/pyload/issues/2296

**Comment by hidden-refuge** [comment] 2016-01-19 14:48
```As a workaround i changed line 134 of Checksum.py to

" if key in data and data[key]:"

which at least allows "normal" downloades, even if it skipps the whole checksum stuff```

Has indeed worked as a workaround. Now I'm also getting https://github.com/pyload/pyload/issues/2296

**Comment by GammaC0de** [comment] 2016-01-19 23:18
same as #2258

**Closed by GammaC0de** 2016-01-19 23:18 UTC
Labels: duplicate, plugin issue
