### ISSUE TITLE
Correct captcha for ddownload is not considered and free download is not started

### ISSUE THREAD

**Issue by godfuture** [pyload/pyload#4275] opened 2023-03-31 09:01 UTC
### Description

I am using Alldebrid. Unfortunately the ddownload hoster is restricted quite often. Therefore I have activated fallback to free download. Problem here is that the captcha popup appears, and I am solving the captcha, but after a (correct) confirm, a next captcha appears. This goes on till my download is sent to wait time.

### Debug log

```
10376	2023-03-31 10:27:16	WARNING	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Plugin may be unstable
10378	2023-03-31 10:27:19	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Processing url: https://ddownload.com/mydownload
10380	2023-03-31 10:27:19	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Checking for link errors...
10382	2023-03-31 10:27:19	WARNING	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | No data to check
10384	2023-03-31 10:27:19	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Grabbing link info...
10386	2023-03-31 10:27:19	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Link name: mydownload
10388	2023-03-31 10:27:19	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Link size: 512.00 MiB (536870912 bytes)
10390	2023-03-31 10:27:19	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Link status: starting
10392	2023-03-31 10:27:19	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Processing as premium download...
10408	2023-03-31 10:27:19	ERROR	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | You have reached the download limit for this host
10409	2023-03-31 10:27:19	WARNING	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Premium download failed | temp. offline
10411	2023-03-31 10:27:20	INFO	pyload	Download restarted: mydownload | Fallback to free processing
10414	2023-03-31 10:27:20	INFO	pyload	Download starts: mydownload
10415	2023-03-31 10:27:20	WARNING	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Plugin may be unstable
10417	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Processing url: https://ddownload.com/mydownload
10418	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Checking for link errors...
10419	2023-03-31 10:27:20	WARNING	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | No data to check
10420	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Grabbing link info...
10421	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Link name: mydownload
10422	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Link size: 512.00 MiB (536870912 bytes)
10423	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Link status: starting
10424	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Processing as free download...
10425	2023-03-31 10:27:20	WARNING	pyload	DOWNLOADER AlldebridCom[4205]: AlldebridCom | Free download failed | MultiDownloader download failed
10426	2023-03-31 10:27:20	INFO	pyload	Download restarted: mydownload | Revert to original downloader plugin
10427	2023-03-31 10:27:20	INFO	pyload	Download starts: mydownload
10428	2023-03-31 10:27:20	WARNING	pyload	DOWNLOADER DdownloadCom[4205]: Plugin may be unstable
10429	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Processing url: https://ddownload.com/mydownload
10435	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Checking for link errors...
10437	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: No errors found
10439	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Grabbing link info...
10441	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Link name: "my download".rar
10443	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Link size: 512.00 MiB (536870912 bytes)
10445	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Link status: online
10447	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Processing as free download...
10448	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Checking for link errors...
10449	2023-03-31 10:27:20	INFO	pyload	DOWNLOADER DdownloadCom[4205]: No errors found
10450	2023-03-31 10:27:20	WARNING	pyload	ANTICAPTCHA DdownloadCom[4205]: ReCaptcha | Secure Token pattern not found
10451	2023-03-31 10:27:20	WARNING	pyload	ANTICAPTCHA DdownloadCom[4205]: ReCaptcha | Secure Token pattern not found
10453	2023-03-31 10:27:20	WARNING	pyload	ANTICAPTCHA DdownloadCom[4205]: ReCaptcha | reCAPTCHA noscript is blocked, trying reCAPTCHA interactive
10457	2023-03-31 10:29:00	WARNING	pyload	Download failed: "my download".rar | (60, 'SSL certificate problem: unable to get local issuer certificate')
10458	2023-03-31 10:29:00	INFO	pyload	ADDON UnSkipOnFail: Looking for skipped duplicates of: "my download".rar (pid:424)
10459	2023-03-31 10:29:00	INFO	pyload	ADDON UnSkipOnFail: No duplicates found
10460	2023-03-31 10:29:14	INFO	pyload	ANTICAPTCHA DdownloadCom[4205]: ReCaptcha | Captcha result: `03AKH6MREgEh_N5lyypmSKpz3i08PjC9sedZ0rM8opG1MM4Vpx1w_YQA_Z5lJFQWj_2Zb8LfrHitRMPM1-_CXHJHKF11hFxG8GQPLa6jFlOlslfexPXk_TbODTQswM2HyFnsly_Z6EmLUGwwSu-G20nr85njNbcJYvOrsyZGRes4xO7cnQ4orapsAAPli2igun2tDWUiWa8SyGwvxuA6HLSwGpM4mIDcw13va2J_C_5UzTzRExovj4OF--FfG8Alm1ybnin5jYakeP1wYD_v8kR8HLZ6mu6mSNk1AYCfj58dW4wVEgDbDOB7IllqYW5SpPxF4XCyCdtCTXQ12AwUEIH_4FJ_x4jYGeicu1rW9LQmtmNqC5I1hL4knRrrW0Enju0U-Hun1ZctryGbHgataaIT-sQlmgpbomlGjwtbtUwydmCLmV4Wfg1W11ftBB3iZ2WWrvC2xXQv_9-rl_2Wc9rtqqFURzGe3IXX9R57jHqx8_9Q9Z_8ugu7qicYUQxBVURHah28MVZQkuy5zI3xtqj2SJpathJt6zRV5zgxHQqBXaqip41U0Bv0CYv3UwY1W_NW8f7fAUbqlY`
10461	2023-03-31 10:29:14	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Checking for link errors...
10462	2023-03-31 10:29:14	WARNING	pyload	DOWNLOADER DdownloadCom[4205]: 1 hour, 59 minutes, 45 seconds
10463	2023-03-31 10:29:14	INFO	pyload	DOWNLOADER DdownloadCom[4205]: Waiting 1 hour, 59 minutes, 45 seconds...
```

**Comment by GammaC0de** [comment] 2023-03-31 09:15
`SSL certificate problem: unable to get local issuer certificate`
duplicate of #4273

**Closed by GammaC0de** 2023-03-31 09:15 UTC
Labels: bug, pyLoad Next
