### ISSUE TITLE
Pyload not Extracting

### ISSUE THREAD

**Issue by faithless1108** [pyload/pyload#2329] opened 2016-02-03 09:20 UTC
Hi Folks, 

i found a porblem with the ExtractArchive-Plugin. After the Package finisches the ExtractArchive Plugin isnt even called. Log doesn't say anything about the "ExtractArchive-Plugin" after it shows the "Package finished"-Message.

Any Ideas on this?

Greez
Faith

331	03.02.2016 09:21:21	INFO	Package finished: XXXXXXXXXXXXXXXXXXXXXXX
![unbenannt](https://cloud.githubusercontent.com/assets/6443821/12777863/b65f8896-ca5f-11e5-89fe-64a456b32262.PNG)
.COMPLETE.BLURAY-LeetHD - filecrypt.cc
332	03.02.2016 09:21:21	DEBUG	ADDON ExternalScripts: No script found under folder `package_finished`
333	03.02.2016 09:21:21	DEBUG	ADDON ExternalScripts: No script found under folder `package_finished`
334	03.02.2016 09:21:21	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
335	03.02.2016 09:21:21	DEBUG	All downloads processed
336	03.02.2016 09:21:21	DEBUG	ADDON ExternalScripts: No script found under folder `package_finished`
337	03.02.2016 09:21:21	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
338	03.02.2016 09:21:21	DEBUG	All downloads processed
339	03.02.2016 09:21:21	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_processed`
340	03.02.2016 09:21:21	DEBUG	All downloads processed
341	03.02.2016 09:21:21	DEBUG	ADDON ExternalScripts: No script found under folder `all_downloads_finished`
342	03.02.2016 09:21:21	DEBUG	All downloads finished

**Comment by Frozen-byte** [comment] 2016-02-03 11:31
Yet another duplicate.
Have a look: https://github.com/pyload/pyload/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ExtractArchive+

**Comment by vuolter** [comment] 2016-02-03 13:07
Oh my, at least a third of the bug you can found here is a duplicate or the duplicate of duplicates. XD

**Comment by Velociraptor85** [comment] 2016-07-22 10:10
@faithless1108 Since this is a Duplicate for https://github.com/pyload/pyload/issues/2168
And is fixed via https://github.com/pyload/pyload/pull/2500 I am closing this

**Closed by Velociraptor85** 2016-07-22 10:10 UTC
Labels: duplicate, plugin issue
