### ISSUE TITLE
Premium download failed | TEXTAREA F1 not found | Plugin may be unstable

### ISSUE THREAD

**Issue by bcclsn** [pyload/pyload#3185] opened 2018-06-13 10:33 UTC
hi,

I have try to download from easybytez (premium account), but download not start... and [THIS](https://hastebin.com/imucafohec.pl) is the log.

I have already disabled XFileSharing and XFileSharingFolder plugins but with some links I got the same problem.

**Comment by GammaC0de** [comment] 2018-06-13 21:17
Free download tested and works, 
Account information is needed for testing, please set to a temporary password and then send account user and password to nitzo2001 at yahoo dot com.

**Comment by bcclsn** [comment] 2018-06-14 11:58
unfortunately, I can't send you the account information, because it isn't my account :(
can I try to help you in other way?

thanks in advance

**Comment by GammaC0de** [comment] 2018-06-15 08:27
Sorry, as I said, it works without an account, I can't proceed without one..

Can you try removing the account and then see if you can download without it?

**Comment by GammaC0de** [comment] 2018-06-18 06:10
So it's a dead end..
The problem is only with premium download and I do not have an account to test..

Have no other option but close this issue, sorry.

**Closed by GammaC0de** 2018-06-18 06:10 UTC
Labels: feedback wanted, question

**Comment by bcclsn** [comment] 2018-06-18 20:05
:(
