### ISSUE TITLE
ExtractArchive: No password found

### ISSUE THREAD

**Issue by schlamar** [pyload/pyload#3331] opened 2019-02-28 17:53 UTC
ExtractArchive can't extract a rar with a password anymore.

I have added a debug output after `reload_passwords` to verify that passwords are actually loaded from the password file (the "Passwords: " line above). Here is the full debug output:

    01.03.2019 01:18:49 DEBUG     ADDON ExtractArchive: Use for extensions: .7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
    01.03.2019 01:18:49 DEBUG     ADDON ExtractArchive: Passwords: ['password']
    01.03.2019 01:18:49 INFO      ADDON ExtractArchive: Check package: Package
    01.03.2019 01:18:49 DEBUG     All downloads processed
    01.03.2019 01:18:49 DEBUG     ADDON ExtractArchive: Targets for UnRar: [(51, '/mnt/media/downloads/package.rar', '/mnt/media/downloads/')]
    01.03.2019 01:18:49 INFO      ADDON ExtractArchive: package.rar | Extract to: /mnt/media/downloads/
    01.03.2019 01:18:49 DEBUG     ADDON ExtractArchive: Password: None provided
    01.03.2019 01:18:49 DEBUG     EXTRACTOR UnRar: EXECUTE unrar l -o- -or -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- -v /mnt/media/downloads/package.rar
    01.03.2019 01:18:49 DEBUG     ADDON ExtractArchive: Extracting using password: None
    01.03.2019 01:18:49 DEBUG     EXTRACTOR UnRar: EXECUTE unrar e -o- -or -x*.nfo -x*.DS_Store -xindex.dat -xthumb.db -y -p- /mnt/media/downloads/package.rar /mnt/media/downloads/
    01.03.2019 01:18:55 ERROR     ADDON ExtractArchive: package.rar | No password found
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/threading.py", line 774, in __bootstrap
        self.__bootstrap_inner()
      File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/home/user/pyload/module/PluginThread.py", line 459, in run
        self.f(*self.args, **self.kwargs)
      File "/home/user/pyload/module/plugins/hooks/ExtractArchive.py", line 177, in extract_queued
        if self.extract(packages, thread):  # @NOTE: check only if all gone fine, no failed reporting for now
      File "/home/user/pyload/module/plugins/hooks/ExtractArchive.py", line 327, in extract
        new_files = self._extract(pyfile, archive, pypack.password)
      File "/home/user/pyload/module/plugins/hooks/ExtractArchive.py", line 463, in _extract
        archive.extract(password)
      File "/home/user/pyload/module/plugins/internal/UnRar.py", line 149, in extract
        raise PasswordError
    PasswordError

    01.03.2019 01:18:55 DEBUG     All downloads finished
    01.03.2019 01:18:55 ERROR     ADDON ExtractArchive: package.rar | Extract failed
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/threading.py", line 774, in __bootstrap
        self.__bootstrap_inner()
      File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/home/user/pyload/module/PluginThread.py", line 459, in run
        self.f(*self.args, **self.kwargs)
      File "/home/user/pyload/module/plugins/hooks/ExtractArchive.py", line 177, in extract_queued
        if self.extract(packages, thread):  # @NOTE: check only if all gone fine, no failed reporting for now
      File "/home/user/pyload/module/plugins/hooks/ExtractArchive.py", line 327, in extract
        new_files = self._extract(pyfile, archive, pypack.password)
      File "/home/user/pyload/module/plugins/hooks/ExtractArchive.py", line 531, in _extract
        raise Exception(_("Extract failed"))
    Exception: Extract failed

**Comment by GammaC0de** [comment] 2019-02-28 18:15
@schlamar Are you using the passwords file or have you put the password int the add URL dialog?

**Comment by schlamar** [comment] 2019-02-28 18:23
passwords file

**Comment by schlamar** [comment] 2019-02-28 18:29
I guess `archive.verify`does not raise PasswordError and in this case you are extracting without a password.

**Comment by GammaC0de** [comment] 2019-02-28 18:38
Did it work with the passwords file in the past?

**Comment by schlamar** [comment] 2019-02-28 18:44
Yes. I guess the `_RE_FILES` doesn't work with current unrar (5.70).

Here is the output:


     Attributes      Size     Date    Time   Name
    ----------- ---------  ---------- -----  ----
    *   ..A.... 972127787  2019-02-17 11:45  file

And this is returned from `_RE_FILES.findall`

    (' ', '..A....', '972127787', '2019-02-17', '11:45', 'file')

**Comment by schlamar** [comment] 2019-02-28 18:48
OK, this fixes it for me:

    _RE_FILES_V5 = re.compile(r'([* ])\s+([ACHIRS.rw\-]+)\s+(\d+)(?:\s+\d+)?(?:\s+(?:\d+%|-->|<--))?\s+([\d-]+)\s+([\d:]+)(?:\s+[0-9A-F]{8})?\s+(.+)')

(just placed the `\s+` after `([* ])`

**Comment by GammaC0de** [comment] 2019-02-28 18:59
>OK, this fixes it for me:

I don't think it solves all the issues (try adding passwords to the top of the passwords file and see..), 

BTW, this is duplicate of #3325

**Comment by schlamar** [comment] 2019-02-28 19:15
This is the correct solution.

Empty password is getting added to the password file if verify doesn't raise a PasswordError: https://github.com/pyload/pyload/blob/8684991d3c/module/plugins/hooks/ExtractArchive.py#L454

**Comment by UserX404** [comment] 2019-02-28 21:27
I also noticed the inserting of an empty line. So the password is handled as 'NONE'

**Comment by GammaC0de** [comment] 2019-03-01 09:16
> So the password is handled as 'NONE'

 'NONE' means no password.

**Comment by schlamar** [comment] 2019-03-01 09:29
> 'NONE' means no password.

Yes. As `verify` doesn't raise a PasswordError, pyload thinks the archive is not encrypted and it tries to extract it without a password. `verifiy` needs to be fixed to raise PasswordError correctly in case of an encrypted archive. 

Why `verifiy` is wrong I have explained [above](https://github.com/pyload/pyload/issues/3331#issuecomment-468389194) (the star `*` indicating an encrypted file is not catched by the regular expression).

**Comment by GammaC0de** [comment] 2019-03-01 10:06
> Yes. As `verify` doesn't raise a PasswordError, pyload thinks the archive is not encrypted and it tries to extract it without a password. `verifiy` needs to be fixed to raise PasswordError correctly in case of an encrypted archive.

Yes, all of this has already been discussed in #3325

> Why `verifiy` is wrong I have explained [above](https://github.com/pyload/pyload/issues/3331#issuecomment-468389194) (the star `*` indicating an encrypted file is not catched by the regular expression).

Yes, I know that, but:
the star `*` is indeed indicating an encrypted file but it present even if you put the correct password so
checking if a star is present is not a good method for verifying a correct password.
So the only way to verify a correct password is to issue a test command to unrar.
So that means one more extra pass for every password in the passwords file...

**Comment by schlamar** [comment] 2019-03-01 10:18
You are not getting it...

> So that means one more extra pass for every password in the passwords file...

pyload is already doing exactly that: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExtractArchive.py#L464

But only if `verify` raises PasswordError and the `encrypted` flag is set here https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExtractArchive.py#L427

> the star `*` is indeed indicating an encrypted file but it present even if you put the correct password

Yes, but the star `*` is not detected by the regular expression, probably because unrar changed its output format.

**Comment by GammaC0de** [comment] 2019-03-01 10:36
Password verification is actually done here https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExtractArchive.py#L421 (`verifiy` checks if the star is present - i know the regex is wrong, but fixing the regex does not help detecting a correct password)

> As `verify` doesn't raise a PasswordError, pyload thinks the archive is not encrypted and it tries to extract it without a password. `verifiy` needs to be fixed to raise PasswordError correctly in case of an encrypted archive.

Correct.
How would you do that? you have to run `unrar t` command for every password..

**Comment by schlamar** [comment] 2019-03-01 10:52
> How would you do that? you have to run `unrar t` command for every password

**Again, pyload is doing that already**: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ExtractArchive.py#L464

So fixing the regex does help detecting a correct password.

> Depending the archive size, `unrar t` may take quite time to finish..

Nope, for my case (tested with 3 wrong passwords in a 800MB file) the PasswordError is raised quite instantly in `extract`...

**Comment by schlamar** [comment] 2019-03-01 10:59
Just to make it more clear:

- pyload calls `verify` with every password (probably because other plugins can detect a correct pw in `verify`, `UnRar` can't apparently).
- if `verify` succeeded, `extract` is called with the pw from `verifiy` call
- if `verifiy` failed with PasswordError (`encrypted` flag set), pyload call `extract` with every password

**Comment by GammaC0de** [comment] 2019-03-01 11:17
What happens when "overwrite" setting is set to False andf you extract first with a wrong password and after that with a correct one?
You would get corrupted extracted files...

**Closed** 2019-03-03 20:47 UTC

**Comment by GammaC0de** [comment] 2019-03-03 20:55
Done,
The problem is that  if overwite flag is False, UnRAR keeps corrupted files if you put a wrong password.
The next time you run UnRAR you extract with a correct password, the output file name will be something like `unpacked (1).exe`..

So you end up with a corrupted `unpacked.exe` and a correct `unpacked (1).exe`...

I don't recommend to use UnRAR ,
Better use 7Zip.
