### ISSUE TITLE
uploaded.to free download: "download link not found"

### ISSUE THREAD

**Issue by RyanAir123** [pyload/pyload#3093] opened 2018-02-06 14:14 UTC
Hi,

since approximately two weeks my pyLoad doesn't download from uploaded.to anymore. See below for the exact error message, I've copied the relevant part of the log. As far as I see the captcha is retrieved correctly, in the example below I solved it manually. The used pyLoad version is pyload - 0.4.9-20161208-1 (from opkg NG repository). The update server seems to work properly, I replaced the file /pyload/userplugins/hooks/UpdateManager.py with the new one. 

Any idea? Thanks in advance!

best regards
 
```

391 | 06.02.2018 13:43:09 | INFO | Download starts: Testfile.rar
392 | 06.02.2018 13:43:09 | WARNING | HOSTER UploadedTo[114]: Plugin may be unstable
393 | 06.02.2018 13:43:09 | INFO | HOSTER UploadedTo[114]: Grabbing link info...
394 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Link name: Testfile.rar
395 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Link size: 90.00 MiB (946864 bytes)
396 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Link status: online
397 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Processing url: http://uploaded.net/file/blahblah
398 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Looking for direct download link...
399 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Direct download link not found
400 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Checking for link errors...
401 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: No errors found
402 | 06.02.2018 13:43:10 | INFO | HOSTER UploadedTo[114]: Processing as free download...
403 | 06.02.2018 13:43:10 | WARNING | CAPTCHA UploadedTo[114]: ReCaptcha \| Could not properly detect ReCaptcha version, defaulting to v1
404 | 06.02.2018 13:43:10 | INFO | CAPTCHA UploadedTo[114]: ReCaptcha \| Using OCR to decrypt captcha...
405 | 06.02.2018 13:43:10 | WARNING | CAPTCHA UploadedTo[114]: ReCaptcha \| No OCR result
406 | 06.02.2018 13:43:24 | INFO | CAPTCHA UploadedTo[114]: ReCaptcha \| Captcha result: `bebas calle`
407 | 06.02.2018 13:43:24 | INFO | CAPTCHA UploadedTo[114]: ReCaptcha \| Path deleted:  /pyload/tmp/captcha_image_UploadedTo_59074.jpg
408 | 06.02.2018 13:43:26 | INFO | HOSTER UploadedTo[114]: Checking for link errors...
409 | 06.02.2018 13:43:26 | INFO | HOSTER UploadedTo[114]: No errors found
410 | 06.02.2018 13:43:26 | WARNING | HOSTER UploadedTo[114]: Free download failed \| Parse error: Free download link not found \| Plugin may be out of date
411 | 06.02.2018 13:43:26 | WARNING | Download failed: Testfile.rar \| Parse error: Free download link not found \| Plugin may be out of date
 
```

**Comment by GammaC0de** [comment] 2018-02-06 18:16
Duplicate of #3074, unfortunately no solution yet.

**Closed by GammaC0de** 2018-02-06 18:16 UTC
Labels: duplicate, plugin issue
