### ISSUE TITLE
[unrar] pyLoad thinks all Archives are PW protected

### ISSUE THREAD

**Issue by michiil** [pyload/pyload#1057] opened 2015-01-18 19:38 UTC
hey guys,
since a few days my pyload (running on a OMV debian server) wont extract any archives. I always get:

  Code:
1002   16.01.2015 21:33:15   INFO   ExtractArchive: hp-stirblangsam5-xvid.part1.rar | Extract to: /media/958861ad-4f33-456e-80e6-a1dffb7236b7/NAS/Download/stirblangsam5/
1003   16.01.2015 21:33:15   INFO   ExtractArchive: hp-stirblangsam5-xvid.part1.rar | Password protected
1004   16.01.2015 21:33:15   ERROR   ExtractArchive: hp-stirblangsam5-xvid.part1.rar | No password found
1005   16.01.2015 21:33:15   ERROR   ExtractArchive: hp-stirblangsam5-xvid.part1.rar | Extract failed
1006   16.01.2015 21:33:15   WARNING   ExtractArchive: hp-stirblangsam5-xvid.part1.rar | No files extracted

but the files arent pw protected. i am able to extract them via "unrar x ..." on ssh without entering a pw.
i am downloading from various hostera via a premiumize account.

Here is the forum thread to this issue:
http://forum.pyload.org/viewtopic.php?f=12&t=3940&sid=ab6a66f4443948bd3549414854421931

**Comment by kasperj** [comment] 2015-01-20 10:31
https://github.com/pyload/pyload/issues/1011
https://github.com/pyload/pyload/issues/1023

ExtractArchive is still broken, hopefully it will be fixed soon!

**Comment by michiil** [comment] 2015-01-20 14:03
The wierd thing is it worked a few days ago and i dont know what changed..

**Comment by himbrr** [comment] 2015-01-20 18:54
Update: Even if the correct password is provided, it can't successfully extract the files.

8721	20.01.2015 19:40:34	INFO	ExtractArchive: x.rar | Password protected
8722	20.01.2015 19:40:34	ERROR	ExtractArchive: x.rar | Wrong password
8723	20.01.2015 19:40:34	ERROR	ExtractArchive: x.rar | Extract failed
8724	20.01.2015 19:40:34	WARNING	ExtractArchive: x.rar | No files extracted

Copied the password from the webui and tried to extract it manually -> No problems.

**Comment by michiil** [comment] 2015-01-21 21:54
I made a script that extracts the downloadet rar files until ExtractArchive is fixed:
http://pastebin.com/nr9Q4AcD
just put it into /scripts/package_finished , restart pyload and it should do the job. it only works for unprotected rar archives for now since this is the main thing i am downloading.
You have edit the path to the log file if its different on your installation of pyload. You can also edit the UNRAR_PARAMETER, its explained in the script.
If everything works it should give you somethig like this:
http://pastebin.com/CcnaNenj
have fun (:

**Comment by kb0n** [comment] 2015-01-23 10:05
I just had the same problem and check the code. The problem seems to be obvious and caused by commit e2d8d605:
```python
# module/plugins/hook/ExtractArchive.py , line 305
[298]    def _extract(self, plugin, fid):
[...]
[305]            encrypted = True  #@TODO: set to `False`
```
should be
```python
[298]    def _extract(self, plugin, fid):
[...]
[305]            encrypted = False
```
Did not test it yet, but this seems to be reasonable

**Comment by vuolter** [comment] 2015-01-24 00:52
@kb0n Done: https://github.com/pyload/pyload/commit/d6fc06740679154f67a0f95aba5463dda1ecf3fb

**Comment by michiil** [comment] 2015-01-24 14:38
Thanks @voulter its fixed now (;

**Closed** 2015-01-24 14:38 UTC
Labels: plugin issue
