### ISSUE TITLE
UploadedTo Plugin downloads only the HTML Site and not the File

### ISSUE THREAD

**Issue by Serverfrog** [pyload/pyload#2190] opened 2015-12-10 13:15 UTC
The UploadedTo Plugin downloads only the HTML Site of a download and not the File.
Here is the Log:

```
10.12.2015 13:56:32 INFO      Received Quit signal
10.12.2015 13:56:34 INFO      starte pyLoad 0.4.9
10.12.2015 13:56:34 INFO      Benutze Home-Verzeichnis: /user/.pyload
10.12.2015 13:56:34 DEBUG     Remote activated: True
10.12.2015 13:56:36 DEBUG     created index of plugins
10.12.2015 13:56:36 INFO      ExtractArchive: Aktiviert UnRar UnZip
10.12.2015 13:56:36 INFO      Aktivierte Plugins: CaptchaTrader, ClickAndLoad, ExternalScripts, ExtractArchive, UpdateManager
10.12.2015 13:56:36 INFO      Deaktivierte Plugins: Ev0InFetcher, HotFolder, IRCInterface, MergeFiles, MultiHome, MultishareCz, RealdebridCom, RehostTo, XMPPInterface
10.12.2015 13:56:36 INFO      Downloadzeit: True
10.12.2015 13:56:36 INFO      Starte ThriftBackend: 0.0.0.0:7227
10.12.2015 13:56:38 INFO      Free space: 71.88 GiB
10.12.2015 13:56:38 INFO      Starting builtin webserver: 0.0.0.0:8000
10.12.2015 13:56:38 INFO      Activating Accounts...
10.12.2015 13:56:38 DEBUG     Redirected import module.plugins.accounts.UploadedTo -> userplugins.accounts.UploadedTo
10.12.2015 13:56:38 DEBUG     UploadedTo: Get Account Info for {AccountId}
10.12.2015 13:56:39 DEBUG     UploadedTo: Account Info: {'maxtraffic': {maxTraffic}, 'validuntil': {validUntil}, 'trafficleft': {trafficLeft}}
10.12.2015 13:56:39 INFO      Activating Plugins...
10.12.2015 13:56:39 INFO      pyLoad is up and running
10.12.2015 13:56:41 WARNING   Not able to connect server for updates
10.12.2015 13:56:41 INFO      No Updates for pyLoad
10.12.2015 13:56:42 WARNING   Not able to connect server for updates
10.12.2015 13:56:42 INFO      No plugin updates available
10.12.2015 13:56:55 INFO      Added package {packageName} containing 1 links
10.12.2015 13:56:55 INFO      Decrypting starts: {packageFolder}
10.12.2015 13:56:55 DEBUG     Parsed package {package} with 110 links
10.12.2015 13:56:55 INFO      Added package {package} containing 110 links
10.12.2015 13:56:55 DEBUG     Run Info Fetching for UploadedTo
10.12.2015 13:56:56 DEBUG     Finished Info Fetching for UploadedTo
10.12.2015 13:56:57 INFO      Download starts: part001.rar
10.12.2015 13:56:57 DEBUG     UploadedTo: Get Account Info for {AccountId}
10.12.2015 13:56:58 DEBUG     UploadedTo: Account Info: {'maxtraffic': {maxTraffic}, 'validuntil': {validUntil}, 'trafficleft': {trafficLeft}}
10.12.2015 13:56:58 DEBUG     UploadedTo: Use Premium Account (muchGB left, wow)
10.12.2015 13:56:58 INFO      Download finished: part001.rar
```

The HTML Site

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
        <title>part001.rar (99,83 MB) - uploaded.net</title>
    <base href="http://uploaded.net/" />
        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
        <meta name="revisit-after" content="1 days" />
        <meta name="description" content="the easiest way to backup and share your files with everyone." />
        <meta name="keywords" content="uploaded, ul, uploaded.to, ul.to, upload, download, free, premium, one click hoster, och, sharehoster" />
        <meta name="author" content="uploaded.net" />
        <meta name="owner" content="uploaded.net" />
        <meta name="RATING" content="General">
        <meta name="language" http-equiv="content-language" content="en" />
        <!--<meta property="fb:page_id" content="217881528283333" />-->
                <link rel="stylesheet" href="/img/layout.css?xcache=3232" />
        <!--[if !IE]><!--><link rel="stylesheet" href="/img/noIE.css" /><!--<![endif]-->        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <meta http-equiv="Content-Script-Type" content="text/javascript" />
        <script type="text/javascript" src="/js2/protoculous.js?v=1"></script>
        <script type="text/javascript" src="/js2/yahoo-dom-event.js"></script>
        <script type="text/javascript" src="/js2/element-min.js"></script>
        <script type="text/javascript" src="/js2/uploader-min.js"></script>
        <script type="text/javascript" src="/js2/md5.js"></script>
        <script type="text/javascript" src="/js/script.js"></script>
                        </head>

<body>

<script type="text/javascript">
        if(parent.frames.length > 0)
                top.location.href = self.location;
</script>

<div id="head">
        <div class="center">

                        <a href="" id="logo"><img src="/img/uploaded.png" /></a>

                <div class="navi">
                                                <ul class="user">
                                <input type="hidden" id="user_id" value="userid" />
                                <input type="hidden" id="user_mail" value="my email" />
                                <input type="hidden" id="user_pw" value="pw" />
                                <li><a href="me">Profile</a></li> &middot;
                                <li><a href="manage">Files &amp; Folders</a></li> &middot;
                                <li><a href="/udrive">uDrive</a></li> &middot;
                                <li><a href="affiliate">Affiliate program</a></li> &middot;
                                <li><a href="logout">Logout</a></li>
                        </ul>
                                                                        <div id="nupload"></div>
                                        </div>
        </div>

        <noscript style="position:absolute;top:80px;width:100%;font-weight:bold;" class="cR aC">
                <span style="margin-left:150px;">You have to enable JavaScript to use uploaded!</span>
        </noscript>
</div>
<div class="hshadow"></div>

<div class="bga">
        <div id="content">


<div id="download" class="center">

        <ul id="headmenu">
                                        <li><div class="icon" style="background-position:-12px -155px"></div> <span class="a" id="ilike" onclick="like('xpkucjjr')">i like</span></li>                                  <li><div class="icon" style="background-position:-24px -155px"></div> <span class="a" id="import" onclick="importFile('xpkucjjr')">import to my account</span></li>                  </ul><br />



                <div id="fblike" style="float:left;margin:2px 25px 0 25px;width:70px;height:110px">
                <iframe src="http://uploaded.net/img/fb.html" style="width:100%;height:100%;border:0px" scrolling="no" frameborder="0"></iframe>
        </div>

        <div class="title" style="float:left;width:78%">
                <small class="date" style="text-transform:uppercase">Download file:</small>

                <h1 style="font-size:38px;line-height:40px;text-shadow:0 -1px 1px #BBC8D9, 0 1px 1px #fff"><a href="file/xpkucjjr" id="filename">the filename</a> &nbsp;
                        <small style="border-radius:5px;padding:0 3px;text-shadow:none;background:#ebebeb;color:#bbbbbb;font-size:11px;">99,83 MB</small>
                </h1>
                        </div>
    <div style="clear: both;"></div>

        <br style="clear:both" />
        <div class="hshadow"></div>
        <div class="tfree" style="min-height:100px;margin:23px auto 10px;width:34%">
                                        <form method="post" action="the Post Action" style="width:290px;margin-left:-2px">
                                <button type="submit" class="prem">
                                        <h1>Premium Download</h1>
                                </button>
                        </form>
                        </div>
        </div>
        <br style="clear:both" />
<script type="text/javascript">
function importFile(auth){
        var isUser = true;
        var c = $('import');

        if(isUser){
                c.update('Loading&hellip;');
                new Ajax.Request('io/import', {onComplete:function(t){
                        t = t.responseText.substr(0, t.responseText.length-1).evalJSON();

                        if(t.err)
                                 return c.update('<b class="cR">Error:</b> '+t.err);

                        c.update('<b class="cG">OK</b>');

                        if(confirm("The file was imported into your account\nDo you want to switch to the filemanager now?"))
                                top.location.href = '/manage';

                }.bind(this),parameters:'urls=http://ul.to/xpkucjjr'});
        }
        else
                return top.location.href = '/register';
}

function like(auth)
{
        var c = $('ilike');

        new Ajax.Request('io/fav/add/'+auth, {parameters:'type=file',onComplete:function(t){
                c.replace('<span id="likestatus" class="cG" style="padding-left:3px">'+t.responseText.gsub(' ', '&nbsp;')+'</span>');
                $('likestatus').highlight({endcolor:'#f8f8f8'});
        }});
}
</script>




        </div>

        <div id="foot"><div>
                <div class="center">
                                                        <a href="affiliate">Affiliate program</a>&middot;
                                                <a href="legal">TOS &  Guidelines</a>&middot;
                        <!---->
                        <!--<a href="policy">Child Pornography Policy</a> &middot;-->
                        <a href="help">Support</a> &middot;
                        <a href="/products">Products</a> &middot;
            <a href="corporate">Corporate products</a> <br/>

            <a href="/takedown/notice">Takedown</a>&middot;
            <a href="about">Advertising</a> &middot;
                        <a href="about">Contact</a>

                        <div style="width: 155px;" class="right aR">
                                <b>Language:</b>
                <span class="a" id="language">English</span>
                <a title="Twitter @ul_to" href="http://twitter.com/ul_to" target="_blank" class="twitter-icon"></a>
                                                        </div>
                        <div class="footlogo"></div>
                </div>
        </div></div>
</div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34088231-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script><!-- 2015-12-10 14:00:40 / 0.029530048370361 -->

</body></html>
```

**Comment by Bambie42** [comment] 2015-12-11 07:50
Have you tried to activate "direct downloads" in your uploaded account settings?

**Comment by Serverfrog** [comment] 2015-12-11 09:27
i dont have some kind of option. Either in the Account settings nor in the Plugin settings

**Comment by Serverfrog** [comment] 2015-12-11 10:01
Ok, in the Settings on Uploaded.to. But that is not a kind of solution, it is a workaround

**Comment by GammaC0de** [comment] 2015-12-11 21:10
@Serverfrog I can see two reasons for that:
1) If it works don't fix it.
2) Using the "direct downloads" feature is the preferable direction when downloading premium because that way the download process is as simple a fetching the URL.
That way, you don't have to worry when the hoster changes something on the site - the download will work

**Comment by bepix** [comment] 2015-12-17 13:59
Same here with ShareonlineBiz. Please reopen and/or aggregate to multiple hosters.

**Comment by Serverfrog** [comment] 2015-12-17 14:17
@GammaC0de 
1) It has not worked so i tried to fix it
2) if i use uploaded.to other then with pyload (From my desktop and pyload is on my raspberry pi) then i would like to see what i download bevor it started

**Comment by sraedler** [comment] 2016-02-14 22:17
This is a bug in an old uploaded version, I could not reproduce

please close

**Comment by icep87** [comment] 2016-03-28 17:39
The same issue exists now on Synology Download Station as of DSM 6.0 as they are using this plugin. It only downloads the HTML file.

**Comment by GammaC0de** [comment] 2016-03-28 17:46
An account is needed for testing.
Please send account info to nitzo2001 \[AT\] yahoo \[DOT\] com.

**Comment by icep87** [comment] 2016-03-28 17:47
Download Station seems to be using version 0.40 of the uploaded plugin. I will wait for an updated from Synology to see if issues is resolved in 0.41.

**Comment by GammaC0de** [comment] 2016-03-28 17:58
@icep87 See https://github.com/pyload/pyload/issues/2241 on how to do a manual update

**Comment by GammaC0de** [comment] 2017-02-18 02:59
Closing this issue.

**Closed by GammaC0de** 2017-02-18 02:59 UTC
Labels: account wanted, plugin issue
