### ISSUE TITLE
Info Fetching for OneFichierCom failed | 'name'

### ISSUE THREAD

**Issue by fifi44** [pyload/pyload#1981] opened 2015-10-08 14:19 UTC
Hi,

i have some troubles with all my download.
The same error appeares with OneFichierCom or Uplea 
log trace 

08.10.2015 10:29:20	INFO	HOOK XFileSharingPro: Handling any hoster I can!
14	08.10.2015 10:29:20	INFO	HOOK XFileSharingPro: Handling any crypter I can!
15	08.10.2015 10:29:20	INFO	pyLoad is up and running
16	08.10.2015 10:29:21	INFO	ADDON UpdateManager: No new pyLoad version available
17	08.10.2015 10:29:21	INFO	ADDON UpdateManager: No plugin updates available
18	08.10.2015 10:29:31	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
19	08.10.2015 10:29:54	INFO	Added package film containing 1 links
20	08.10.2015 10:29:54	WARNING	Info Fetching for UpleaCom failed | 'status'
21	08.10.2015 16:13:13	WARNING	Info Fetching for UpleaCom failed | 'status'
22	08.10.2015 16:13:13	INFO	Added package film containing 1 links
23	08.10.2015 16:13:59	INFO	Added package film containing 1 links
24	08.10.2015 16:14:07	WARNING	Info Fetching for OneFichierCom failed | 'name' 

donwload stays pending....

**Comment by joberreiter** [comment] 2015-10-08 14:54
Same problem / duplicate of #1931.

**Comment by vuolter** [comment] 2015-10-08 14:56
Just tries 1fitcher and uplea and working fine for me.
Sample url please.

**Closed** 2015-10-08 14:57 UTC
Labels: issue not reproduced, waiting feedback

**Comment by fifi44** [comment] 2015-10-08 15:19
https://1fichier.com/?c1q50lc158 for example

**Comment by vuolter** [comment] 2015-10-08 15:30
@fifi44 Tested and working with premium account on latest stable. Try: http://forum.pyload.org/viewtopic.php?f=7&t=4335
