### ISSUE TITLE
Plugin ddownload incorrect file names

### ISSUE THREAD

**Issue by B17C0D3** [pyload/pyload#4048] opened 2021-12-12 14:21 UTC
### Description

The downloaded files from Filehoster ddownload.com don't have the correct filename.
The same download from another filehoster gets the correct filename.

### Debug log

* Plugin list got cut to shorten it.

12.12.2021 15:00:49 INFO      Download starts: h--ps://ddownload.com/4f7fghxpzorv/American.Crime.Story.Impeachment.S03E10.Der.Starr-Report.GERMAN.5.1.DUBBED.DL.AC3.1080.p.WEB-DL.h.264-TvR.part5.rar
12.12.2021 15:00:49 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
12.12.2021 15:00:49 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
12.12.2021 15:00:49 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
12.12.2021 15:00:49 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
12.12.2021 15:00:49 DEBUG     HOSTER DdownloadCom[8705]: Plugin version: 0.10
12.12.2021 15:00:49 DEBUG     HOSTER DdownloadCom[8705]: Plugin status: testing
12.12.2021 15:00:49 WARNING   HOSTER DdownloadCom[8705]: Plugin may be unstable
12.12.2021 15:00:49 INFO      ACCOUNT DdownloadCom: Grabbing account info for user `wal*******`...
12.12.2021 15:00:49 DEBUG     ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
12.12.2021 15:00:49 DEBUG     ACCOUNT DdownloadCom: Expire date: 18 January 2023
12.12.2021 15:00:49 DEBUG     ACCOUNT DdownloadCom: Valid until: 1673996400.0
12.12.2021 15:00:49 DEBUG     ACCOUNT DdownloadCom: Size: 91493 | Unit: MB
12.12.2021 15:00:49 DEBUG     ACCOUNT DdownloadCom: LEECH TRAFFIC PATTERN not found
12.12.2021 15:00:49 DEBUG     ACCOUNT DdownloadCom: Account info for user `wal*******`: {'login': {'timestamp': 1639317444.978646, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account DdownloadCom>, 'leechtraffic': None, 'trafficleft': 95937363968, 'maxtraffic': None, 'validuntil': 1673996400.0, 'login': 'wal*******', 'type': 'DdownloadCom', 'options': {'limitDL': ['0']}}}
12.12.2021 15:00:49 INFO      HOSTER DdownloadCom[8705]: Grabbing link info...
12.12.2021 15:00:49 DEBUG     HOSTER DdownloadCom[8705]: LOAD URL h--ps://ddownload.com/4f7fghxpzorv | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
12.12.2021 15:00:50 ERROR     <<< UNCAUGHT EXCEPTION >>>
Traceback (most recent call last):
  File "/app/pyload/module/network/HTTPRequest.py", line 344, in write
    raise Exception("Loaded Url exceeded limit")
Exception: Loaded Url exceeded limit
12.12.2021 15:00:50 DEBUG     HOSTER DdownloadCom[8705]: Link info: {'status': 7, 'hash': {}, 'name': u'4f7fghxpzorv', 'url': u'h--ps://ddownload.com/4f7fghxpzorv', 'pattern': {'ID': u'4f7fghxpzorv'}, 'size': 0}
12.12.2021 15:00:50 DEBUG     HOSTER DdownloadCom[8705]: Previous link info: {}
12.12.2021 15:00:50 INFO      HOSTER DdownloadCom[8705]: Link name: 4f7fghxpzorv
12.12.2021 15:00:50 INFO      HOSTER DdownloadCom[8705]: Link size: N/D
12.12.2021 15:00:50 INFO      HOSTER DdownloadCom[8705]: Link status: starte
12.12.2021 15:00:50 INFO      HOSTER DdownloadCom[8705]: Processing url: h--ps://ddownload.com/4f7fghxpzorv/American.Crime.Story.Impeachment.S03E10.Der.Starr-Report.GERMAN.5.1.DUBBED.DL.AC3.1080.p.WEB-DL.h.264-TvR.part5.rar
12.12.2021 15:00:50 INFO      HOSTER DdownloadCom[8705]: Looking for direct download link...
12.12.2021 15:00:50 DEBUG     HOSTER DdownloadCom[8705]: LOAD URL h--ps://ddownload.com/4f7fghxpzorv | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
12.12.2021 15:00:51 DEBUG     HOSTER DdownloadCom[8705]: Redirect #1 to: h--ps://www29.ucdn.to:183/d/fr7a43bqzu2wwcue2bmdarluk3x2bm7w4atzrwumtpc7depyma26rjft3jwh2yyx2pb7py7k/American.Crime.Story.Impeachment.S03E10.Der.Starr-Report.GERMAN.5.1.DUBBED.DL.AC3.1080.p.WEB-DL.h.264-TvR.part5.rar
12.12.2021 15:00:51 DEBUG     HOSTER DdownloadCom[8705]: LOAD URL h--ps://www29.ucdn.to:183/d/fr7a43bqzu2wwcue2bmdarluk3x2bm7w4atzrwumtpc7depyma26rjft3jwh2yyx2pb7py7k/American.Crime.Story.Impeachment.S03E10.Der.Starr-Report.GERMAN.5.1.DUBBED.DL.AC3.1080.p.WEB-DL.h.264-TvR.part5.rar | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
12.12.2021 15:00:51 INFO      HOSTER DdownloadCom[8705]: Direct download link detected
12.12.2021 15:00:51 INFO      HOSTER DdownloadCom[8705]: Downloading file...
12.12.2021 15:00:51 DEBUG     HOSTER DdownloadCom[8705]: DOWNLOAD URL h--ps://ddownload.com/4f7fghxpzorv | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
12.12.2021 15:00:51 DEBUG     Chunked with range 0-
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: File saved
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: Checking download...
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: File is OK
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: Checking file (with built-in rules)...
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: Checking file (with custom rules)...
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: Checking for link errors...
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: No errors found
12.12.2021 15:01:13 INFO      HOSTER DdownloadCom[8705]: No errors found
12.12.2021 15:01:13 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
12.12.2021 15:01:13 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
12.12.2021 15:01:13 INFO      Download finished: 4f7fghxpzorv
12.12.2021 15:01:13 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
12.12.2021 15:01:13 DEBUG     ADDON Checksum: {'status': 7, 'hash': {}, 'name': u'4f7fghxpzorv', 'url': u'h--ps://ddownload.com/4f7fghxpzorv', 'pattern': {'ID': u'4f7fghxpzorv'}}
12.12.2021 15:01:13 INFO      Package finished: American.Crime.Story.Impeachment.S03.GERMAN.5.1.DUBBED.DL.AC3.1080p.WEB-DL.h264-TvR
12.12.2021 15:01:13 DEBUG     ADDON ExternalScripts: No script found under folder `package_finished`
12.12.2021 15:01:13 DEBUG     ADDON ExtractArchive: Use for extensions: .001|.7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
12.12.2021 15:01:13 INFO      ADDON ExtractArchive: Check package: American.Crime.Story.Impeachment.S03.GERMAN.5.1.DUBBED.DL.AC3.1080p.WEB-DL.h264-TvR
12.12.2021 15:01:13 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
12.12.2021 15:01:13 DEBUG     All downloads processed
12.12.2021 15:01:13 INFO      ADDON ExtractArchive: No files found to extract
12.12.2021 15:01:13 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_finished`
12.12.2021 15:01:13 DEBUG     All downloads finished

Another example with a short filename and without an UNCAUGHT EXCEPTION
File 'download_files.PNG' got downloaded as '12lldf605ani'

12.12.2021 15:54:37 INFO      Download starts: 12lldf605ani
12.12.2021 15:54:37 DEBUG     ADDON ExternalScripts: No script found under folder `download_preparing`
12.12.2021 15:54:37 DEBUG     ADDON UserAgentSwitcher: Setting connection timeout to 60 seconds
12.12.2021 15:54:37 DEBUG     ADDON UserAgentSwitcher: Setting maximum redirections to 10
12.12.2021 15:54:37 DEBUG     ADDON UserAgentSwitcher: Use custom user-agent string `Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
12.12.2021 15:54:37 DEBUG     HOSTER DdownloadCom[8711]: Plugin version: 0.10
12.12.2021 15:54:37 DEBUG     HOSTER DdownloadCom[8711]: Plugin status: testing
12.12.2021 15:54:37 WARNING   HOSTER DdownloadCom[8711]: Plugin may be unstable
12.12.2021 15:54:37 INFO      ACCOUNT DdownloadCom: Grabbing account info for user `wal*******`...
12.12.2021 15:54:37 DEBUG     ACCOUNT DdownloadCom: LOAD URL http://www.ddownload.com/ | redirect=True | cookies=True | get={'op': 'my_account'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
12.12.2021 15:54:38 DEBUG     ACCOUNT DdownloadCom: Expire date: 18 January 2023
12.12.2021 15:54:38 DEBUG     ACCOUNT DdownloadCom: Valid until: 1673996400.0
12.12.2021 15:54:38 DEBUG     ACCOUNT DdownloadCom: Size: 91389 | Unit: MB
12.12.2021 15:54:38 DEBUG     ACCOUNT DdownloadCom: LEECH TRAFFIC PATTERN not found
12.12.2021 15:54:38 DEBUG     ACCOUNT DdownloadCom: Account info for user `wal*******`: {'login': {'timestamp': 1639320869.377263, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account DdownloadCom>, 'leechtraffic': None, 'trafficleft': 95828312064, 'maxtraffic': None, 'validuntil': 1673996400.0, 'login': 'wal*******', 'type': 'DdownloadCom', 'options': {'limitDL': ['0']}}}
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Grabbing link info...
12.12.2021 15:54:38 DEBUG     HOSTER DdownloadCom[8711]: LOAD URL https://ddownload.com/12lldf605ani | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
12.12.2021 15:54:38 DEBUG     HOSTER DdownloadCom[8711]: Link info: {'status': 7, 'hash': {}, 'name': u'12lldf605ani', 'url': u'https://ddownload.com/12lldf605ani', 'pattern': {'ID': u'12lldf605ani'}, 'size': 0}
12.12.2021 15:54:38 DEBUG     HOSTER DdownloadCom[8711]: Previous link info: {}
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Link name: 12lldf605ani
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Link size: 10.00 KiB (10237 bytes)
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Link status: starte
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Processing url: https://ddownload.com/12lldf605ani
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Looking for direct download link...
12.12.2021 15:54:38 DEBUG     HOSTER DdownloadCom[8711]: LOAD URL https://ddownload.com/12lldf605ani | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
12.12.2021 15:54:38 DEBUG     HOSTER DdownloadCom[8711]: Redirect #1 to: https://www581.ucdn.to:183/d/an7qp5brzu2wwcuefzmtkejpltpj7y33gmocd2yhxxosj23hcpni6lakp4kcxssoac53vzmg/download_files.PNG
12.12.2021 15:54:38 DEBUG     HOSTER DdownloadCom[8711]: LOAD URL https://www581.ucdn.to:183/d/an7qp5brzu2wwcuefzmtkejpltpj7y33gmocd2yhxxosj23hcpni6lakp4kcxssoac53vzmg/download_files.PNG | redirect=True | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=True
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Direct download link detected
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Downloading file...
12.12.2021 15:54:38 DEBUG     HOSTER DdownloadCom[8711]: DOWNLOAD URL https://ddownload.com/12lldf605ani | cookies=True | resume=None | get={} | disposition=True | chunks=None | post={} | ref=True
12.12.2021 15:54:38 DEBUG     Chunked with range 0-
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: File saved
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Checking download...
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: File is OK
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Checking file (with built-in rules)...
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Checking file (with custom rules)...
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: Checking for link errors...
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: No errors found
12.12.2021 15:54:38 INFO      HOSTER DdownloadCom[8711]: No errors found
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `download_processed`
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `package_processed`
12.12.2021 15:54:38 INFO      Download finished: 12lldf605ani
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `download_finished`
12.12.2021 15:54:38 DEBUG     ADDON Checksum: {'status': 7, 'hash': {}, 'name': u'12lldf605ani', 'url': u'https://ddownload.com/12lldf605ani', 'pattern': {'ID': u'12lldf605ani'}}
12.12.2021 15:54:38 INFO      Package finished: example
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `package_finished`
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_processed`
12.12.2021 15:54:38 DEBUG     All downloads processed
12.12.2021 15:54:38 DEBUG     ADDON ExtractArchive: Use for extensions: .001|.7z|.bz2|.bzip2|.gz|.gzip|.lha|.lzh|.lzma|.rar|.tar|.taz|.tbz|.tbz2|.tgz|.xar|.xz|.z|.zip
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `all_downloads_finished`
12.12.2021 15:54:38 DEBUG     All downloads finished
12.12.2021 15:54:38 INFO      ADDON ExtractArchive: Check package: example
12.12.2021 15:54:38 INFO      ADDON ExtractArchive: No files found to extract
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `all_archives_extracted`
12.12.2021 15:54:38 DEBUG     ADDON ExternalScripts: No script found under folder `all_archives_processed`

### Screenshots

![download_files](https://user-images.githubusercontent.com/3804141/145716111-2c6a46f3-0523-4408-b804-6d92f3a50088.PNG)

**Comment by GammaC0de** [comment] 2021-12-13 21:42
This is duplicate of #4045

**Closed** 2021-12-14 23:37 UTC
Labels: plugin bug, pyLoad Stable
