### ISSUE TITLE
Support for Multiple Uploaded Premium Accounts (and possible for all hosters)

### ISSUE THREAD

**Issue by ClitCommander** [pyload/pyload#2384] opened 2016-03-18 00:33 UTC
*** FEATURE REQUEST ***

Hi guys,
is there a chance to make pyload supporting multiple uploaded premium accounts?
Last time i had more than one account added, 
pyload would only download from the first account,
but wont use the others if there was no traffic left on the first one.
i had to delete the "empty" one to start downloading with the next one.

desirable behaviour:
* if a download link is added, use the account with the most traffic left.
* try to distribute the traffic evenly between the accounts
* override this behaviour, and only use marked account    
(e.g. u have a coupon for 48h or something and you want to max this one out)

If this is too much, or would take too long,
can you add a checkbox, in the "Accounts" section, 
to disable accounts manually, so you dont have to delete them every time, 
when an account is maxed out?

sincerely,
your ClitCommander ^^

**Comment by GammaC0de** [comment] 2016-03-18 00:59
Duplicate of #2211

**Closed by GammaC0de** 2016-03-18 00:59 UTC
Labels: duplicate, feature request
