### ISSUE TITLE
invalid arguments to setopt

### ISSUE THREAD

**Issue by hardy123480** [pyload/pyload#1620] opened 2015-07-30 15:28 UTC
I'm getting a few errors:

WARNING	ACCOUNT ShareonlineBiz: Error loading info for user
WARNING	Download failed: xy.part14.rar | invalid arguments to setopt

**Comment by wweich** [comment] 2015-07-31 04:34
Duplicate of #1589 
Dev is working on it.

For the first line, check your account.conf. The password in that file was probably replaced with *******. (That error was fix recently)

**Closed** 2015-07-31 05:33 UTC
Labels: duplicate, plugin issue
