### ISSUE TITLE
Fshare.vn plugin cannot login

### ISSUE THREAD

**Issue by thachdpn** [pyload/pyload#4039] opened 2021-11-22 16:57 UTC
When i add a Fshare account , I receive an error

> [2021-11-22 23:53:53]  ERROR               pyload  ACCOUNT FshareVn: Could not login user `dun****` | Login handshake has failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyload/plugins/accounts/FshareVn.py", line 98, in signin
    api_data = self.api_request(
  File "/usr/lib/python3.8/site-packages/pyload/plugins/accounts/FshareVn.py", line 43, in api_request
    json_data = self.load(
  File "/usr/lib/python3.8/site-packages/pyload/plugins/base/plugin.py", line 218, in load
    html = req.load(
  File "/usr/lib/python3.8/site-packages/pyload/core/network/browser.py", line 127, in load
    return self.http.load(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyload/core/network/http/http_request.py", line 312, in load
    self.code = self.verify_header()
  File "/usr/lib/python3.8/site-packages/pyload/core/network/http/http_request.py", line 336, in verify_header
    raise BadHeader(
pyload.core.network.http.exceptions.BadHeader: Bad server response: 403 Forbidden
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyload/plugins/base/account.py", line 135, in login
    self.signin(self.user, self.info["login"]["password"], self.info["data"])
  File "/usr/lib/python3.8/site-packages/pyload/plugins/accounts/FshareVn.py", line 103, in signin
    self.fail_login()
  File "/usr/lib/python3.8/site-packages/pyload/plugins/base/account.py", line 484, in fail_login
    return self.fail(msg)
  File "/usr/lib/python3.8/site-packages/pyload/plugins/base/plugin.py", line 154, in fail
    raise Fail(msg)
pyload.core.network.exceptions.Fail: Login handshake has failed

**Comment by GammaC0de** [comment] 2021-11-22 21:56
duplicate of #4036,
See https://github.com/pyload/pyload/issues/4036#issuecomment-965810511

**Closed by GammaC0de** 2021-11-22 21:56 UTC
