### ISSUE TITLE
Required account not found

### ISSUE THREAD

**Issue by SebaBoler** [pyload/pyload#1880] opened 2015-09-27 18:24 UTC
I using NoPremiumPL after last update i have error

3399	27.09.2015 16:09:53	INFO	ADDON UnSkipOnFail: No duplicates found
3398	27.09.2015 16:09:53	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: Ray.Donovan.S03E10.PL.480p.HDTV.XviD.AC3-H3Q.avi (pid:462)
3397	27.09.2015 16:09:53	WARNING	Download failed: Ray.Donovan.S03E10.PL.480p.HDTV.XviD.AC3-H3Q.avi | Required account not found
3396	27.09.2015 16:09:53	INFO	Download starts: Ray.Donovan.S03E10.PL.480p.HDTV.XviD.AC3-H3Q.avi
3395	27.09.2015 16:09:53	INFO	Added package https://rapidu.net/7410834044/Ray.Donovan.S03E10.PL.480p.HDTV.XviD.AC3-H3Q.avi containing 1 links

**Comment by joberreiter** [comment] 2015-09-29 17:52
Duplicate of #1875, reported to be fixed with #1863, but not yet committed.

**Closed** 2015-10-02 10:40 UTC
Labels: duplicate, plugin issue
