### ISSUE TITLE
2 Accounts from one premium hoster? 

### ISSUE THREAD

**Issue by donaufisch66** [pyload/pyload#2339] opened 2016-02-11 15:06 UTC
Hello, 
How can I use two shareOnlineBiz accounts? I added 2 shareOnlineBiz premium accounts. pyload does not change the account when one ran out of trafficvolume. The active Account is changed to a free one with reduced speed instead of using the secound account wich has enough trafficvolume left. 
A restart doesnt help to change the Account.  I have to delete the first account, stop the process and Start pyload again. 
Do you know how I could tell pyload or the plugin to change accounts instead of switching from premium to free?
In Cash of both Accounts have active trafficvolume, how can I tell pyload to use both Accounts parallel?

**Comment by GammaC0de** [comment] 2016-02-11 15:09
duplicate of #2211

**Closed by GammaC0de** 2016-02-11 15:09 UTC
Labels: duplicate, feature request
