### ISSUE TITLE
lightweight server problem

### ISSUE THREAD

**Issue by maxbat10** [pyload/pyload#2932] opened 2017-08-15 16:38 UTC
Hello,

I would like to use the lightweight server bjoern. I was able to install it (following the guide [https://github.com/jonashaag/bjoern/wiki/Installation](url)), a I copied the _bjoern.so file into the /opt/pyload/module/lib folder.

Unfortunately, I still have the following error when I launch pyload :
`Error importing lightweight server: dynamic module does not define init function (initbjoern)
`

Do you have an idea on how to sole this problem and use bjoern ?

Thanks

**Comment by GammaC0de** [comment] 2017-08-17 01:52
What exatly do you try to accomplish? 
pyload has its own web server buitl-in...

**Comment by maxbat10** [comment] 2017-08-17 16:15
I would like to use bjoern instead of to the defaut web server, as mentioned at [https://pyload.net/](url) : 

>  bjoern (https://github.com/jonashaag/bjoern) More responsive web interface.

It is also proposed to use the light web server when you configure pyload, they explained that you need to install bjoern using their git, and to copy the bjoern.so file. That's what I don't achieve to do.

Thanks

**Comment by GammaC0de** [comment] 2017-08-17 17:28
And why use bjoern and not the built in servers?

**Comment by GammaC0de** [comment] 2017-08-17 19:02
Anyway:
`pip install bjoern`
`/usr/bin/pyLoadCore -s` and choose `lightweight` server.

Ubuntu 16.04 LTS works without issues, no copy of `bjoern.so`.

**Comment by maxbat10** [comment] 2017-08-17 20:39
Thank you for helping me.

I was able to install bjoern using `pip install bjoern` and I choose lightweight server.
I use Raspbian Jessie Lite.

I still have the following error messages when I launch pyload :
`17.08.2017 20:32:45 ERROR     Error importing lightweight server: dynamic module does not define init function (initbjoern)`
`17.08.2017 20:32:45 WARNING   You need to download and compile bjoern, https://github.com/jonashaag/bjoern`
`17.08.2017 20:32:45 WARNING   Copy the boern.so to module/lib folder or use setup.py install`
`17.08.2017 20:32:45 WARNING   Of course you need to be familiar with linux and know how to compile software`

**Comment by GammaC0de** [comment] 2017-08-17 22:20
Can you do this in python without errors?
```
import bjoern
```

**Comment by maxbat10** [comment] 2017-08-19 10:13
Sorry for the delay...

I have this error with this command :
`from: can't read /var/mail/bjoern`

**Comment by GammaC0de** [comment] 2017-08-19 21:26
No, you should do:
```
python
from bjoern import run
```

**Comment by maxbat10** [comment] 2017-08-19 23:34
Sorry..

I can do this without errors.

**Comment by GammaC0de** [comment] 2017-08-20 00:56
Start pyload with ` /usr/bin/pyLoadCore -d` and post the log from the console.

**Comment by maxbat10** [comment] 2017-08-20 10:06
Here it is !

> 20.08.2017 12:03:16 INFO      Démarrage pyLoad 0.4.9
20.08.2017 12:03:16 INFO      Utilisation du dossier principal : /media/maxtor
20.08.2017 12:03:16 DEBUG     Remote activated: True
20.08.2017 12:03:37 DEBUG     created index of plugins
20.08.2017 12:03:38 INFO      Plugins activés: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
20.08.2017 12:03:38 INFO      Plugins désactivés: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
20.08.2017 12:03:38 INFO      Temps de téléchargement : True
20.08.2017 12:03:38 INFO      Démarre ThriftBackend: 0.0.0.0:7227
20.08.2017 12:03:42 INFO      Free space: 6.73 GiB
20.08.2017 12:03:42 ERROR     Error importing lightweight server: dynamic module does not define init function (initbjoern)
20.08.2017 12:03:42 WARNING   You need to download and compile bjoern, https://github.com/jonashaag/bjoern
20.08.2017 12:03:42 WARNING   Copy the boern.so to module/lib folder or use setup.py install
20.08.2017 12:03:42 WARNING   Of course you need to be familiar with linux and know how to compile software
20.08.2017 12:03:42 INFO      Starting builtin webserver: 192.168.0.25:8000
20.08.2017 12:03:43 INFO      Activating Accounts...
20.08.2017 12:03:43 INFO      ACCOUNT AlldebridCom: Adding user `max*******`...
20.08.2017 12:03:43 DEBUG     ACCOUNT AlldebridCom: Reached login timeout for user `max*******`
20.08.2017 12:03:43 INFO      ACCOUNT AlldebridCom: Login user `max*******`...
20.08.2017 12:03:43 DEBUG     ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | redirect=True | cookies=True | get={'action': 'info_user', 'login': 'max*******', 'pw': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
20.08.2017 12:03:45 INFO      ACCOUNT AlldebridCom: Grabbing account info for user `max*******`...
20.08.2017 12:03:45 DEBUG     ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | redirect=True | cookies=True | get={'action': 'info_user', 'login': 'max*******', 'pw': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
20.08.2017 12:03:45 DEBUG     ACCOUNT AlldebridCom: Account info for user `max*******`: {'login': {'timestamp': 1503223423.820419, 'password': '**********', 'valid': True}, 'data': {'premium': True, 'plugin': <Account AlldebridCom>, 'trafficleft': -1, 'maxtraffic': None, 'validuntil': 1512591900.323522, 'login': 'max*******', 'type': 'AlldebridCom', 'options': {'limitdl': ['0']}}}
20.08.2017 12:03:45 INFO      Activating Plugins...
20.08.2017 12:03:45 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
20.08.2017 12:03:45 DEBUG     ADDON ExternalScripts: No script found under folder `pyload_start`
20.08.2017 12:03:46 INFO      ADDON UpdateManager: pyLoad is up to date!
20.08.2017 12:03:46 DEBUG     ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
20.08.2017 12:03:46 DEBUG     ADDON ExtractArchive: Found UnRar 5.21 | Found UnZip 2.7.9 | Found UnTar 2.7.9
20.08.2017 12:03:47 DEBUG     ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'FreeWayMe'), (u'hooks', u'FreeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
20.08.2017 12:03:49 DEBUG     Redirected import module.plugins.hoster.RapidgatorNet -> userplugins.hoster.RapidgatorNet
20.08.2017 12:03:49 DEBUG     Redirected import userplugins.captcha.AdsCaptcha -> module.plugins.captcha.AdsCaptcha
20.08.2017 12:03:49 DEBUG     Redirected import userplugins.captcha.ReCaptcha -> module.plugins.captcha.ReCaptcha
20.08.2017 12:03:49 DEBUG     Redirected import userplugins.captcha.SolveMedia -> module.plugins.captcha.SolveMedia
20.08.2017 12:03:49 DEBUG     Redirected import userplugins.internal.misc -> module.plugins.internal.misc
20.08.2017 12:03:49 DEBUG     Redirected import userplugins.internal.SimpleHoster -> module.plugins.internal.SimpleHoster
20.08.2017 12:03:50 INFO      ADDON XFileSharing: Auto-discover new hosters
20.08.2017 12:03:51 DEBUG     ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|fistfast\.net|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|uptobox\.com|vidplay\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
20.08.2017 12:03:51 INFO      ADDON UpdateManager: All plugins are up to date!
20.08.2017 12:03:51 INFO      ADDON XFileSharing: Auto-discover new crypters
20.08.2017 12:03:52 DEBUG     ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P<DOMAIN>(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
20.08.2017 12:03:52 INFO      pyLoad is up and running
20.08.2017 12:03:54 DEBUG     ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | redirect=True | cookies=True | get={'action': 'get_host'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
20.08.2017 12:03:54 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
20.08.2017 12:03:54 DEBUG     ACCOUNT AlldebridCom: Hoster list for user `max*******`: [u'ausfile.com', u'bigfile.to', u'cloudsix.me', u'datei.to', u'debfile.com', u'depfile.com', u'dipfile.com', u'easybytez.com', u'exoshare.com', u'extmatrix.com', u'faststore.org', u'file4safe.com', u'filebox.com', u'filefactory.com', u'fileflyer.com', u'filesabc.com', u'filesave.me', u'filesflash.com', u'filesflash.net', u'filesmonster.net', u'firedrive.com', u'firedrop.com', u'fourshared.com', u'gigapeta.com', u'junocloud.me', u'katfile.com', u'kingfiles.net', u'load.to', u'mega.co.nz', u'mega.nz', u'megashares.com', u'nowdownload.sx', u'onefichier.com', u'ozofiles.com', u'prefiles.com', u'purevid.com', u'rapidgator.net', u'rapidu.net', u'scribd.com', u'sendspace.com', u'share-online.biz', u'sockshare.com', u'soundcloud.com', u'tezfiles.com', u'turbobit.net', u'tusfiles.net', u'twoshared.com', u'unibytes.com', u'uplea.com', u'uploadcloud.pro', u'uploaded.to', u'uploaded.to', u'uploading.site', u'uptobox.com', u'userscloud.com', u'vidbux.com', u'vidxden.com', u'wipfiles.net', u'wushare.com', u'youtube.com', u'yunfile.com', u'zippyshare.com']
20.08.2017 12:03:54 DEBUG     ACCOUNT AlldebridCom: Overwritten hosters: BigfileTo, DateiTo, EasybytezCom, FilefactoryCom, FiredriveCom, FourSharedCom, GigapetaCom, JunocloudMe, KatfileCom, KingfilesNet, LoadTo, MegaCoNz, MegasharesCom, NowDownloadSx, OneFichierCom, RapidgatorNet, RapiduNet, SendspaceCom, ShareonlineBiz, SockshareCom, SoundcloudCom, TurbobitNet, TusfilesNet, TwoSharedCom, UnibytesCom, UpleaCom, UploadedTo, UptoboxCom, UserscloudCom, YoutubeCom, ZippyshareCom
20.08.2017 12:03:54 DEBUG     ACCOUNT AlldebridCom: New hosters: ausfile.com, cloudsix.me, debfile.com, depfile.com, dipfile.com, exoshare.com, extmatrix.com, faststore.org, file4safe.com, filebox.com, fileflyer.com, filesabc.com, filesave.me, filesflash.com, filesflash.net, filesmonster.net, firedrop.com, mega.nz, ozofiles.com, prefiles.com, purevid.com, scribd.com, tezfiles.com, uploadcloud.pro, uploading.site, vidbux.com, vidxden.com, wipfiles.net, wushare.com, yunfile.com
20.08.2017 12:03:54 DEBUG     ACCOUNT AlldebridCom: Pattern: https?://(?:www\.|s\d+\.)?alldebrid\.com/dl/[\w^_]+|.*(?P<DOMAIN>ausfile\.com|cloudsix\.me|debfile\.com|depfile\.com|dipfile\.com|exoshare\.com|extmatrix\.com|faststore\.org|file4safe\.com|filebox\.com|fileflyer\.com|filesabc\.com|filesave\.me|filesflash\.com|filesflash\.net|filesmonster\.net|firedrop\.com|mega\.nz|ozofiles\.com|prefiles\.com|purevid\.com|scribd\.com|tezfiles\.com|uploadcloud\.pro|uploading\.site|vidbux\.com|vidxden\.com|wipfiles\.net|wushare\.com|yunfile\.com).*

**Comment by GammaC0de** [comment] 2017-08-20 15:29
can you do this:
```
python
import bjoern
```
?

Because this is the point of failure (this is what pyload tries to do in [ServerThread.py#L54](https://github.com/pyload/pyload/blob/stable/module/web/ServerThread.py#L54) but fails).

**Comment by maxbat10** [comment] 2017-08-20 15:42
I can import bjoern into python without any errors, but I still have the same error when I launch pyload...

`Error importing lightweight server: dynamic module does not define init function (initbjoern)
`

**Comment by GammaC0de** [comment] 2017-08-20 17:03
Does it work with `sudo /usr/bin/pyLoadCore -d`?

**Comment by maxbat10** [comment] 2017-08-24 18:38
I get the same log that I have always posted.

**Comment by GammaC0de** [comment] 2017-08-24 19:35
What OS are you running?

**Comment by maxbat10** [comment] 2017-08-24 20:15
Raspbian Jessie Lite

**Comment by GammaC0de** [comment] 2017-09-05 19:51
Well I don't have a Pi and I could not reproduce this on Ubuntu.
If you want to give me access to your server, I can try to fix this.
Otherwise, there's nothing I can do and we should close this issue.

**Comment by GammaC0de** [comment] 2017-09-13 00:14
No response, closing.

**Closed by GammaC0de** 2017-09-13 00:14 UTC
Labels: question
