### ISSUE TITLE
Cant download from uploaded

### ISSUE THREAD

**Issue by mattionline** [pyload/pyload#1965] opened 2015-10-06 10:05 UTC
I also tried to stop pyload, remove accounts and userplugins and restarted it but it doesnt helped.

660	06.10.2015 11:54:54	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname`...
661	06.10.2015 11:54:54	INFO	Download restarted: Archive.part42.rar | Html file
662	06.10.2015 11:54:54	INFO	Download starts: Archive.part42.rar
663	06.10.2015 11:54:54	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
664	06.10.2015 11:54:54	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
665	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: Updating file info...
666	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: File name: Archive.part42.rar
667	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: File size: 104857634 bytes
668	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: File status: starte
669	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: Looking for direct download link...
670	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: Direct download link not found
671	06.10.2015 11:54:55	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
672	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: Filesize: 102400 KiB | Traffic left for user myaccountname: 529290880.0 KiB
673	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: Processing as premium download...
674	06.10.2015 11:54:55	INFO	HOSTER UploadedTo[95]: Downloading file...
675	06.10.2015 11:54:56	INFO	HOSTER UploadedTo[95]: Checking downloaded file...
676	06.10.2015 11:54:56	WARNING	HOSTER UploadedTo[95]: Check result: Html file | Waiting 1 minute and retry
677	06.10.2015 11:54:56	INFO	HOSTER UploadedTo[95]: Waiting 60 seconds...
678	06.10.2015 11:54:56	INFO	HOSTER UploadedTo[95]: Requiring reconnection...
679	06.10.2015 11:54:56	WARNING	HOSTER UploadedTo[95]: Ignore reconnection due logged account
680	06.10.2015 11:54:56	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
681	06.10.2015 11:54:56	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
682	06.10.2015 11:54:56	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
683	06.10.2015 11:54:58	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
684	06.10.2015 11:54:58	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
685	06.10.2015 11:54:58	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
686	06.10.2015 11:55:00	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
687	06.10.2015 11:55:00	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
688	06.10.2015 11:55:00	INFO	ACCOUNT UploadedTo: Grabbing account info for user `myaccountname `...
689	06.10.2015 11:55:03	INFO	Download aborted: Archive.part40.rar
690	06.10.2015 11:55:04	INFO	Download aborted: Archive.part41.rar
691	06.10.2015 11:55:06	INFO	Download aborted: Archive.part42.rar
692	06.10.2015 11:55:44	ERROR	ADDON ClickNLoad: [Errno 98] Address already in use
693	06.10.2015 11:59:44	ERROR	ADDON ClickNLoad: [Errno 98] Address already in use

**Comment by thadrien** [comment] 2015-10-06 10:17
Maybe it's a duplicate of this : https://github.com/pyload/pyload/issues/1961 ?

**Comment by mattionline** [comment] 2015-10-06 10:25
thank you for the reference. i recloned the project and tried out kasperj's fix and it works now.

**Comment by kasperj** [comment] 2015-10-06 10:29
https://github.com/pyload/pyload/pull/1964

**Comment by damien599901** [comment] 2015-10-06 17:31
i m sad 
nothing works anymore
i m a fan of pyload and there... :( => :(

**Comment by thadrien** [comment] 2015-10-06 17:47
5db85c4 commit plus #1964 pull request works for me.

**Comment by realwax** [comment] 2015-10-07 11:18
I can confirm uploaded.to not working anymore again. Multiple account info grabing happnend before. Now it retrying files with a minute delay without success. See logs below... Thank you!

05	07.10.2015 13:13:07	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
606	07.10.2015 13:13:07	INFO	HOSTER UploadedTo[4]: Updating file info...
607	07.10.2015 13:13:07	INFO	HOSTER UploadedTo[4]: File name: test20120tvs.part4.rar
608	07.10.2015 13:13:07	INFO	HOSTER UploadedTo[4]: File size: 335523821 bytes
609	07.10.2015 13:13:07	INFO	HOSTER UploadedTo[4]: File status: starte
610	07.10.2015 13:13:07	INFO	HOSTER UploadedTo[4]: Looking for direct download link...
611	07.10.2015 13:13:08	INFO	HOSTER UploadedTo[4]: Direct download link not found
612	07.10.2015 13:13:08	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
613	07.10.2015 13:13:09	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
614	07.10.2015 13:13:10	INFO	HOSTER UploadedTo[4]: Filesize: 327659 KiB | Traffic left for user user123: 534773760.0 KiB
615	07.10.2015 13:13:10	INFO	HOSTER UploadedTo[4]: Processing as premium download...
616	07.10.2015 13:13:10	INFO	HOSTER UploadedTo[4]: Downloading file...
617	07.10.2015 13:13:10	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
618	07.10.2015 13:13:10	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
619	07.10.2015 13:13:10	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
620	07.10.2015 13:13:10	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
621	07.10.2015 13:13:10	INFO	HOSTER UploadedTo[4]: Checking downloaded file...
622	07.10.2015 13:13:10	WARNING	HOSTER UploadedTo[4]: Check result: Html file | Waiting 1 minute and retry
623	07.10.2015 13:13:10	INFO	HOSTER UploadedTo[4]: Waiting 60 seconds...
624	07.10.2015 13:13:10	INFO	HOSTER UploadedTo[4]: Requiring reconnection...
625	07.10.2015 13:13:10	WARNING	HOSTER UploadedTo[4]: Ignore reconnection due logged account
626	07.10.2015 13:13:12	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
627	07.10.2015 13:13:12	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
628	07.10.2015 13:13:12	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
629	07.10.2015 13:13:12	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
630	07.10.2015 13:13:13	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
631	07.10.2015 13:13:15	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
632	07.10.2015 13:13:15	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...

**Comment by realwax** [comment] 2015-10-08 09:24
Some more logs of today after the update:
126	08.10.2015 11:20:57	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: testdownload.part5.rar (pid:1)
127	08.10.2015 11:20:57	INFO	ADDON UnSkipOnFail: No duplicates found
128	08.10.2015 11:20:58	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
129	08.10.2015 11:20:59	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
130	08.10.2015 11:20:59	INFO	Download starts: penny20720tvs.part1.rar
131	08.10.2015 11:20:59	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
132	08.10.2015 11:20:59	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
133	08.10.2015 11:20:59	INFO	HOSTER UploadedTo[27]: Updating file info...
134	08.10.2015 11:20:59	WARNING	Download failed: penny20720tvs.part1.rar | 'pattern'
135	08.10.2015 11:20:59	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: penny20720tvs.part1.rar (pid:1)
136	08.10.2015 11:20:59	INFO	ADDON UnSkipOnFail: No duplicates found
137	08.10.2015 11:21:01	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
138	08.10.2015 11:21:01	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
139	08.10.2015 11:21:01	INFO	Download starts: penny20720tvs.part2.rar
140	08.10.2015 11:21:01	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
141	08.10.2015 11:21:01	INFO	ACCOUNT UploadedTo: Grabbing account info for user `user123`...
142	08.10.2015 11:21:01	INFO	HOSTER UploadedTo[28]: Updating file info...
143	08.10.2015 11:21:02	WARNING	Download failed: penny20720tvs.part2.rar | 'pattern'
144	08.10.2015 11:21:02	INFO	ADDON UnSkipOnFail: Looking for skipped duplicates of: penny20720tvs.part2.rar (pid:1)

**Comment by mattionline** [comment] 2015-10-08 11:24
@realwax try to reclone the project and do the changes by kasperj. (i dont know if they are already committed) this helped me. today i cant start pyload because of a Plugin.py error but i copied the new two versions manually and it worked. maybe you get this too

**Comment by vuolter** [comment] 2015-10-08 11:30
@mattionline kasperj's PR was merged. Currently working on broken MultiAccount (multi-hoster support) and investigating about strange `Grabbing account` messages...

**Comment by vuolter** [comment] 2015-10-08 13:39
Good news: `Grabbing account` solved. Now optimizing normal behaviour...

**Comment by vuolter** [comment] 2015-10-08 15:06
Retry now, please.

**Closed by vuolter** 2015-10-08 15:06 UTC
Labels: plugin issue

**Comment by realwax** [comment] 2015-10-08 18:30
Confirmed! Uploaded.net/to works again.

Thank you Walter for your great work and effort!

Cheers

Wolfgang


2015-10-08 17:06 GMT+02:00 Walter Purcaro <notifications@github.com>:

**Comment by Poule-Hein** [comment] 2015-10-09 09:05
Thx
