### ISSUE TITLE
Bad server response: 400 Bad Request

### ISSUE THREAD

**Issue by mezzo86** [pyload/pyload#3614] opened 2020-04-30 07:26 UTC
### Describe the problem

I am running pyload (headless) on a RPi with captcha9kw behind a FreshTomato router (3400v3). The 3400v3 sits behind another router. This is working perfectly fine (captchas are getting solved automatically and downloads complete as expected). I am primarily downloading from UL and RG. 

The problem starts when activating the openvpn client on the FreshTomato (3400v3) router. I am using cyberghost (udp). The vpn connection starts fine and I seem to continue to have unlimited connectivity. 

However, as soon as the VPN connection is established pyload stop to work properly. The captcha doesn't get solved and I immediately receive a 400 Bad Request error. This happens with both, UL and RG (both require reCaptcha). And I have also test with NitroFlare and am receiving the same error.

I have tested on my Win10 machine which is hooked up to the same 3400v3. There everything is working fine, even when the VPN is active on the Freshtomato router. Hence I assume it must be a pyload issue.

Did a complete reinstall of the raspberry and pyload. Same behaviour when VPN enabled...

I am not sure if this is related to reCaptcha or something else.
Also I am not sure why this is only occurring when behind VPN - without VPN everything works just fine.

### Debug log

```

16 | 29.04.2020 10:25:34 | INFO | HOSTER RapidgatorNet[398]: Waiting 30 seconds...
-- | -- | -- | --
17 | 29.04.2020 10:26:06 | DEBUG | HOSTER RapidgatorNet[398]: LOAD URL https://rapidgator.net/download/AjaxGetDownloadLink?sid=XXX \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=https://rapidgator.net/file/XXX \| just_header=False
18 | 29.04.2020 10:26:07 | DEBUG | HOSTER RapidgatorNet[398]: https://rapidgator.net/download/AjaxGetDownloadLink?sid=XXX \| {"state":"done"}
19 | 29.04.2020 10:26:07 | DEBUG | HOSTER RapidgatorNet[398]: LOAD URL https://rapidgator.net/download/captcha \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=https://rapidgator.net/file/XXX \| just_header=False
20 | 29.04.2020 10:26:07 | DEBUG | CAPTCHA RapidgatorNet[398]: ReCaptcha \| Key: XXX
21 | 29.04.2020 10:26:07 | DEBUG | CAPTCHA RapidgatorNet[398]: ReCaptcha \| Key: XXX
22 | 29.04.2020 10:26:07 | WARNING | CAPTCHA RapidgatorNet[398]: ReCaptcha \| Secure Token pattern not found
23 | 29.04.2020 10:26:07 | DEBUG | CAPTCHA RapidgatorNet[398]: ReCaptcha \| Detected reCAPTCHA v2
24 | 29.04.2020 10:26:07 | WARNING | CAPTCHA RapidgatorNet[398]: ReCaptcha \| Secure Token pattern not found
25 | 29.04.2020 10:26:07 | DEBUG | HOSTER RapidgatorNet[398]: LOAD URL http://www.google.com/recaptcha/api/fallback?k=XXX \| redirect=True \| cookies=True \| get={} \| req=None \| decode=True \| multipart=False \| post={} \| ref=https://rapidgator.net/file/XXX \| just_header=False
26 | 29.04.2020 10:26:07 | DEBUG | ADDON ExternalScripts: No script found under folder `download_processed`
27 | 29.04.2020 10:26:07 | DEBUG | ADDON ExternalScripts: No script found under folder `package_processed`
28 | 29.04.2020 10:26:07 | WARNING | Download failed: XXX.pdf \| Bad server response: 400 Bad Request
29 | ? | ? | Traceback (most recent call last):
30 | ? | ? | File "/home/pi/pyload/module/PluginThread.py", line 189, in run
31 | ? | ? | pyfile.plugin.preprocessing(self)
32 | ? | ? | File "/home/pi/pyload/module/plugins/internal/Base.py", line 291, in preprocessing
33 | ? | ? | return self._process(*args, **kwargs)
34 | ? | ? | File "/home/pi/pyload/module/plugins/internal/Hoster.py", line 118, in _process
35 | ? | ? | self.process(self.pyfile)
36 | ? | ? | File "/home/pi/pyload/module/plugins/internal/SimpleHoster.py", line 282, in process
37 | ? | ? | self.handle_free(pyfile)
38 | ? | ? | File "/home/pi/pyload/module/plugins/hoster/RapidgatorNet.py", line 150, in handle_free
39 | ? | ? | response, challenge = captcha.challenge()
40 | ? | ? | File "/home/pi/pyload/module/plugins/captcha/ReCaptcha.py", line 154, in challenge
41 | ? | ? | secure_token=secure_token)
42 | ? | ? | File "/home/pi/pyload/module/plugins/captcha/ReCaptcha.py", line 149, in challenge
43 | ? | ? | return getattr(self, "_challenge_v%s" % version)(key, secure_token=secure_token)
44 | ? | ? | File "/home/pi/pyload/module/plugins/captcha/ReCaptcha.py", line 281, in _challenge_v2
45 | ? | ? | html = self.pyfile.plugin.load(fallback_url, ref=self.pyfile.url)
46 | ? | ? | File "/home/pi/pyload/module/plugins/internal/Base.py", line 487, in load
47 | ? | ? | return Plugin.load(self, *args, **kwargs)
48 | ? | ? | File "/home/pi/pyload/module/plugins/internal/Plugin.py", line 248, in load
49 | ? | ? | decode is True)
50 | ? | ? | File "/home/pi/pyload/module/network/Browser.py", line 98, in load
51 | ? | ? | return self.http.load(*args, **kwargs)
52 | ? | ? | File "/home/pi/pyload/module/network/HTTPRequest.py", line 264, in load
53 | ? | ? | self.code = self.verifyHeader()
54 | ? | ? | File "/home/pi/pyload/module/network/HTTPRequest.py", line 280, in verifyHeader
55 | ? | ? | raise BadHeader(code, self.header, self.getResponse())
56 | ? | ? | BadHeader: Bad server response: 400 Bad Request
57 | 29.04.2020 10:26:08 | INFO | Debug Report written to debug_RapidgatorNet_29-04-2020_10-26-07.zip
```

### Additional references

```
Python: | 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
-- | --
OS: | posix linux2 Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l
pyLoad version: | 0.4.20
Installation Folder: | /home/pi/pyload
Config Folder: | /home/pi/.pyload
Download Folder: | /home/pi/.pyload/Downloads
Free Space: | 57.66 GiB
Language: | en
Webinterface Port: | 8000
Remote Interface Port: | 7227
```

Happy to provide more information as needed. Just let me know.

Thanks for all your great work!

**Comment by GammaC0de** [comment] 2020-04-30 23:27
Please attach debug_RapidgatorNet_29-04-2020_10-26-07.zip

**Comment by mezzo86** [comment] 2020-05-01 07:58
@GammaC0de Sure, here you go! Thanks for you help - I appreciate it!

[debug_RapidgatorNet_29-04-2020_10-26-07.zip](https://github.com/pyload/pyload/files/4562955/debug_RapidgatorNet_29-04-2020_10-26-07.zip)

**Comment by GammaC0de** [comment] 2020-05-01 23:52
Duplicate of #3535

**Closed** 2020-05-01 23:54 UTC
Labels: bug
