### ISSUE TITLE
DDL.to Plugin dead?  v0.4.20

### ISSUE THREAD

**Issue by inDane** [pyload/pyload#3915] opened 2021-03-21 00:17 UTC
Pyload cannot use the DDL.To plugin anymore; it was working some time ago, I don't know since when it stopped working.

```

20.03.2021 01:51:38 | INFO | Starting threaded webserver: 0.0.0.0:8000
-- | -- | --
478 | 20.03.2021 01:51:38 | INFO | pyLoad is up and running
479 | 20.03.2021 01:51:38 | INFO | ADDON UpdateManager: pyLoad is up to date!
480 | 20.03.2021 01:51:38 | INFO | ADDON UpdateManager: All plugins are up to date!
481 | 20.03.2021 01:51:44 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
482 | 20.03.2021 07:51:41 | INFO | ADDON UpdateManager: pyLoad is up to date!
483 | 20.03.2021 07:51:41 | INFO | ADDON UpdateManager: All plugins are up to date!
484 | 20.03.2021 13:51:42 | INFO | ADDON UpdateManager: pyLoad is up to date!
485 | 20.03.2021 13:51:42 | INFO | ADDON UpdateManager: All plugins are up to date!
486 | 20.03.2021 19:51:43 | INFO | ADDON UpdateManager: pyLoad is up to date!
487 | 20.03.2021 19:51:43 | INFO | ADDON UpdateManager: All plugins are up to date!
488 | 21.03.2021 01:12:20 | INFO | restarting pyLoad
489 | 21.03.2021 01:12:20 | INFO | shutting down...
490 | 21.03.2021 01:12:20 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
491 | 21.03.2021 01:12:20 | INFO | ADDON ClickNLoad: Shutting down proxy...
492 | 21.03.2021 01:12:20 | INFO | Starting pyLoad 0.4.20
493 | 21.03.2021 01:12:20 | INFO | Using home directory: /root/.pyload
494 | 21.03.2021 01:12:20 | INFO | Activated plugins: ClickNLoad, EventMapper, ExternalScripts, TORRENT, UnSkipOnFail, UpdateManager, UserAgentSwitcher
495 | 21.03.2021 01:12:20 | INFO | Deactivate plugins: AntiStandby, AntiVirus, AppriseNotify,  BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha,  DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders,  ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter,  LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet,  PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify,  XFileSharing, XMPP
496 | 21.03.2021 01:12:20 | INFO | Downloadtime: True
497 | 21.03.2021 01:12:20 | INFO | Starting ThriftBackend: 0.0.0.0:7227
498 | 21.03.2021 01:12:20 | INFO | Free space: 1.44 TiB
499 | 21.03.2021 01:12:20 | INFO | Activating Accounts...
500 | 21.03.2021 01:12:20 | ERROR | Bad or missing plugin: ACCOUNT DdlTo
501 | 21.03.2021 01:12:20 | INFO | Activating Plugins...
502 | 21.03.2021 01:12:20 | WARNING | ADDON TORRENT: torrents / magnets are not associated with any plugin
503 | 21.03.2021 01:12:20 | INFO | Starting threaded webserver: 0.0.0.0:8000
504 | 21.03.2021 01:12:20 | INFO | pyLoad is up and running
505 | 21.03.2021 01:12:20 | INFO | ADDON UpdateManager: pyLoad is up to date!
506 | 21.03.2021 01:12:20 | INFO | ADDON UpdateManager: All plugins are up to date!
507 | 21.03.2021 01:12:26 | INFO | ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
508 | 21.03.2021 01:12:28 | ERROR | Bad or missing plugin: ACCOUNT DdlTo
509 | 21.03.2021 01:12:28 | ERROR | Bad or missing plugin: ACCOUNT DdlTo
```

From the console I get

```
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 112, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/usr/share/pyload/module/Api.py", line 895, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/usr/share/pyload/module/utils.py", line 169, in new
    return func(*args)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 153, in updateAccount
    updated = p.updateAccounts(user, password, options)
AttributeError: 'NoneType' object has no attribute 'updateAccounts'
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 112, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/usr/share/pyload/module/Api.py", line 895, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/usr/share/pyload/module/utils.py", line 169, in new
    return func(*args)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 153, in updateAccount
    updated = p.updateAccounts(user, password, options)
AttributeError: 'NoneType' object has no attribute 'updateAccounts'
```

**Comment by GammaC0de** [comment] 2021-03-21 00:21
Duplicate of #3905.

**Closed** 2021-03-21 20:56 UTC
Labels: bug, duplicate, pyLoad Stable
