### ISSUE TITLE
new errors

### ISSUE THREAD

**Issue by damien599901** [pyload/pyload#1977] opened 2015-10-08 09:34 UTC
An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/utils.py", line 165, in new
return func(*args)
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/volume1/.@plugins/AppCentral/pyload/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by Poule-Hein** [comment] 2015-10-08 14:13
Same problem for me !

An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/usr/share/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/usr/share/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/usr/share/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/usr/share/pyload/module/utils.py", line 165, in new
return func(*args)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

**Comment by joberreiter** [comment] 2015-10-08 14:59
Duplicate of #1907 ?

**Comment by vuolter** [comment] 2015-10-08 15:05
Really no idea, try reinstalling.
This week-end, I hope to release the 0.4.9-hotfix and shutdown this mess for a while.

**Comment by godfuture** [comment] 2015-10-08 22:29
Just did updates and now the following error appears when clicking settings in webinterface:
```
An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/usr/share/pyload/module/web/utils.py", line 113, in _view
return func(*args, **kwargs)
File "/usr/share/pyload/module/web/pyload_app.py", line 256, in config
accs = PYLOAD.getAccounts(False)
File "/usr/share/pyload/module/Api.py", line 875, in getAccounts
accs = self.core.accountManager.getAccountInfos(False, refresh)
File "/usr/share/pyload/module/utils.py", line 165, in new
return func(*args)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
p = self.getAccountPlugin(p)
File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
```

**Comment by Poule-Hein** [comment] 2015-10-09 09:05
#1965

**Comment by godfuture** [comment] 2015-10-15 21:58
Any news?

**Comment by vuolter** [comment] 2015-10-15 23:11
Working on a fix...

**Comment by godfuture** [comment] 2015-10-24 11:25
Did this serval times:
http://forum.pyload.org/viewtopic.php?f=7&t=4335

Now readded all packages in queue, and that helped. So delete all added packages, do this http://forum.pyload.org/viewtopic.php?f=7&t=4335 and then add all again. Now it works for me again.

cheers!

**Closed** 2015-10-24 23:11 UTC
Labels: plugin issue

**Comment by Pandiora** [comment] 2017-11-27 23:06
@godfuture Nice redirection-chain. Remove those links from your comment please.
