### ISSUE TITLE
ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by scrimpy** [pyload/pyload#1639] opened 2015-07-31 16:52 UTC
31.07.2015 18:49:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
818	31.07.2015 18:49:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
817	31.07.2015 18:48:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
816	31.07.2015 18:48:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
815	31.07.2015 18:47:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
814	31.07.2015 18:47:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
813	31.07.2015 18:46:56	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
812	31.07.2015 18:46:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
811	31.07.2015 18:46:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
810	31.07.2015 18:45:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
809	31.07.2015 18:45:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
808	31.07.2015 18:44:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
807	31.07.2015 18:44:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
806	31.07.2015 18:43:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
805	31.07.2015 18:43:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
804	31.07.2015 18:42:56	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
803	31.07.2015 18:42:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
802	31.07.2015 18:42:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
801	31.07.2015 18:41:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
800	31.07.2015 18:41:01	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
799	31.07.2015 18:40:53	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
798	31.07.2015 18:40:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
797	31.07.2015 18:39:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
796	31.07.2015 18:39:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
795	31.07.2015 18:38:56	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
794	31.07.2015 18:38:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
793	31.07.2015 18:38:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
792	31.07.2015 18:37:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
791	31.07.2015 18:37:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
790	31.07.2015 18:36:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
789	31.07.2015 18:36:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
788	31.07.2015 18:35:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
787	31.07.2015 18:35:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
786	31.07.2015 18:34:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
785	31.07.2015 18:34:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
784	31.07.2015 18:34:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
783	31.07.2015 18:33:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
782	31.07.2015 18:33:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
781	31.07.2015 18:32:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
780	31.07.2015 18:32:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
779	31.07.2015 18:31:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
778	31.07.2015 18:31:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
777	31.07.2015 18:30:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
776	31.07.2015 18:30:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
775	31.07.2015 18:30:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
774	31.07.2015 18:29:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
773	31.07.2015 18:29:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
772	31.07.2015 18:28:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
771	31.07.2015 18:28:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
770	31.07.2015 18:27:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
769	31.07.2015 18:27:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
768	31.07.2015 18:26:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
767	31.07.2015 18:26:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
766	31.07.2015 18:26:00	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
765	31.07.2015 18:25:52	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
764	31.07.2015 18:24:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
763	31.07.2015 18:24:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
762	31.07.2015 18:23:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
761	31.07.2015 18:23:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
760	31.07.2015 18:22:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
759	31.07.2015 18:22:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
758	31.07.2015 18:22:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
757	31.07.2015 18:21:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
756	31.07.2015 18:21:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
755	31.07.2015 18:20:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
754	31.07.2015 18:20:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
753	31.07.2015 18:19:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
752	31.07.2015 18:19:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
751	31.07.2015 18:18:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
750	31.07.2015 18:18:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
749	31.07.2015 18:18:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
748	31.07.2015 18:17:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
747	31.07.2015 18:17:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
746	31.07.2015 18:16:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
745	31.07.2015 18:16:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
744	31.07.2015 18:15:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
743	31.07.2015 18:15:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
742	31.07.2015 18:14:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
741	31.07.2015 18:14:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
740	31.07.2015 18:14:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
739	31.07.2015 18:13:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
738	31.07.2015 18:13:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
737	31.07.2015 18:12:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
736	31.07.2015 18:12:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
735	31.07.2015 18:11:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
734	31.07.2015 18:11:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
733	31.07.2015 18:10:59	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
732	31.07.2015 18:10:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
731	31.07.2015 18:10:51	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
730	31.07.2015 18:09:58	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
729	31.07.2015 18:09:50	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
728	31.07.2015 18:08:58	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
727	31.07.2015 18:08:50	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
726	31.07.2015 18:07:58	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
725	31.07.2015 18:07:50	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
724	31.07.2015 18:06:58	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
723	31.07.2015 18:06:55	ERROR	HOOK ClickAndLoad: [Errno 98] Address already in use
722	31.07.2015 18:06:50	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
721	31.07.2015 18:05:58	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded
720	31.07.2015 18:05:50	ERROR	HOOK LinkdecrypterCom: Error executing addon: maximum recursion depth exceeded

**Comment by wweich** [comment] 2015-07-31 16:55
Duplicate of #1636 and #1633 .

**Closed** 2015-08-01 00:39 UTC
Labels: duplicate, plugin issue
