### ISSUE TITLE
Zippyshare: 'exceptions.AttributeError' object has no attribute 'strip'

### ISSUE THREAD

**Issue by analca3** [pyload/pyload#1484] opened 2015-06-11 16:49 UTC
Hi! I'm trying to download some files from zippyshare and I get this error in the most of files (I added 86 and download only 2).

    'exceptions.AttributeError' object has no attribute 'strip'

What can I do for helping? In .pyload/Logs/log.txt there isn't any more info :(.

EDIT: OK, I found debug mode :).

This is a debug report for a single file.

```
11.06.2015 19:26:02 INFO      Added package TestingZippy containing 1 links
11.06.2015 19:26:02 DEBUG     Run Info Fetching for ZippyshareCom
11.06.2015 19:26:03 DEBUG     Finished Info Fetching for ZippyshareCom
11.06.2015 19:26:03 INFO      Download starts: juruno-1080-xevious.part16.rar
11.06.2015 19:26:03 DEBUG     ZippyshareCom: Update file info...
11.06.2015 19:26:03 DEBUG     ZippyshareCom: Previous file info: {}
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Current file info: {'status': 2, 'url': u'http://www14.zippyshare.com/v/45144612/file.html', 'size': 199994900.48, 'name': u'juruno-1080-xevious.part16.rar', 'pattern': {'S': u'190.73', 'U': u'MB', 'KEY': u'45144612', 'N': u'juruno-1080-xevious.part16.rar'}}
11.06.2015 19:26:04 DEBUG     ZippyshareCom: File name: juruno-1080-xevious.part16.rar | File size: 199994900
11.06.2015 19:26:04 DEBUG     ZippyshareCom: File status: online
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Update file info...
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Previous file info: {'status': 2, 'url': u'http://www14.zippyshare.com/v/45144612/file.html', 'size': 199994900.48, 'name': u'juruno-1080-xevious.part16.rar', 'pattern': {'S': u'190.73', 'U': u'MB', 'KEY': u'45144612', 'N': u'juruno-1080-xevious.part16.rar'}}
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Current file info: {'status': 2, 'name': u'juruno-1080-xevious.part16.rar', 'url': u'http://www14.zippyshare.com/v/45144612/file.html', 'pattern': {'S': u'190.73', 'U': u'MB', 'KEY': u'45144612', 'N': u'juruno-1080-xevious.part16.rar'}, 'size': 199994900.48}
11.06.2015 19:26:04 DEBUG     ZippyshareCom: File name: juruno-1080-xevious.part16.rar | File size: 199994900
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Update file info...
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Previous file info: {'status': 2, 'name': u'juruno-1080-xevious.part16.rar', 'url': u'http://www14.zippyshare.com/v/45144612/file.html', 'pattern': {'S': u'190.73', 'U': u'MB', 'KEY': u'45144612', 'N': u'juruno-1080-xevious.part16.rar'}, 'size': 199994900.48}
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Current file info: {'status': 2, 'name': u'juruno-1080-xevious.part16.rar', 'url': u'http://www14.zippyshare.com/v/45144612/file.html', 'pattern': {'S': u'190.73', 'U': u'MB', 'KEY': u'45144612', 'N': u'juruno-1080-xevious.part16.rar'}, 'size': 199994900.48}
11.06.2015 19:26:04 DEBUG     ZippyshareCom: File name: juruno-1080-xevious.part16.rar | File size: 199994900
11.06.2015 19:26:04 DEBUG     ZippyshareCom: File status: online
11.06.2015 19:26:04 DEBUG     ZippyshareCom: Handled as free download
11.06.2015 19:26:04 DEBUG     ReCaptcha: Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
11.06.2015 19:26:04 DEBUG     ReCaptcha: Key: 6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
11.06.2015 19:26:04 DEBUG     ReCaptcha: API version: r20150604090638
11.06.2015 19:26:04 DEBUG     ReCaptcha: API language: es
11.06.2015 19:26:06 DEBUG     ReCaptcha: API jsh-string: m;/_/scs/apps-static/_/js/k=oz.gapi.es.J0TFVZ-A1KE.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCOQ2zIhjTjZV_uOPjCEajXTZfCkSw
11.06.2015 19:26:06 DEBUG     ReCaptcha: Time: 1434043566214
11.06.2015 19:26:06 DEBUG     ReCaptcha: Rpc-token: 16455549
11.06.2015 19:26:07 WARNING   Download failed: juruno-1080-xevious.part16.rar | 'exceptions.AttributeError' object has no attribute 'strip'
11.06.2015 19:26:07 INFO      Debug Report written to debug_ZippyshareCom_11-06-2015_19-26-07.zip
11.06.2015 19:26:07 INFO      UnSkipOnFail: Looking for skipped duplicates of: juruno-1080-xevious.part16.rar (pid:4)
11.06.2015 19:26:07 INFO      UnSkipOnFail: No duplicates found
11.06.2015 19:26:08 DEBUG     All downloads processed
```

Regards!

**Comment by sebdelsol** [comment] 2015-06-11 17:43
captcha is not correctly detected.

**Comment by GammaC0de** [comment] 2015-06-11 20:58
this is a duplicate of #1434 (recaptcha v2)

**Comment by jojo141185** [comment] 2015-06-13 16:00
I think GammaC0de is right! This bug seems to be associated with No Captcha ReCAPTCHA v2.
![haiiaief](https://cloud.githubusercontent.com/assets/6240522/8144982/bf7c48b0-11f5-11e5-858d-e41ecb9606c3.png)
![bibjfaci](https://cloud.githubusercontent.com/assets/6240522/8144983/c59e2024-11f5-11e5-94da-4c699d30d50a.png)
Is it possible to bypass this captcha with pyload?

**Comment by sebdelsol** [comment] 2015-06-13 18:10
In this document.location point to the actual file url- I've checked.
Yet it's not enough to trigger the download. I don't know why.

here's what I've tried
```python
    def handleFree(self, pyfile):
        location = re.search(self.LINK_PREMIUM_PATTERN, self.html)
        if location:
            self.link = location.groups()[0]
        else:
            self.link = self.get_link()
```

**Comment by GammaC0de** [comment] 2015-06-13 23:26
On `ReCaptcha.py's`  `_challenge_v2` function, the request of `https://www.google.com/recaptcha/api2/anchor` is missing a `co` parameter, maybe this causes the problem
```
k	6LcF3P8SAAAAALMK-i8iU5ZVQOoKNWYMEUBto-uq
co	aHR0cDovL3d3dzE0LnppcHB5c2hhcmUuY29t
hl	en
v	r20150604090638
theme	white
size	normal
usegapi	1
jsh	m;/_/scs/apps-static/_/js/k=oz.gapi.iw.51fqvpdmSJA.O/m=__features__/am=AQ/rt=j/d=1/t=zcms/rs=AGLTcCOpZWzzYCFzkoCGGwDGKwPxP2ubtA
```

**Comment by zapp-brannigan** [comment] 2015-06-14 07:01
@jojo141185  Please, post the link to that zippyshare file with captcha, so i can check RecaptchaV2
I've never seen a captcha on zippyshare...

**Comment by GammaC0de** [comment] 2015-06-14 07:12
@zapp-brannigan 
http://www14.zippyshare.com/v/45144612/file.html is the link, the problem is that the captcha is randomly appears.
from my little investigation, the load of `https://www.google.com/recaptcha/api2/anchor` did not contain `recaptcha-token` in it while it did with a browser.
the get arguments with a browser included a `co` parameter while `ReCaptcha.py` does not send one
notice the message `ERROR: Required field must not be blank` in the html, maybe this is a hint.

result html of `https://www.google.com/recaptcha/api2/anchor`:
```html
<!DOCTYPE HTML>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style type="text/css">
        @font-face {
            font-family: 'Roboto';
            font-style: normal;
            font-weight: 400;
            src: local('Roboto Regular'), local('Roboto-Regular'), url(//fonts.gstatic.com/s/roboto/v15/CWB0XYA8bzo0kSThX0UTuA.woff2) format('woff2'), url(//fonts.gstatic.com/s/roboto/v15/2UX7WLTfW3W8TclTUvlFyQ.woff) format('woff');
        }
        
        @font-face {
            font-family: 'Roboto';
            font-style: normal;
            font-weight: 500;
            src: local('Roboto Medium'), local('Roboto-Medium'), url(//fonts.gstatic.com/s/roboto/v15/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2) format('woff2'), url(//fonts.gstatic.com/s/roboto/v15/RxZJdnzeo3R5zSexge8UUT8E0i7KZn-EPnyo3HZu7kw.woff) format('woff');
        }
    </style>
    <link rel="stylesheet" type="text/css" href="https://www.gstatic.com/recaptcha/api2/r20150604090638/styles__rtl.css">
</head>

<body>
    <div class="rc-anchor rc-anchor-default">
        <div class="rc-anchor-content">
            <div class="rc-anchor-item">
                <div class="rc-anchor-center-container">
                    <div class="rc-anchor-error rc-anchor-center-item"><span>ERROR: Required field must not be blank</span></div>
                </div>
            </div>
        </div>
        <div class="rc-anchor-item">
            <div class="rc-anchor-logo"></div>
        </div>
    </div>
</body>

</html>
```

**Comment by GammaC0de** [comment] 2015-06-14 07:15
P.S. as @jojo141185 mentiond, it is a No Captcha ReCAPTCHA v2, i.e. you only had the press "I'm not a robot' check-box and the the download button was showing, no challenge was presented.

**Comment by zapp-brannigan** [comment] 2015-06-14 07:46
On the demo-page i receive a "choose all pictures with beer" captacha which is not solvable by now :(
Also, i've never seen that "no captacha just click the button" one. Sorry, i can't help :(

**Comment by jojo141185** [comment] 2015-06-14 12:26
As I know, thereCAPTCHA v2 is not static. It uses an advanced risk analysis engine and adaptive CAPTCHAs to keep automated software from engaging in abusive activities on your site.
As I know, it considers many factors like:
- behavior prior to clicking, how your cursor moved on its way to the check (organic path/acceleration)
- which part of the checkbox was clicked (random places, or dead on center every time)
- browser fingerprint like Google cookies & contents, click location history tied to your fingerprint or account if it detects one etc.
Only if its still in doubt it will asked you questions with images or text!

You can see it on ZippyShare 
(for example, I used this link: http://www58.zippyshare.com/v/MuY3lBPj/file.html)

Same URL, WITH Captcha:
![haiiaief](https://cloud.githubusercontent.com/assets/6240522/8148453/f9b09eec-129e-11e5-81d1-e57e6ce805fc.png)
Source: http://pastebin.com/mPmkuwLj

Same URL, WITHOUT Captcha:
![zippy](https://cloud.githubusercontent.com/assets/6240522/8148465/5071fdf2-129f-11e5-8d0e-014cf7537567.PNG)
Source: http://pastebin.com/qaMjnbi5

You can see the diffrence in Source:
![zippy_sourcediff](https://cloud.githubusercontent.com/assets/6240522/8148513/4703dda6-12a1-11e5-8515-3ce8c27ad865.PNG)

**Comment by sebdelsol** [comment] 2015-06-14 13:31
as you can see `document.loaction = '...'` contains the actual link to the file. Yet the download is not triggered. I've checked the cookies. There's nothing added after the cpatcha resolution... So what have I missed ?

**Comment by nomad71** [comment] 2015-06-15 10:10
just a side note: this annoying with zippyshare but just temporary. If you can wait, retry in a day or two and the captcha will be gone ... at least it did disappear in the past.

**Comment by jojo141185** [comment] 2015-06-20 12:22
@nomad71 From my investigations concerning this issue, I can confirm that the FileSize is relevant!

**Comment by sraedler** [comment] 2016-02-14 21:40
zippyshare is working...

could be closed

**Closed** 2016-02-14 21:52 UTC
Labels: API request, plugin issue
