### ISSUE TITLE
Zippyshare download file.html

### ISSUE THREAD

**Issue by Mister-XY** [pyload/pyload#1311] opened 2015-04-03 21:16 UTC
Hello, i found a small bug if any download via zippyshare. In some downloads, you get only a file.html file instead of the realy filename.
Here is an example to test
3616	03.04.2015 23:13:26	DEBUG	ReCaptcha: Key not found
3615	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Handled as free download
3614	03.04.2015 23:13:26	DEBUG	ZippyshareCom: File status: online
3613	03.04.2015 23:13:26	DEBUG	ZippyshareCom: File name: tvp-starwarsrebels-s01e01e02-720p.part1.rar | File size: 155189248 byte
3612	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar', 'url': u'http://www56.zippyshare.com/v/JzrRg8mW/file.html', 'pattern': {'S': u'148', 'U': u'MB', 'KEY': u'JzrRg8mW', 'N': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar'}, 'size': 155189248.0}
3611	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'name': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar', 'url': u'http://www56.zippyshare.com/v/JzrRg8mW/file.html', 'pattern': {'S': u'148', 'U': u'MB', 'KEY': u'JzrRg8mW', 'N': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar'}, 'size': 155189248.0}
3610	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Update file info...
3609	03.04.2015 23:13:26	DEBUG	ZippyshareCom: File name: tvp-starwarsrebels-s01e01e02-720p.part1.rar | File size: 155189248 byte
3608	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar', 'url': u'http://www56.zippyshare.com/v/JzrRg8mW/file.html', 'pattern': {'S': u'148', 'U': u'MB', 'KEY': u'JzrRg8mW', 'N': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar'}, 'size': 155189248.0}
3607	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'url': u'http://www56.zippyshare.com/v/JzrRg8mW/file.html', 'size': 155189248.0, 'name': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar', 'pattern': {'S': u'148', 'U': u'MB', 'KEY': u'JzrRg8mW', 'N': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar'}}
3606	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Update file info...
3605	03.04.2015 23:13:26	DEBUG	ZippyshareCom: File status: online
3604	03.04.2015 23:13:26	DEBUG	ZippyshareCom: File name: tvp-starwarsrebels-s01e01e02-720p.part1.rar | File size: 155189248 byte
3603	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'url': u'http://www56.zippyshare.com/v/JzrRg8mW/file.html', 'size': 155189248.0, 'name': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar', 'pattern': {'S': u'148', 'U': u'MB', 'KEY': u'JzrRg8mW', 'N': u'tvp-starwarsrebels-s01e01e02-720p.part1.rar'}}
3602	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Previous file info: {}
3601	03.04.2015 23:13:26	DEBUG	ZippyshareCom: Update file info...
3600	03.04.2015 23:13:26	INFO	Download starts: tvp-starwarsrebels-s01e01e02-720p.part1.rar
3599	03.04.2015 23:13:25	DEBUG	ReCaptcha: Key not found
3598	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Handled as free download
3597	03.04.2015 23:13:25	DEBUG	ZippyshareCom: File status: online
3596	03.04.2015 23:13:25	DEBUG	ZippyshareCom: File name: file.html | File size: 157286400 byte
3595	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'file.html', 'url': u'http://www27.zippyshare.com/v/2AEwGYlh/file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'2AEwGYlh'}, 'size': 157286400.0}
3594	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'name': u'file.html', 'url': u'http://www27.zippyshare.com/v/2AEwGYlh/file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'2AEwGYlh'}, 'size': 157286400.0}
3593	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Update file info...
3592	03.04.2015 23:13:25	DEBUG	ZippyshareCom: File name: file.html | File size: 157286400 byte
3591	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'name': u'file.html', 'url': u'http://www27.zippyshare.com/v/2AEwGYlh/file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'2AEwGYlh'}, 'size': 157286400.0}
3590	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Previous file info: {'status': 2, 'url': u'http://www27.zippyshare.com/v/2AEwGYlh/file.html', 'size': 157286400.0, 'name': u'file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'2AEwGYlh'}}
3589	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Update file info...
3588	03.04.2015 23:13:25	DEBUG	ZippyshareCom: File status: online
3587	03.04.2015 23:13:25	DEBUG	ZippyshareCom: File name: file.html | File size: 157286400 byte
3586	03.04.2015 23:13:25	DEBUG	ZippyshareCom: Current file info: {'status': 2, 'url': u'http://www27.zippyshare.com/v/2AEwGYlh/file.html', 'size': 157286400.0, 'name': u'file.html', 'pattern': {'S': u'150', 'U': u'MB', 'KEY': u'2AEwGYlh'}}
3585	03.04.2015 23:13:24	DEBUG	ZippyshareCom: Previous file info: {}
3584	03.04.2015 23:13:24	DEBUG	ZippyshareCom: Update file info...
3583	03.04.2015 23:13:24	INFO	Download starts: file.html
3582	03.04.2015 23:13:24	DEBUG	Redirected import module.plugins.internal.CaptchaService -> userplugins.internal.CaptchaService
3581	03.04.2015 23:13:24	DEBUG	Redirected import module.plugins.hoster.ZippyshareCom -> userplugins.hoster.ZippyshareCom

**Comment by sebdelsol** [comment] 2015-04-04 10:59
what OS and JS engine are you using ?

**Comment by Mister-XY** [comment] 2015-04-04 13:42
My OS is Ubuntu and the JS engine is rhino 1.7

**Comment by sebdelsol** [comment] 2015-04-04 15:53
Thanks. I've tried to dl your links, and it works for me. I don't have rhino though.
Could you please try again with this version of [Zippysharecom.py](http://www51.zippyshare.com/v/GULUG33z/file.html) ?
It'll log the js scripts that have been found on the page and evaluate `math.pow()` that seems to fail with some js engine. 
Please swith debug on and post the log of a failed download. You should see quite a lot of `DEBUG >>>` lines in the log. 
This way, we'll see if it's a duplicate of bug https://github.com/pyload/pyload/issues/1211

**Comment by Mister-XY** [comment] 2015-04-04 17:18
look like this?
url found: "/d/OSy0kna9/357914/d-beemovie-1080p.part09.rar"
GVAR["dlbutton_href"]
} catch(err){}
}
GVAR['fimage'+"_href"] = "/i/OSy0kna9/"+(Math.pow(a, 3)+b)+"/d-beemovie-1080p.part09.rar";
if (GVAR['fimage'+"_None"]) {
GVAR['dlbutton'+"_href"] = "/d/OSy0kna9/"+(Math.pow(a, 3)+b)+"/d-beemovie-1080p.part09.rar";
var b = GVAR['dlbutton'+"_omg"].length;
GVAR['dlbutton'+"_omg"] = "asdasd".substr(0, 3);
var a = 71;
try{
GVAR['dlbutton'+"_href"] = "#";
GVAR['dlbutton'+"_omg"] = null;
GVAR['fimage'+"_href"] = null;
GVAR['fimage'+"_None"] = null;
var GVAR = {}
Script Found----
Test Math.pow: "4"
JSE is js

**Comment by sebdelsol** [comment] 2015-04-04 17:22
yes. I guess those logs come from succesful dowloads.

**Comment by Mister-XY** [comment] 2015-04-04 17:25
but the file is called "file.html" instead xxx.rar

**Comment by sebdelsol** [comment] 2015-04-04 17:29
oh. is the file the real one ? I mean is it only a issue with the file name ?

**Comment by Mister-XY** [comment] 2015-04-04 17:32
This is an example 
http://www10.zippyshare.com/v/LkRIe0cH/file.html

**Comment by sebdelsol** [comment] 2015-04-04 17:33
ok, the url is fine, as is the file. Yet the file name is wrong, because it's encrypted as an image !
I'll see what I can do. thanks.

**Comment by Mister-XY** [comment] 2015-04-04 17:34
OK cool

**Comment by sebdelsol** [comment] 2015-04-04 18:01
@vuolter, I don't really now where to do that : 
```python
        if self.info['name'] == 'file.html':
            self.info['name'] = urllib.unquote(self.link.split('/')[-1])
```

**Comment by Mister-XY** [comment] 2015-04-04 18:05
and now?

**Comment by sebdelsol** [comment] 2015-04-04 18:24
I've to read quite a lot of code... please be patient

**Comment by sebdelsol** [comment] 2015-04-04 19:16
See https://github.com/pyload/pyload/pull/1314

**Comment by Mister-XY** [comment] 2015-04-04 21:07
Is it not easyer to get the file insteat of the filename?

**Comment by GammaC0de** [comment] 2015-04-04 21:51
Hi,
This patch should solve the issue.
```patch
--- ZippyshareCom.py.bad        2015-03-18 23:13:07.000000000 +0200
+++ ZippyshareCom.py    2015-04-05 00:47:11.357482825 +0300
@@ -23,7 +23,7 @@

     COOKIES = [("zippyshare.com", "ziplocale", "en")]

-    NAME_PATTERN    = r'("/|<title>Zippyshare.com - )(?P<N>[^/]+?)("\);|</title>)'
+    NAME_PATTERN    = r'("/|<title>Zippyshare.com - )(?P<N>[^/]+?)("\)?;|</title>)'
     SIZE_PATTERN    = r'>Size:.+?">(?P<S>[\d.,]+) (?P<U>[\w^_]+)'
     OFFLINE_PATTERN = r'does not exist (anymore )?on this server<'


```

**Comment by Mister-XY** [comment] 2015-04-04 22:46
yes, this patch solve the also the error.

**Comment by sebdelsol** [comment] 2015-04-04 23:45
oh ok, I thought that NAME_PATTERN was for searching in the html.

**Comment by GammaC0de** [comment] 2015-04-05 05:45
@sebdelsol you are right about NAME_PATTERN searching in the html only, but where do you think `self.link` comes from? It comes from the html...

**Comment by sebdelsol** [comment] 2015-04-05 13:02
That I know :) I've written this plugin's `get_link()`. 

Thanks to your clarification, I see that in this case `NAME_PATTERN` match the javascript line in the html where ```document.getElementById('dlbutton').href``` is evaluated. 

So it works for now. Yet this solution is not robust, since any subtle change in the javascript could bring false or no positive. 
Indeed, Zippyshare changes its javascript a lot : it splits its scripts, rewrite or reorder them. I even saw some scripts meant to fail to obfuscate everything...

That's why I think that it's way more safe to extract the file name from the _found_ url :https://github.com/sebdelsol/pyload/commit/40add66d77e0eeb1f0f709ad07ecba553123bba1

**Comment by sebdelsol** [comment] 2015-04-05 14:35
```
--- a/module/plugins/hoster/ZippyshareCom.py
+++ b/module/plugins/hoster/ZippyshareCom.py
@@ -1,6 +1,7 @@
 # -*- coding: utf-8 -*-
 
 import re
+from urllib import unquote
 
 from BeautifulSoup import BeautifulSoup
 
@@ -52,6 +53,9 @@ def handleFree(self, pyfile):
         else:
             self.link = self.get_link()
 
+        if  pyfile.name == 'file.html' and self.link:
+            pyfile.name = unquote(self.link.split('/')[-1])
+
 
     def get_link(self):
         # get all the scripts inside the html body
```

**Closed** 2015-04-08 21:31 UTC
Labels: plugin issue
