### ISSUE TITLE
File Exists is now a failed task

### ISSUE THREAD

**Issue by chaosmaker** [pyload/pyload#1473] opened 2015-06-09 09:50 UTC
I'm not sure why this was changed, but if a file exists it shouldn't be classed as a failed task. This is particularly annoying when you have rss which contains multiple links to the same files, which now means that 1 task finishes and x tasks (however many links it found) are now failed. If anything they should be classed as completed, or "skipped" as they were before.

**Comment by vuolter** [comment] 2015-06-09 10:04
Post a sample debug log.

**Comment by chaosmaker** [comment] 2015-06-09 10:13
This is all it says:
```
269	09.06.2015 10:43:08	WARNING	Download failed: Penny.Dreadful.S02E06.720p.HDTV.X264.DIMENSION.mkv | File exists.
```

**Comment by vuolter** [comment] 2015-06-09 10:33
Understood.

**Comment by TodsDeath** [comment] 2015-06-09 13:28
Why is it a feature request? Until the updates yesterday the files got marked as skipped.

I have packages in my download queue which links got downloaded fine, but then failed with `WARNING	Download failed: ***.rar | checkFile() takes exactly 1 argument (2 given)` (this is also a bug since the yesterdays updates), so the package will not start to extract. When I restart the package, pyload finds the already downloaded files. 

In the past, those already existing files would be skipped (green tick in queue), so the package finished and triggered the extracting. Since yesterday this files are failing (red exclamation mark in queue) with `WARNING	Download failed: ***.rar | File exists.`, the package does not finish and does not trigger the extracting.

**Comment by GammaC0de** [comment] 2015-06-09 20:25
sample effected URL & full log please

**Comment by TodsDeath** [comment] 2015-06-10 06:47
The problem with checkFile was caused by an old version of the Realdebrid plugin in my local installation. Manually triggering an update (lowering the version number in the file) fixed the problem.

Remains the problem with the skipped files, which affects every downloaded and then restarted file (e.g. by a package restart). Traceback looks like this:
```
TRACEBACK:
 Traceback (most recent call last):
  File "/volume1/@appstore/pyload/pyload/module/PluginThread.py", line 182, in run
    pyfile.plugin.checkForSameFiles(starting=True)
  File "/volume1/@appstore/pyload/var/config/userplugins/internal/Plugin.py", line 598, in checkForSameFiles
    raise SkipDownload("File exists.")
SkipDownload: File exists.
```
Digging into Plugin.py shows, that raising the exception and failing is indeed the correct behaviour. Checking the commit history, apparently Plugin.py got only moved and not changed. So why does it behave different than before, where it recognized some already downloaded file?

Now its like "Hey, this file already exists, this is wrong, user has to delete it manually, so I can download it.", where it has been like "Hey, this file already exists, I will use this instead, so there is no need in dowloading it again.".

**Comment by vuolter** [comment] 2015-06-10 07:32
Checking...

**Closed** 2015-06-10 08:46 UTC
Labels: bug

**Comment by TodsDeath** [comment] 2015-06-10 08:53
it's working again, thx!
