### ISSUE TITLE
FilboomMe hoster plugin out of date

### ISSUE THREAD

**Issue by igel-kun** [pyload/pyload#3377] opened 2019-05-03 11:10 UTC
### Type of ticket:

- [ ] Plugin request
- [ ] Feature request
- [x] Bug report
- [ ] Question
- [ ] Other

### Summary:

seems that the guys over at fileboom.me changed their website, which is now basically a whole mess of javascript. However, I think I read somewhere (and the guys developing JDownloader use this I think) that fileboom basically follows the Keep2share API, so this may be a great opportunity to just inherit from Keep2shareCC, change the API URL and be done with it :)

**Comment by GammaC0de** [comment] 2019-05-04 00:38
Thanks for the hint 👍

**Comment by GammaC0de** [comment] 2019-05-04 00:55
Duplicate of #3153

**Closed** 2019-05-04 01:07 UTC
Labels: checking, duplicate, plugin bug
