### ISSUE TITLE
ExtractArchive Unzip broken?

### ISSUE THREAD

**Issue by gr0ebi** [pyload/pyload#3239] opened 2018-10-05 21:01 UTC
This is actually the first time I'm extracting zip files with pyload
When trying to unzip this 65MB zip-file (Kis - DeRoCi.zip), it gets stuck for 7 minutes only showing "archive testing" or "archive extracting" in GUI
On my system, a 100MB rar file only takes a few seconds to unrar
```
239 | 05.10.2018 22:25:12 | DEBUG | ADDON ExtractArchive: Targets for UnZip: [(2602, '/mnt/nfs/backup/XX/XX/Kis - DeRoCi.zip', '/mnt/nfs/backup/XX/XX'), (2605, '/mnt/nfs/backup/XX/XX/Rem-LoMyRe.zip', '/mnt/nfs/backup/XX/XX'), (2600, '/mnt/nfs/backup/XX/XX/SyOfADo - BYOB.zip', '/mnt/nfs/backup/XX/XX'), (2597, '/mnt/nfs/backup/XX/XX/SyOfADo - Que.zip', '/mnt/nfs/backup/XX/XX')]
240 | 05.10.2018 22:25:12 | INFO | ADDON ExtractArchive: Kis - DeRoCi.zip \| Extract to: /mnt/nfs/backup/XX/XX
241 | 05.10.2018 22:25:12 | DEBUG | ADDON ExtractArchive: Password: asdf.com
242 | 05.10.2018 22:27:47 | DEBUG | ADDON ExtractArchive: Extracting using password: asdf.com
243 | 05.10.2018 22:33:00 | DEBUG | ADDON ExtractArchive: Would delete: /mnt/nfs/backup/XX/XX/Kis - DeRoCi.zip
244 | 05.10.2018 22:33:00 | INFO | ADDON ExtractArchive: Kis - DeRoCi.zip \| Extracting finished
245 | 05.10.2018 22:33:00 | DEBUG | ADDON ExtractArchive: Extracted files: ['Kiss - Detroit Rock City/', 'Kiss - Detroit Rock City/Kiss - Detroit Rock City.jpg', 'Kiss - Detroit Rock City/Kiss - Detroit Rock City.mp3', 'Kiss - Detroit Rock City/Kiss - Detroit Rock City.mp4', 'Kiss - Detroit Rock City/Kiss - Detroit Rock City.txt']
246 | 05.10.2018 22:33:00 | DEBUG | ADDON ExternalScripts: No script found under folder `archive_extracted`
247 | 05.10.2018 22:33:00 | INFO | ADDON ExtractArchive: Rem-LoMyRe.zip \| Extract to: /mnt/nfs/backup/XX/XX
248 | 05.10.2018 22:33:00 | DEBUG | ADDON ExtractArchive: Password: asdf.com
249 | 05.10.2018 22:38:54 | DEBUG | ADDON ExtractArchive: Extracting using password: asdf.com

```

I'm not sure why the archive is beeing tested, since "Use checksum" isn't set

Python: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
OS: `posix linux2 Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64`

Any help appreciated,
Thanks

**Comment by GammaC0de** [comment] 2018-10-05 23:20
Try installing 7-zip and then restart pyload and see if it helps.

**Comment by gr0ebi** [comment] 2018-10-05 23:39
> Try installing 7-zip and then restart pyload and see if it helps.

had it installed, I also tried p7zip-full - still not working as supposed

**Comment by GammaC0de** [comment] 2018-10-05 23:55
Can you share the URL?

**Comment by gr0ebi** [comment] 2018-10-05 23:58
I can if you want to but I have at least 2 different zip files that aren't working

**Comment by GammaC0de** [comment] 2018-10-06 01:01
Whell, choose a URL that you don't mind to share ad if it fails I will test the same URL here.

**Comment by gr0ebi** [comment] 2018-10-06 01:41
http://ul.to/omz50kry
pw: ultrastar-base.com

thanks a lot

**Comment by GammaC0de** [comment] 2018-10-06 17:32
Well, after checking I can tell that the issue is not in pyLoad but the poor performance of python's `zipfile` module when handling password protected zips.

You can try this code snippet and see how much time it takes :disappointed: :
```python
import zipfile
import time

def TestZip(filename, password):
    print("Checking %s" % filename)
    t = time.time()
    with zipfile.ZipFile(filename, 'r') as z:
        if password:
            z.setpassword(password)
        badfile = z.testzip()
        if badfile is not None:
            print("CRC error: " % badfile)
    print("Done. it took %s seconds" % (time.time() -t))

if __name__ == "__main__":
    TestZip("Kis - DeRoCi 1.zip", "ultrastar-base.com")
```

**Comment by gr0ebi** [comment] 2018-10-06 18:07
Thanks a lot @GammaC0de 
You're right, it took 140.6999 sedonds for 65MB 😒

**Comment by GammaC0de** [comment] 2018-10-06 18:31
Right, but the "good" news is that it finishes eventually.. :grimacing:

If you want, there is `czipfile` moule (https://github.com/V-E-O/czipfile) that is supposed to deal with this, it is from 2015 though.

Closing..

**Closed by GammaC0de** 2018-10-06 18:31 UTC
