### ISSUE TITLE
Premiumize with broken filenames

### ISSUE THREAD

**Issue by snickers2k** [pyload/pyload#1800] opened 2015-08-31 22:38 UTC
The filenames are often something like "pntiohtx" "oemc3bfb" "etls17b6" "o8f716hs" instead of the real .rar file name

**Comment by boerngen-schmidt** [comment] 2015-09-02 11:59
It does not really matter since once the file is downloaded the original filename is used. Though it is an annoyance. In #1624 I had a similar issue. Maybe this is connected?

I guess it is somewhat connected to @GammaC0de's change dedce876f1f9cb9ad9f8b135ced26bf19fc1dbc7

**Comment by GammaC0de** [comment] 2015-09-02 12:09
@boerngen-schmidt without a debug log these are all pure assumptions.
@snickers2k please post debug log.

**Comment by boerngen-schmidt** [comment] 2015-09-02 12:17
@GammaC0de that is true, but comparing the changes in both commits yours and the one in #1624 It seems plausible. I had this issue too a few days back, but now I dont.

**Comment by GammaC0de** [comment] 2015-09-02 12:51
@boerngen-schmidt  maybe you are right, but again, without a debug log one cannot be sure.
I would have test it myself but since it is a premium only hoster I cannot.

**Comment by snickers2k** [comment] 2015-09-02 14:17
i have debug-mode enabled, and maybe i overlooked it, but i think there wasn't any debug log :(
i check it again, as soon as the bug appears again. thanks

**Comment by boerngen-schmidt** [comment] 2015-09-02 14:21
@GammaC0de I do have a Premiumize Account and I had the same problem described here a few days back (~4days or so). I tested it today, but it seems to be working just fine and the issue is not reproduceable right now.

So I would suggest to close this bug for now.

**Comment by snickers2k** [comment] 2015-09-02 14:26
you're right. i had the bug just for one or two days.
but "working just fine"? is premiumize really working for you?! with uploaded, i'm getting always the error "Bad server response: 403 Forbidden 168.00 B" .. but i think it's premiumize itself, not pyload. because with chrome i'm getting the error "access error" .. 

but yes, i'm done with premiumize anyway.

so lets close this issue

**Comment by boerngen-schmidt** [comment] 2015-09-02 14:33
Yes Premiumize is working for me, although I get the same 403 Error once in a while, but I do not care since it is more a backup. I just restart the downloads and then they work (most of the time).

I do not think that it is a Premiumize Issue in general, since I tried to download a file with pyload and got the 403, but using the FF Premiumize Plugin just downloaded the file fine. I have not investigated this issue yet due to not enough time, but this then would be another issue.

**Comment by snickers2k** [comment] 2015-09-03 20:43
and again...a few days, nothing worked.. today it's working again, but with the filename bug

03.09.2015 22:42:13	DEBUG	HOSTER PremiumizeMe[1869]: PremiumizeMe | PROCESS URL http://uploaded.net/file/pyovo237 | PLUGIN VERSION 0.20
83	03.09.2015 22:42:13	INFO	HOSTER PremiumizeMe[1869]: PremiumizeMe | Updating file info...
84	03.09.2015 22:42:13	DEBUG	HOSTER PremiumizeMe[1869]: PremiumizeMe | File info: {'status': 3, 'url': u'http://uploaded.net/file/pyovo237', 'name': u'pyovo237', 'size': 0}
85	03.09.2015 22:42:13	DEBUG	HOSTER PremiumizeMe[1869]: PremiumizeMe | Previous file info: {}
86	03.09.2015 22:42:13	INFO	HOSTER PremiumizeMe[1869]: PremiumizeMe | File name: pyovo237
87	03.09.2015 22:42:13	INFO	HOSTER PremiumizeMe[1869]: PremiumizeMe | File size: 105906176 bytes
88	03.09.2015 22:42:13	INFO	HOSTER PremiumizeMe[1869]: PremiumizeMe | File status: queued
89	03.09.2015 22:42:13	DEBUG	HOSTER PremiumizeMe[1869]: PremiumizeMe | LOAD URL http://uploaded.net/file/pyovo237 | cookies=True | get={} | req=None | decode=True | multipart=False | post={} | ref=False | just_header=False
90	03.09.2015 22:42:14	INFO	HOSTER PremiumizeMe[1869]: PremiumizeMe | File status: queued
91	03.09.2015 22:42:14	INFO	HOSTER PremiumizeMe[1869]: PremiumizeMe | Processing as premium download...
92	03.09.2015 22:42:14	DEBUG	HOSTER PremiumizeMe[1869]: PremiumizeMe | LOAD URL http://api.premiumize.me/pm-api/v1.php | cookies=True | get={'params[link]': u'http://uploaded.net/file/pyovo237', 'params[pass]': 'sqqwn2zg4ketz3hx', 'params[login]': '709558658', 'method': 'directdownloadlink'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
93	03.09.2015 22:42:18	INFO	HOSTER PremiumizeMe[1869]: PremiumizeMe | Downloading file...
94	03.09.2015 22:42:18	DEBUG	HOSTER PremiumizeMe[1869]: PremiumizeMe | DOWNLOAD URL https://c-2538627716.energycdn.com/cdl?key=665ad704f7aaa47c5a93e53a7399299f&log=eyJzaXRlIjoicHJlbWl1bWl6ZSIsInVzZXJfaWQiOiI3MDk1NTg2NTgiLCJzZXJ2aWNlIjoidXBsb2FkZWQudG8ifQ&sig=zBBPYmi7flBJndNOcmtUbhbgzdA= | cookies=True | get={} | disposition=True | post={} | ref=True
95	03.09.2015 22:42:18	DEBUG	Content-Disposition: BLT7P101.part1.rar

**Comment by GammaC0de** [comment] 2015-09-04 00:08
@snickers2k if I understand right, the issue you are complaining about is that the file name is not displayed right in the Active Downloads page but the actual file does have the correct name?

**Comment by boerngen-schmidt** [comment] 2015-09-04 09:54
@GammaC0de That is correct. Also it happen, that files are not marked as downloaded, even if they were. So the download stays at 0%, no extracting etc will happen.

**Comment by GammaC0de** [comment] 2015-09-05 18:59
Please try this patch for a decent period of time and then post the results, thanks.

```patch
--- PremiumizeMe.py.bak 2015-08-08 22:59:40.000000000 +0300
+++ PremiumizeMe.py     2015-09-05 21:57:04.012615834 +0300
@@ -44,6 +44,12 @@
         status = data['status']

         if status == 200:
+            if 'filename' in data['result']:
+                self.pyfile.name = data['result']['filename']
+
+            if 'filesize' in data['result']:
+                self.pyfile.size = data['result']['filesize']
+
             self.link = data['result']['location']
             return

```

**Comment by GammaC0de** [comment] 2015-09-06 18:22
@snickers2k please change your premiumize password as the log you have posted before reveals is.

**Comment by GammaC0de** [comment] 2015-09-14 14:31
Hi,
any conclusion yet?

**Closed** 2015-09-20 22:17 UTC
