### ISSUE TITLE
2nd free download from hoster not starting

### ISSUE THREAD

**Issue by stefan1983** [pyload/pyload#3579] opened 2020-04-10 18:28 UTC
Describe the problem

Similar to an already submitted bugfix > https://github.com/pyload/pyload/issues/3415 I've got the same issue with turbobit.net. In free mode the hoster allows you to download 1 file per xx min. After this "xx min blocking period" you can start downloading another file - disregard whether the previous file has already been fully downloaded or not.

Pyload does not start a new download for me after this "xx min blocking period" - neither from existing queue nor if I add a new one manually.

**Comment by GammaC0de** [comment] 2020-04-10 20:46
Duplicate of #255

**Comment by GammaC0de** [comment] 2020-04-10 20:47
Please test proposed solution in #255

**Comment by stefan1983** [comment] 2020-04-10 21:56
Thanks, how to apply the patch file? Just put in the root folder and restart pyload?

**Comment by GammaC0de** [comment] 2020-04-10 22:20
No, If you do not know how to apply patch file, I will have to send you the patched files and you replace the files.

**Comment by GammaC0de** [comment] 2020-04-10 22:50
Here are the patched files: [255.zip](https://github.com/pyload/pyload/files/4463649/255.zip)

**Comment by stefan1983** [comment] 2020-04-11 06:59
Thanks, I'll give it a try.

**Comment by stefan1983** [comment] 2020-04-11 07:17
FYI, I am running pyload in docker (linuxserver/pyload) currently. 

![image](https://user-images.githubusercontent.com/8542806/79037849-e4caca80-7bd4-11ea-8e06-2967007010f5.png)

I guess the plugins > internal > Base.py has to be moved to >userplugins > internal Base.py 
But how about module > ThreadManager.py ??? Create folder "module" and place the file there? Currently I do not find "ThreadManager.py" in my pyload folder install folder.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/8542806/79037839-d381be00-7bd4-11ea-90b1-78f226d993d9.png">

Thanks!
Stefan

**Comment by GammaC0de** [comment] 2020-04-11 11:51
You will have to build a new docker image with replaced files.
I cannot help you with that.

**Comment by stefan1983** [comment] 2020-04-11 19:46
> You will have to build a new docker image with replaced files.
> I cannot help you with that.

I know how to deploy a new docker image, but that is actually not necessary since those files in the second picture above are the persistent files created by the docker image. So I would just need to replace the current files with the ones you prepared. 
I am just wondering about the files and folder since they have different names than the ones you prepared.

Thanks

**Comment by GammaC0de** [comment] 2020-04-11 19:53
`Base.py` goes to `module/plugins/internal` directory
`ThreadManager.py` goes into `module` directory

Those file should be inside the docker image. (they are not shown in the second picture)

**Comment by stefan1983** [comment] 2020-04-11 20:50
Hmm...., ok. Thanks for the direction.
Currently I am using the linuxserver / pyload docker image. 

Is there something like an official pyload docker image?  I didn't find one, but the most favourite one is the writl / pyload docker image, I´ll give it a try. Maybe the folders are different from the one I am currently using.

**Comment by GammaC0de** [comment] 2020-04-11 20:56
> Is there something like an official pyload docker image?

No, no spare time for making docker image.

linuxserver/pyload and writl/pyload are the two known docker images

**Comment by stefan1983** [comment] 2020-04-11 22:29
That's how a newly created docker image folder looks alike (no folder "module", no folder "plugins"). I fear that just "copy over" those files might not work.....


> /sharedfolders/Docker/AppData/pyload-test$ ls -R
> .:
> accounts.conf  files.db  files.version	Logs  plugin.conf  pyload.conf	pyload.pid  scripts  setup.lock  tmp  userplugins
> 
> ./Logs:
> log.txt
> 
> ./scripts:
> after_reconnect		all_downloads_finished	 archive_extract_failed  download_finished   package_deleted	     package_failed	pyload_restart
> all_archives_extracted	all_downloads_processed  before_reconnect	 download_preparing  package_extracted	     package_finished	pyload_start
> all_archives_processed	archive_extracted	 download_failed	 download_processed  package_extract_failed  package_processed	pyload_stop
> 
> ./scripts/after_reconnect:
> 
> ./scripts/all_archives_extracted:
> 
> ./scripts/all_archives_processed:
> 
> ./scripts/all_downloads_finished:
> 
> ./scripts/all_downloads_processed:
> 
> ./scripts/archive_extracted:
> 
> ./scripts/archive_extract_failed:
> 
> ./scripts/before_reconnect:
> 
> ./scripts/download_failed:
> 
> ./scripts/download_finished:
> 
> ./scripts/download_preparing:
> 
> ./scripts/download_processed:
> 
> ./scripts/package_deleted:
> 
> ./scripts/package_extracted:
> 
> ./scripts/package_extract_failed:
> 
> ./scripts/package_failed:
> 
> ./scripts/package_finished:
> 
> ./scripts/package_processed:
> 
> ./scripts/pyload_restart:
> 
> ./scripts/pyload_start:
> 
> ./scripts/pyload_stop:
> 
> ./tmp:
> jinja_cache
> 
> ./tmp/jinja_cache:
> 
> ./userplugins:
> accounts  captcha  container  crypter  hooks  hoster  __init__.py  __init__.pyc  internal
> 
> ./userplugins/accounts:
> FshareVn.py  __init__.py  LinkifierCom.py  RealdebridCom.py  UlozTo.py
> 
> ./userplugins/captcha:
> __init__.py  __init__.pyc
> 
> ./userplugins/container:
> __init__.py
> 
> ./userplugins/crypter:
> Dereferer.py  Dereferer.pyc  __init__.py  __init__.pyc	MegaCoNzFolder.py  MegaCoNzFolder.pyc  RealdebridComTorrent.py	RealdebridComTorrent.pyc  XFileSharingFolder.py  XFileSharingFolder.pyc
> 
> ./userplugins/hooks:
> __init__.py
> 
> ./userplugins/hoster:
> FastshareCz.py	 FshareVn.py   __init__.py   MegaCoNz.py   PremiumTo.py   RapidgatorNet.py   RealdebridCom.py	UlozTo.py   XDCC.py   XFileSharing.py	YoutubeCom.py
> FastshareCz.pyc  FshareVn.pyc  __init__.pyc  MegaCoNz.pyc  PremiumTo.pyc  RapidgatorNet.pyc  RealdebridCom.pyc	UlozTo.pyc  XDCC.pyc  XFileSharing.pyc	YoutubeCom.pyc
> 
> ./userplugins/internal:
> Account.py  Addon.pyc  Base.pyc    Captcha.pyc	Hoster.pyc   __init__.pyc  misc.pyc	    MultiCrypter.pyc  MultiHoster.pyc  Plugin.py
> Addon.py    Base.py    Captcha.py  Hoster.py	__init__.py  misc.py	   MultiCrypter.py  MultiHoster.py    OCR.py	       Plugin.pyc

**Comment by stefan1983** [comment] 2020-04-11 23:08
So, as predicted..., that didn't work. I was able to replace the Base.py (userplugins > internal > Base.py). But there wasn't any folder named "module". There wasn't also a file called "ThreadManager.py" in any of the other folders..., so I think the links didn't work then.

Any other idea?

**Comment by stefan1983** [comment] 2020-04-12 08:17
Sorry, I was mistaken.... the folder shown above is not the complete installation folder of the pyload container. 🙈

After accessing the "/" folder of the docker container, I found the folders you mentioned in "app/pyload": 

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/8542806/79064125-8ff78480-7ca6-11ea-957c-159e207c909f.png">

I now replaced those files from you and have a test run with TurbobitNet again.....

**Comment by stefan1983** [comment] 2020-04-12 10:19
So, I tested it now..., does not work. I replaced the files but that seems to didn't have any feedback. From the log files I can see, that there is no counter or anything which indicates, that pyload would try again in xxx minutes.

I just double checked that the files are indeed the correct ones:

> root@pyload2:/# ls
> app  config    dev          downloads  home  lib      media  opt   root  sbin     srv  tmp  var
> bin  defaults  docker-mods  etc        init  libexec  mnt    proc  run   scripts  sys  usr
> root@pyload2:/# sha256sum app/pyload/module/ThreadManager.py
> 2439c622dc2efa36bd736f73f43be06380c43759c8ed029c35082b391686f3d3  app/pyload/module/ThreadManager.py
> root@pyload2:/# sha256sum downloads/255/module/ThreadManager.py
> 2439c622dc2efa36bd736f73f43be06380c43759c8ed029c35082b391686f3d3  downloads/255/module/ThreadManager.py
> root@pyload2:/# sha256sum app/pyload/module/plugins/internal/Base.py
> 18c26dac0b2994596720093097d6bc110ed6e22e0258a21d144840587211ea4e  app/pyload/module/plugins/internal/Base.py
> root@pyload2:/# sha256sum downloads/255/plugins/internal/Base.py
> 18c26dac0b2994596720093097d6bc110ed6e22e0258a21d144840587211ea4e  downloads/255/plugins/internal/Base.py

**Closed** 2020-10-03 04:58 UTC
Labels: outdated, plugin bug
