### ISSUE TITLE
Download-Issue with Filer.net on Qnap

### ISSUE THREAD

**Issue by cryzto** [pyload/pyload#1201] opened 2015-02-23 08:56 UTC
Hi @vuolter 
Unfortunately I experience some Issues when downloading from Filer.net. Some links have the status "waiting". When I try to download directly from the site it works fine, but from pyLoad it seems to have kinda issues. Last Update where the Plugin worked I turned OFF the Updatemanager, so no updates could compromise the whole thing...then since a few days this issue appeared.
![filer net](https://cloud.githubusercontent.com/assets/6126067/6325022/31cb0c9a-bb42-11e4-8ae7-0a878d5b2d27.png)

**Comment by cryzto** [comment] 2015-02-23 08:59
Here the Debug:
189	23.02.2015 09:58:38	DEBUG	Download Check triggered
188	23.02.2015 09:58:36	INFO	FilerNet: Direct download link detected
187	23.02.2015 09:58:36	DEBUG	Download Check triggered
186	23.02.2015 09:58:35	DEBUG	FilerNet: Redirect #2 to: http://dl2.filer.net/dl/3ae2525e2d7764927fdcc9363da6ccfd/54eaec0c/p1m2biaqon8alzoy/f4earszhrtsdftrf4w.part2.rar
185	23.02.2015 09:58:35	DEBUG	FilerNet: Redirect #1 to: http://filer.net/dl/2ce1334344b2f3bade1fd20497ab0750e8bc73af/p1m2biaqon8alzoy?apikey=
184	23.02.2015 09:58:35	DEBUG	FilerNet: Redirect #0 to: http://filer.net/get/p1m2biaqon8alzoy
183	23.02.2015 09:58:35	DEBUG	FilerNet: Looking for direct download link...

**Comment by cryzto** [comment] 2015-03-10 08:36
any progress in here? ;-)

**Comment by vuolter** [comment] 2015-03-10 14:33
Checking...

**Comment by vuolter** [comment] 2015-03-10 15:29
Try: https://github.com/pyload/pyload/commit/85bba1418987aa3e8b11a75a2732577da6008d8a

**Comment by cryzto** [comment] 2015-03-10 15:48
still the same :-(

**Comment by vuolter** [comment] 2015-03-10 16:08
Could you post some sample url. I tried to download 10 links at once (as premium) and all went fine. :S

**Comment by cryzto** [comment] 2015-03-10 16:42
Try this one:
http://filer.net/folder/ai3b00umflydtexn


Von Samsung-Tablet gesendet


-------- Ursprüngliche Nachricht --------
Von: Walter Purcaro <notifications@github.com> 
Datum:10.03.2015  17:08  (GMT+01:00) 
An: pyload/pyload <pyload@noreply.github.com> 
Cc: Cris <cryzto@cryzto.ch> 
Betreff: Re: [pyload] Download-Issue with Filer.net (#1201) 

Could you post some sample url. I tried to download 10 links at once (as premium) and all went fine. :S

**Comment by vuolter** [comment] 2015-03-10 17:54
@cryzto Works for me. :S

**Comment by cryzto** [comment] 2015-03-10 19:34
@vuolter how come? Dam'it....




Von Samsung-Tablet gesendet


-------- Ursprüngliche Nachricht --------
Von: Walter Purcaro <notifications@github.com> 
Datum:10.03.2015  18:54  (GMT+01:00) 
An: pyload/pyload <pyload@noreply.github.com> 
Cc: Cris <cryzto@cryzto.ch> 
Betreff: Re: [pyload] Download-Issue with Filer.net (#1201) 

@cryzto Works for me. :S

**Comment by vuolter** [comment] 2015-03-10 20:09
When filer.net plugin downloads an html file, simplehoster retry download, but in that case, should mark the file as offline. u.u

**Comment by cryzto** [comment] 2015-03-10 22:13
@vuolter
Now it makrs the file offline...thats not true.

1010 10.03.2015 23:09:57 WARNING Download is offline: 9564532565.part7.rar
1009 10.03.2015 23:09:56 INFO FilerNet: Direct download link detected

Gosh...thats frustrating :-(

**Comment by vuolter** [comment] 2015-03-10 22:30
I tried all the file you posted + some found on the web. When the plugin retry if because the file is offline. Then I put all the files on jd and got the same behaviour...

**Comment by cryzto** [comment] 2015-03-10 22:36
Well I tried it with direct download just to witness that the files are not offline...so something is definitely wrong
:-(

**Comment by vuolter** [comment] 2015-03-10 22:50
Okay, post the url you tested.

**Comment by cryzto** [comment] 2015-03-10 22:52
http://filer.net/folder/u6saumon4gziffhu

**Comment by cryzto** [comment] 2015-03-10 22:52
318	10.03.2015 23:52:16	WARNING	Download is offline: ttykc3af8cowsnsm
317	10.03.2015 23:52:15	INFO	FilerNet: Direct download link detected
316	10.03.2015 23:52:14	WARNING	Download is offline: 374520740124.part5.rar
315	10.03.2015 23:52:13	INFO	FilerNet: Direct download link detected
314	10.03.2015 23:52:13	INFO	Download starts: 374520740124.part6.rar
313	10.03.2015 23:52:12	WARNING	Download is offline: s8pw2p5urnoosae6
312	10.03.2015 23:52:11	INFO	FilerNet: Direct download link detected
311	10.03.2015 23:52:11	INFO	Download starts: 4twzzpbyaktcc9vk
310	10.03.2015 23:52:10	WARNING	Download is offline: zke3mivuq2kt7lg5
309	10.03.2015 23:52:09	INFO	FilerNet: Direct download link detected
308	10.03.2015 23:52:09	INFO	Download starts: s8pw2p5urnoosae6
307	10.03.2015 23:52:08	WARNING	Download is offline: 374520740124.part2.rar
306	10.03.2015 23:52:07	INFO	Download starts: zke3mivuq2kt7lg5
305	10.03.2015 23:52:07	INFO	FilerNet: Direct download link detected
304	10.03.2015 23:52:06	WARNING	Download is offline: ccfftxt6zwrwjo4x
303	10.03.2015 23:52:05	INFO	Download starts: hhl84lyz7kdllfwm
302	10.03.2015 23:52:05	INFO	FilerNet: Direct download link detected
301	10.03.2015 23:52:03	INFO	Download starts: ccfftxt6zwrwjo4x
300	10.03.2015 23:52:01	INFO	Added package 374520740124 containing 6 links
299	10.03.2015 23:52:01	INFO	Decrypting starts: 374520740124
298	10.03.2015 23:52:00	INFO	Added package Housebound containing 1 links

**Comment by vuolter** [comment] 2015-03-10 23:03
And... all work for me again:

```
10.03.2015 23:59:15 INFO      Added package TEST containing 1 links
10.03.2015 23:59:15 DEBUG     Run Info Fetching for FilerNetFolder
10.03.2015 23:59:15 DEBUG     Finished Info Fetching for FilerNetFolder
10.03.2015 23:59:16 INFO      Decrypting starts: 374520740124
10.03.2015 23:59:16 DEBUG     FilerNetFolder: File info (BEFORE): {}
10.03.2015 23:59:16 DEBUG     FilerNetFolder: File info (AFTER): {'status': 2, 'url': u'http://filer.net/folder/u6saumon4gziffhu',
 'size': 0, 'name': u'374520740124', 'pattern': {'N': u'374520740124'}}
10.03.2015 23:59:16 DEBUG     FilerNetFolder: File name: 374520740124 | File folder: 374520740124
10.03.2015 23:59:17 DEBUG     FilerNetFolder: File info (BEFORE): {'status': 2, 'name': u'374520740124', 'url': u'http://filer.net
/folder/u6saumon4gziffhu', 'pattern': {'N': u'374520740124'}, 'folder': u'374520740124', 'size': 0}
10.03.2015 23:59:17 DEBUG     FilerNetFolder: File info (AFTER): {'status': 2, 'name': u'374520740124', 'url': u'http://filer.net/
folder/u6saumon4gziffhu', 'pattern': {'N': u'374520740124'}, 'folder': u'374520740124', 'size': 0}
10.03.2015 23:59:17 DEBUG     FilerNetFolder: File name: 374520740124 | File folder: 374520740124
10.03.2015 23:59:17 DEBUG     FilerNetFolder: File status: online
10.03.2015 23:59:17 DEBUG     FilerNetFolder: Package has 6 links
10.03.2015 23:59:17 DEBUG     Parsed package 374520740124 with 6 links
10.03.2015 23:59:17 DEBUG     Run Info Fetching for FilerNet
10.03.2015 23:59:17 INFO      Added package 374520740124 containing 6 links
10.03.2015 23:59:18 INFO      Download starts: ccfftxt6zwrwjo4x
10.03.2015 23:59:18 DEBUG     FilerNet: Update file info...
10.03.2015 23:59:18 DEBUG     FilerNet: Previous file info: {}
10.03.2015 23:59:19 DEBUG     FilerNet: Current file info: {'status': 3, 'url': u'http://filer.net/get/ccfftxt6zwrwjo4x', 'name':
u'ccfftxt6zwrwjo4x', 'size': 0}
10.03.2015 23:59:19 DEBUG     FilerNet: File name: ccfftxt6zwrwjo4x | File size: Unknown
10.03.2015 23:59:19 DEBUG     FilerNet: File status: queued
10.03.2015 23:59:19 DEBUG     FilerNet: Looking for direct download link...
10.03.2015 23:59:19 DEBUG     FilerNet: Redirect #0 to: http://filer.net/get/ccfftxt6zwrwjo4x
10.03.2015 23:59:19 DEBUG     FilerNet: Redirect #1 to: http://filer.net/dl/7080805e9cf28d1e418c9931f1c1f5a1ec79e2a5/ccfftxt6zwrwj
o4x?apikey=
10.03.2015 23:59:19 DEBUG     FilerNet: Redirect #2 to: http://dl9.filer.net/dl/ec0aadc566e6142443b700afc1e7e4ac/54ff774a/ccfftxt6
zwrwjo4x/374520740124.part1.rar
10.03.2015 23:59:20 INFO      Download starts: hhl84lyz7kdllfwm
10.03.2015 23:59:20 DEBUG     FilerNet: Update file info...
10.03.2015 23:59:20 DEBUG     FilerNet: Previous file info: {}
10.03.2015 23:59:20 DEBUG     Finished Info Fetching for FilerNet
10.03.2015 23:59:20 INFO      FilerNet: Direct download link detected
10.03.2015 23:59:21 DEBUG     FilerNet: Current file info: {'status': 3, 'url': u'http://filer.net/get/hhl84lyz7kdllfwm', 'name':
u'hhl84lyz7kdllfwm', 'size': 0}
10.03.2015 23:59:21 DEBUG     FilerNet: File name: hhl84lyz7kdllfwm | File size: Unknown
10.03.2015 23:59:21 DEBUG     FilerNet: File status: queued
10.03.2015 23:59:21 DEBUG     FilerNet: Looking for direct download link...
10.03.2015 23:59:21 DEBUG     FilerNet: Redirect #0 to: http://filer.net/get/hhl84lyz7kdllfwm
10.03.2015 23:59:21 DEBUG     FilerNet: Redirect #1 to: http://filer.net/dl/578ac347aa4f2e8a340bb3cc4748cdcc49179d8c/hhl84lyz7kdll
fwm?apikey=
10.03.2015 23:59:21 DEBUG     FilerNet: Redirect #2 to: http://dl9.filer.net/dl/4d581c1e95b3b5d9ea5b712873e53573/54ff774c/hhl84lyz
7kdllfwm/374520740124.part2.rar
10.03.2015 23:59:22 INFO      Download starts: zke3mivuq2kt7lg5
10.03.2015 23:59:22 DEBUG     FilerNet: Update file info...
10.03.2015 23:59:22 DEBUG     FilerNet: Previous file info: {}
10.03.2015 23:59:23 DEBUG     Content-Disposition: 374520740124.part1.rar
10.03.2015 23:59:23 DEBUG     Chunked with range 41943041-83886082
10.03.2015 23:59:23 DEBUG     Chunked with range 83886082-
10.03.2015 23:59:23 INFO      FilerNet: Direct download link detected
10.03.2015 23:59:23 DEBUG     FilerNet: Current file info: {'status': 3, 'url': u'http://filer.net/get/zke3mivuq2kt7lg5', 'name':
u'zke3mivuq2kt7lg5', 'size': 0}
10.03.2015 23:59:23 DEBUG     FilerNet: File name: zke3mivuq2kt7lg5 | File size: Unknown
10.03.2015 23:59:23 DEBUG     FilerNet: File status: queued
10.03.2015 23:59:23 DEBUG     FilerNet: Looking for direct download link...
10.03.2015 23:59:23 DEBUG     FilerNet: Redirect #0 to: http://filer.net/get/zke3mivuq2kt7lg5
10.03.2015 23:59:23 DEBUG     FilerNet: Redirect #1 to: http://filer.net/dl/3c562af01515d8645f4dfa407dfd06bf1580b761/zke3mivuq2kt7
lg5?apikey=
10.03.2015 23:59:24 DEBUG     FilerNet: Redirect #2 to: http://dl9.filer.net/dl/63b522254e00632167a11301ae054029/54ff774e/zke3mivu
q2kt7lg5/374520740124.part3.rar
10.03.2015 23:59:24 INFO      Download starts: s8pw2p5urnoosae6
10.03.2015 23:59:24 DEBUG     FilerNet: Update file info...
10.03.2015 23:59:24 DEBUG     FilerNet: Previous file info: {}
10.03.2015 23:59:25 INFO      FilerNet: Direct download link detected
10.03.2015 23:59:25 DEBUG     Content-Disposition: 374520740124.part2.rar
10.03.2015 23:59:25 DEBUG     Chunked with range 41943041-83886082
10.03.2015 23:59:25 DEBUG     Chunked with range 83886082-
10.03.2015 23:59:25 DEBUG     FilerNet: Current file info: {'status': 3, 'url': u'http://filer.net/get/s8pw2p5urnoosae6', 'name':
u's8pw2p5urnoosae6', 'size': 0}
10.03.2015 23:59:25 DEBUG     FilerNet: File name: s8pw2p5urnoosae6 | File size: Unknown
10.03.2015 23:59:25 DEBUG     FilerNet: File status: queued
10.03.2015 23:59:25 DEBUG     FilerNet: Looking for direct download link...
10.03.2015 23:59:25 DEBUG     FilerNet: Redirect #0 to: http://filer.net/get/s8pw2p5urnoosae6
10.03.2015 23:59:25 DEBUG     FilerNet: Redirect #1 to: http://filer.net/dl/1bd3696b1a9853d5d255e8c915b8c2860ae17454/s8pw2p5urnoos
ae6?apikey=
10.03.2015 23:59:25 DEBUG     FilerNet: Redirect #2 to: http://dl9.filer.net/dl/4512b0bf92bfc91de7251aa67f0f7789/54ff7750/s8pw2p5u
rnoosae6/374520740124.part4.rar
10.03.2015 23:59:26 INFO      Download starts: 374520740124.part5.rar
10.03.2015 23:59:26 DEBUG     FilerNet: Update file info...
10.03.2015 23:59:26 DEBUG     FilerNet: Previous file info: {}
10.03.2015 23:59:26 INFO      FilerNet: Direct download link detected
10.03.2015 23:59:27 DEBUG     Content-Disposition: 374520740124.part3.rar
10.03.2015 23:59:27 DEBUG     Chunked with range 41943041-83886082
10.03.2015 23:59:27 DEBUG     Chunked with range 83886082-
10.03.2015 23:59:27 DEBUG     FilerNet: Current file info: {'status': 3, 'url': u'http://filer.net/get/4twzzpbyaktcc9vk', 'name':
u'4twzzpbyaktcc9vk', 'size': 0}
10.03.2015 23:59:27 DEBUG     FilerNet: File name: 4twzzpbyaktcc9vk | File size: 125829120 byte
10.03.2015 23:59:27 DEBUG     FilerNet: File status: queued
10.03.2015 23:59:27 DEBUG     FilerNet: Looking for direct download link...
10.03.2015 23:59:27 DEBUG     FilerNet: Redirect #0 to: http://filer.net/get/4twzzpbyaktcc9vk
10.03.2015 23:59:27 DEBUG     FilerNet: Redirect #1 to: http://filer.net/dl/702c0df3c5ae99c90a7c8b596fa3a4b20bdbc642/4twzzpbyaktcc
9vk?apikey=
10.03.2015 23:59:28 DEBUG     FilerNet: Redirect #2 to: http://dl10.filer.net/dl/c7ffd38eb5c19f0676565bd34f773140/54ff7752/4twzzpb
yaktcc9vk/374520740124.part5.rar
10.03.2015 23:59:28 INFO      Download starts: ttykc3af8cowsnsm
10.03.2015 23:59:28 DEBUG     FilerNet: Update file info...
10.03.2015 23:59:28 DEBUG     FilerNet: Previous file info: {}
10.03.2015 23:59:29 DEBUG     Content-Disposition: 374520740124.part4.rar
10.03.2015 23:59:29 DEBUG     Chunked with range 41943041-83886082
10.03.2015 23:59:29 DEBUG     Chunked with range 83886082-
10.03.2015 23:59:29 INFO      FilerNet: Direct download link detected
10.03.2015 23:59:29 DEBUG     FilerNet: Current file info: {'status': 3, 'url': u'http://filer.net/get/ttykc3af8cowsnsm', 'name':
u'ttykc3af8cowsnsm', 'size': 0}
10.03.2015 23:59:29 DEBUG     FilerNet: File name: ttykc3af8cowsnsm | File size: Unknown
10.03.2015 23:59:29 DEBUG     FilerNet: File status: queued
10.03.2015 23:59:29 DEBUG     FilerNet: Looking for direct download link...
10.03.2015 23:59:29 DEBUG     FilerNet: Redirect #0 to: http://filer.net/get/ttykc3af8cowsnsm
10.03.2015 23:59:29 DEBUG     FilerNet: Redirect #1 to: http://filer.net/dl/6c4c671a2945c52eae4539adb709f7f471664f57/ttykc3af8cows
nsm?apikey=
10.03.2015 23:59:30 DEBUG     FilerNet: Redirect #2 to: http://dl10.filer.net/dl/6e7e9cbd30f87b43815fc69f713c62cc/54ff7754/ttykc3a
f8cowsnsm/374520740124.part6.rar
10.03.2015 23:59:31 DEBUG     Content-Disposition: 374520740124.part5.rar
10.03.2015 23:59:31 DEBUG     Chunked with range 41943041-83886082
10.03.2015 23:59:31 DEBUG     Chunked with range 83886082-
10.03.2015 23:59:31 INFO      FilerNet: Direct download link detected
10.03.2015 23:59:33 DEBUG     Content-Disposition: 374520740124.part6.rar
10.03.2015 23:59:33 DEBUG     Chunked with range 28558621-57117242
10.03.2015 23:59:33 DEBUG     Chunked with range 57117242-
10.03.2015 23:59:52 INFO      Download aborted: ccfftxt6zwrwjo4x
10.03.2015 23:59:52 INFO      Download aborted: hhl84lyz7kdllfwm
10.03.2015 23:59:52 INFO      Download aborted: zke3mivuq2kt7lg5
10.03.2015 23:59:52 INFO      Download aborted: s8pw2p5urnoosae6
10.03.2015 23:59:52 INFO      Download aborted: 4twzzpbyaktcc9vk
10.03.2015 23:59:53 INFO      Download aborted: ttykc3af8cowsnsm
10.03.2015 23:59:53 DEBUG     All downloads processed
```

Okay, file names need a fix... ;)

**Comment by cryzto** [comment] 2015-03-11 05:51
Yeah file names are crap...and the package name still is different to the one chosen...but I really don't understand where the problem is...I guess I start a new Setup clean...from scratch...I don't know where the problem is, cause I only use these two pluginz:
filer.net
file4safe.com
...
I'll let you know...thnx for ur result @vuolter

**Comment by cryzto** [comment] 2015-03-11 13:05
@vuolter 
I installed it now from scratch...still same issue...I don't know WHY it wokrs on you...since last update I get "file offline"....I didn't touch any preferences...

**Comment by cryzto** [comment] 2015-03-11 17:00
Here the debug-text:
WARNING	FilerNet: Bad file | Waiting 1 minute and retry

**Comment by vuolter** [comment] 2015-03-11 18:32
Yep, I add that warning. Anyway you should see it if the file is online... Which OS do you use + python version, please.

**Comment by cryzto** [comment] 2015-03-11 19:10
Qnap ts-220
QTS v.4.1.3
and yes the files are all online

**Comment by cryzto** [comment] 2015-03-12 06:30
strange thing is it partly downloads...but most its waiting :-(
![12-03-2015 07-18-42](https://cloud.githubusercontent.com/assets/6126067/6613209/9929dd04-c889-11e4-918b-bc450973e833.png)

**Comment by cryzto** [comment] 2015-03-14 20:54
@vuolter problem still persists

**Comment by vuolter** [comment] 2015-03-14 21:09
Re-scheduled for the next week-end. Sorry.

**Comment by cryzto** [comment] 2015-03-15 08:47
Well, then...thnx anyway.

**Comment by cryzto** [comment] 2015-04-01 06:25
Any chance?

**Comment by cryzto** [comment] 2015-04-01 06:26
Any chance to have this solved? Sorry to bother....

**Comment by cryzto** [comment] 2015-04-01 06:41
DAMN!!!
Downloading but not working right again!!! This is so frustrating...
Filename not right:
![filename](https://cloud.githubusercontent.com/assets/6126067/6935786/ef307656-d84a-11e4-8369-9451b9202eb2.png)

**Comment by cryzto** [comment] 2015-04-29 21:57
@vuolter: still having this issue, help...

**Comment by cryzto** [comment] 2015-06-01 13:39
still having issues :-(

**Comment by vuolter** [comment] 2015-06-01 19:26
I think is unfixable in 0.4.9, the issue is in the netwok module... :S

**Comment by Velociraptor85** [comment] 2018-09-26 06:39
@GammaC0de is this the same ? @cryzto is this fixed with the latest commit?

**Closed** 2018-09-26 06:45 UTC
Labels: plugin issue
