### ISSUE TITLE
Error rockfile

### ISSUE THREAD

**Issue by maxking71** [pyload/pyload#2777] opened 2017-03-06 01:04 UTC
Error rockfile

.03.2017 08:50:48WARNINGSSL certificates not found.20405.03.2017 08:50:48INFOFree space: 289.65 GiB20505.03.2017 08:50:48ERRORError importing lightweight server: No module named bjoern20605.03.2017 08:50:48WARNINGYou need to download and compile bjoern, https://github.com/jonashaag/bjoern20705.03.2017 08:50:48WARNINGCopy the boern.so to module/lib folder or use setup.py install20805.03.2017 08:50:48WARNINGOf course you need to be familiar with linux and know how to compile software20905.03.2017 08:50:48INFOStarting builtin webserver: 0.0.0.0:888821005.03.2017 08:50:48INFOActivating Accounts...21105.03.2017 08:50:48INFOActivating Plugins...21205.03.2017 08:50:48INFOpyLoad is up and running21305.03.2017 21:06:37DEBUGRedirected import module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu21405.03.2017 21:06:37ERRORError importing RockfileEu: No module named Plugin21505.03.2017 21:06:37CRITICAL'NoneType' object has no attribute 'RockfileEu'21605.03.2017 21:06:39DEBUGRedirected import module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu21705.03.2017 21:06:39ERRORError importing RockfileEu: No module named Plugin21805.03.2017 21:06:39CRITICAL'NoneType' object has no attribute 'RockfileEu'21905.03.2017 21:06:57DEBUGRedirected import module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu22005.03.2017 21:06:57ERRORError importing RockfileEu: No module named Plugin22105.03.2017 21:06:57CRITICAL'NoneType' object has no attribute 'RockfileEu'22205.03.2017 21:07:03DEBUGRedirected import module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu22305.03.2017 21:07:03ERRORError importing RockfileEu: No module named Plugin22405.03.2017 21:07:03CRITICAL'NoneType' object has no attribute 'RockfileEu'22505.03.2017 21:09:27INFOAdded package dance containing 1 links22605.03.2017 21:09:27DEBUGRedirected import module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu22705.03.2017 21:09:27ERRORError importing RockfileEu: No module named Plugin22805.03.2017 21:09:28DEBUGRedirected import module.plugins.hoster.RockfileEu -> userplugins.hoster.RockfileEu22905.03.2017 21:09:28ERRORError importing RockfileEu: No module named Plugin23005.03.2017 21:09:28CRITICAL'NoneType' object has no attribute 'RockfileEu'

**Comment by GammaC0de** [comment] 2017-03-06 01:22
Duplicate of #2749, please delete your userplugins directory and the update to the latest plugins.

**Comment by GammaC0de** [comment] 2017-03-07 21:52
No response, closing.

**Closed by GammaC0de** 2017-03-07 21:52 UTC
Labels: duplicate, question
