### ISSUE TITLE
'ascii' codec can't encode character u'\xe9'

### ISSUE THREAD

**Issue by zephura** [pyload/pyload#1949] opened 2015-10-04 09:42 UTC
Seen it for UpleaCom
Of course, same issue with other char \xe9, \xe8, \xe0, \xea (respectivly é, è, à, ê)

I don't think a full debug is necessary, but here it comes
TRACEBACK:
```
 Traceback (most recent call last):
  File "/usr/share/pyload/module/PluginThread.py", line 187, in run
    pyfile.plugin.preprocessing(self)
  File "/opt/pyload/userplugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/opt/pyload/userplugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 262, in process
    self.check_info()  #@TODO: Remove in 0.4.10
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 481, in check_info
    self.check_name_size()
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 450, in check_name_size
    self.info.update(self.get_info(self.pyfile.url, self.html))
  File "/opt/pyload/userplugins/internal/SimpleHoster.py", line 191, in get_info
    info['name'] = parse_name(name)
  File "/opt/pyload/userplugins/internal/Plugin.py", line 73, in parse_name
    path  = fixurl(decode(string), unquote=False)
  File "/opt/pyload/userplugins/internal/Plugin.py", line 63, in fixurl
    newurl = html_unescape(newurl.decode('unicode-escape'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 27: ordinal not in range(128)
```
FRAMESTACK:
```
Frame preprocessing in /opt/pyload/userplugins/internal/Base.py at line 201
                        self = <Hoster UpleaCom>
                        args = (<DownloadThread(Thread-2, started daemon 139879132907264)>,)
                      kwargs = {}

Frame _process in /opt/pyload/userplugins/internal/Hoster.py at line 93
                        self = <Hoster UpleaCom>
                      thread = <DownloadThread(Thread-2, started daemon 139879132907264)>

Frame process in /opt/pyload/userplugins/internal/SimpleHoster.py at line 262
                      pyfile = PyFile 624: http:// from uplea website /##/6D4EA10837E679C@UpleaCom
                        self = <Hoster UpleaCom>

Frame check_info in /opt/pyload/userplugins/internal/SimpleHoster.py at line 481
                        self = <Hoster UpleaCom>

Frame check_name_size in /opt/pyload/userplugins/internal/SimpleHoster.py at line 450
                    old_info = {}
                        self = <Hoster UpleaCom>
                     getinfo = True

Frame get_info in /opt/pyload/userplugins/internal/SimpleHoster.py at line 191
                        info = {'name': '6D4EA10837E679C',
 'pattern': {'N': u'03 - Qui veut la peau du sh\xe9rif-Zone-Telechargement.com.avi',
             'S': u'349.77',
             'U': u'Mo'},
 'size': 0,
 'status': 2,
 'url': u'http:// from uplea website /##/6D4EA10837E679C'}
                        attr = None
                         url = u'http:// from uplea website /##/6D4EA10837E679C'
                     pattern = 'HASHSUM_PATTERN'
                       pdict = {'S': u'349.77', 'U': u'Mo'}
                        html = u'\n
=======//  SNIP  //=======
                      online = True
                         cls = <class 'userplugins.hoster.UpleaCom.UpleaCom'>
                        name = u'03 - Qui veut la peau du sh\xe9rif-Zone-Telechargement.com.avi'

Frame parse_name in /opt/pyload/userplugins/internal/Plugin.py at line 73
                      string = u'03 - Qui veut la peau du sh\xe9rif-Zone-Telechargement.com.avi'

Frame fixurl in /opt/pyload/userplugins/internal/Plugin.py at line 63
                     unquote = False
                         url = u'03 - Qui veut la peau du sh\xe9rif-Zone-Telechargement.com.avi'
                      newurl = u'03 - Qui veut la peau du sh\xe9rif-Zone-Telechargement.com.avi'
```
=====//  SNIP  //=====

PYFILE OBJECT DUMP:
```
                       _size = 0
                       abort = False
                      active = False
                       error = "'ascii' codec can't encode character u'\\xe9' in position 27: ordinal not in range(128)"
                          id = 624
                        lock = <_RLock owner=None count=0>
                           m = <module.database.FileDatabase.FileHandler instance at 0x7f3826a70950>
                 maxprogress = 100
                        name = u'http:// from uplea website /##/6D4EA10837E679C'
                       order = 2
                   packageid = 36
                      plugin = <Hoster UpleaCom>
                 pluginclass = <class 'userplugins.hoster.UpleaCom.UpleaCom'>
                pluginmodule = <module 'userplugins.hoster.UpleaCom' from '/opt/pyload/userplugins/hoster/UpleaCom.pyc'>
                  pluginname = u'UpleaCom'
                    progress = 0
                 reconnected = False
                        size = 0
                      status = 8
                  statusname = None
                         url = u'http:// from uplea website /##/6D4EA10837E679C'
                   waitUntil = 0
```

**Comment by Spartanineo** [comment] 2015-10-04 12:18
I have the same On certain files

**Comment by GammaC0de** [comment] 2015-10-04 12:22
sample effected url: http://uplea.com/dl/6D4EA10837E679C

**Comment by honza889** [comment] 2015-10-04 14:12
Problem shoudl be fixed by applying pull request https://github.com/pyload/pyload/pull/1951
Can you please check if it fix it for you? (URL by @GammaC0de already ok for me)

**Comment by zephura** [comment] 2015-10-04 14:25
It allow the download to begin.
Your fix substitute any error by nothing, this means the word "Shérif" will be "Shrif"
the sentence "ça c'est un évènement" will be "c c'est un vnement".
the sentence "große Brötchen" will be "groe Brtchen"
same for any spanish, russian or asian language file

I don't care, as I always rename the files 
thus I thanks honza889!

**Comment by GammaC0de** [comment] 2015-10-04 14:59
I would have wait for @vuolter to take care of this properly.
also I bet https://github.com/pyload/pyload/pull/1951 would not be merged since the update of `PluginManager.py` which is part of the core and the core is not updated in the stable branch

**Comment by damien599901** [comment] 2015-10-04 15:26
same thing for me

**Comment by GammaC0de** [comment] 2015-10-05 02:32
still does not work even after fixpack (3):
```
05.10.2015 04:28:28 WARNING   Download failed: http://uplea.com/dl/6D4EA10837E679C | 'ascii' codec can't encode character u'\xe9' in position 27: ordinal not in range(128)
Traceback (most recent call last):
  File "/DataVolume/opt/share/pyload/module/PluginThread.py", line 193, in run
    pyfile.plugin.preprocessing(self)
  File "/DataVolume/opt/etc/pyload/userplugins/internal/Base.py", line 201, in preprocessing
    return self._process(*args, **kwargs)
  File "/DataVolume/opt/etc/pyload/userplugins/internal/Hoster.py", line 80, in _process
    self.process(self.pyfile)
  File "/DataVolume/opt/etc/pyload/userplugins/internal/SimpleHoster.py", line 262, in process
    self.check_info()  #@TODO: Remove in 0.4.10
  File "/DataVolume/opt/etc/pyload/userplugins/internal/SimpleHoster.py", line 481, in check_info
    self.check_name_size()
  File "/DataVolume/opt/etc/pyload/userplugins/internal/SimpleHoster.py", line 450, in check_name_size
    self.info.update(self.get_info(self.pyfile.url, self.html))
  File "/DataVolume/opt/etc/pyload/userplugins/internal/SimpleHoster.py", line 191, in get_info
    info['name'] = parse_name(name)
  File "/DataVolume/opt/etc/pyload/userplugins/internal/Plugin.py", line 73, in parse_name
    path  = fixurl(decode(string), unquote=False)
  File "/DataVolume/opt/etc/pyload/userplugins/internal/Plugin.py", line 63, in fixurl
    newurl = html_unescape(decode(newurl).decode('unicode-escape'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 27: ordinal not in range(128)
<type 'unicode'>
```

**Comment by honza889** [comment] 2015-10-05 06:08
@GammaC0de you didnt apply fixpack correctly - after #1951 you shouldn't have `decode('unicode-escape')` in `Plugin.py`.

**Comment by zephura** [comment] 2015-10-05 15:21
I'v replaced line 63 by this one :
newurl = html_unescape(newurl.encode('ascii', 'ignore'))

as stated by : https://github.com/pyload/pyload/pull/1951/files?diff=unified

it worked... (not at home, I'll check this in a couple of hour)

**Comment by janpal** [comment] 2015-10-05 19:30
while waiting for resolution you can check the workaround in #1737

**Comment by honza889** [comment] 2015-10-06 07:29
As workaround can be used also #1951 but because it removes non-ascii characters, that PR will be closed.

**Comment by janpal** [comment] 2015-10-06 15:22
btw. why these conversion issues are being classified as plugin issues?  I beleive it is incorrect to decode url from the download name (which is the source of this exception). It looks like core issue.

**Comment by honza889** [comment] 2015-10-06 17:42
+1 It IS core issue.

**Comment by joberreiter** [comment] 2015-10-08 15:19
Should `parse_name()` return the name of the downloaded file (to store on disk)?
If yes,
- please rename it to a unambigious name, as `parse_filename()`, `parse_savename()` for instance
- why not using the logic of `urllib.parse()` to simplify the current version:
```
def parse_name(string):
    path  = fixurl(decode(string), unquote=False)
    url_p = urlparse.urlparse(path.rstrip('/'))
    name  = (url_p.path.split('/')[-1] or
             url_p.query.split('=', 1)[::-1][0].split('&', 1)[0] or
             url_p.netloc.split('.', 1)[0])

    return urllib.unquote(name)
```

**Comment by vuolter** [comment] 2015-10-08 15:43
@joberreiter `parse_name` extracts name from url string, but should not affect a regular name entered as input. Its output is an unicode string. In truth, I think to `parse filename` like the right name for function giving in output a string encoded for disk writing. But It's only a silly feeling. XD

**Comment by joberreiter** [comment] 2015-10-08 15:54
Ok, so 'name' = 'package name'? Has nothing to do with the name of the downloaded file?
What if you use
```
urllib.parse(string).path.split('/')[-1]
```

**Comment by vuolter** [comment] 2015-10-08 16:04
`urllib.parse` is available only for python 3.

**Comment by joberreiter** [comment] 2015-10-08 16:08
> urllib.parse is available only for python 3.

In Python 2 it is called urlparse:
```
from urlparse import urlparse
print urlparse(string).path.rstrip('/').split('/')[-1]
```

**Comment by joberreiter** [comment] 2015-10-08 16:11
Minimal example:
```python
from urlparse import urlparse

def parse_name(string):
    return urlparse(string).path.rstrip('/').split('/')[-1].strip()

print parse_name('http://uplea.com/dl/6D4EA10837E679C')
print parse_name('http://uplea.com/dl/6D4EA10837E679C/')
print parse_name('http://uplea.com/dl/6D4EA10837E679C/dd')
print parse_name('/uplea.com/dl/6D4EA10837E679C/ee.zip')
print parse_name('ee.zip')
print parse_name('ee.zip - Full File (Test)')
print parse_name('Testname / Test')
```

**Comment by vuolter** [comment] 2015-10-08 16:16
...and urlparse is so used in current parse_name.

**Comment by joberreiter** [comment] 2015-10-08 16:20
... you are right, ouch ... too much trees to see the forest.

Then the problem is `fixurl()`, but this could be solved with urljoin(), or am I wrong?

**Comment by vuolter** [comment] 2015-10-08 16:34
The problem is that string (currently commented):

    path  = fixurl(decode(string), unquote=False)

The must be quote before parsed by urlparse, but there are some other troubles with the regex used in Plugin.py fixurl.

**Comment by sschwart** [comment] 2016-01-14 12:43
There is a solution in post #2286 ;)
It works great for me :)

**Comment by Velociraptor85** [comment] 2016-05-27 13:52
@vuolter @GammaC0de pls close is duplicate and already in "main" issue thread linked #2286

**Closed** 2016-05-27 16:25 UTC
Labels: plugin issue

**Comment by efferre79** [comment] 2016-10-13 23:33
Salve,

Siamo stati in un posto molto bello di recente e ci è  piaciuto  così  tanto, penso che sia un luogo fantastico, dai  un’occhiata <http://ivn.shimizuspa.com/wuj>

Cari auguri, FBIO ROSSI

**Comment by efferre79** [comment] 2016-11-09 00:53
Caro! 

Come te la passi?  Ti  ho pensato di recente  e credo di aver trovato  qualcosa di utile  per te, leggi  di più qui <http://handygepu.pcprogroup.com/yt/4>

Saluti, FBIO ROSSI
