### ISSUE TITLE
Some plugins settings are not persistent

### ISSUE THREAD

**Issue by ghost** [pyload/pyload#1157] opened 2015-02-08 09:30 UTC
I noticed that some of the UpdateManger settings are not persistent. They are reset to the default values if you restart pyLoad

```
user@laptop:~/.pyload$ grep -A 7 UpdateMa plugin.conf 
UpdateManager - "UpdateManager":
    bool autorestart : "Automatically restart pyLoad when required" = True
    int interval : "Check interval in hours" = 360
    bool activated : "Activated" = True
    bool nodebugupdate : "Don't check for updates in debug mode" = False
    bool reloadplugins : "Monitor plugins for code changes in debug mode" = True
    pyLoad + plugins;plugins only mode : "Check updates for" = pyLoad + plugins

user@laptop:~/.pyload$ pyLoadCore 
08.02.2015 10:13:11 INFO      Starting pyLoad 0.4.9
08.02.2015 10:13:11 INFO      Using home directory: /home/user/.pyload
08.02.2015 10:13:11 INFO      Activated plugins: Captcha9Kw, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, HotFolder, MovieblogFeed, UnSkipOnFail, UpdateManager, XFileSharingPro
08.02.2015 10:13:15 INFO      UpdateManager: No new pyLoad version available
08.02.2015 10:13:15 INFO      UpdateManager: No plugin updates available

*** Make some changes in Updatemanager settings ***

^C08.02.2015 10:13:58 INFO      shutting down...
08.02.2015 10:13:58 INFO      killed pyLoad from Terminal
user@laptop:~/.pyload$ grep -A 7 UpdateMa plugin.conf 
UpdateManager - "UpdateManager":
    bool autorestart : "Automatically restart pyLoad when required" = False
    int interval : "Check interval in hours" = 360
    bool activated : "Activated" = True
    bool nodebugupdate : "Don't check for updates in debug mode" = True
    bool reloadplugins : "Monitor plugins for code changes in debug mode" = True
    pyLoad + plugins;plugins only mode : "Check updates for" = pyLoad + plugins

user@laptop:~/.pyload$ pyLoadCore 
08.02.2015 10:14:05 INFO      Starting pyLoad 0.4.9
08.02.2015 10:14:05 INFO      Using home directory: /home/user/.pyload
08.02.2015 10:14:06 INFO      Activated plugins: Captcha9Kw, Checksum, ClickAndLoad, ExternalScripts, ExtractArchive, HotFolder, MovieblogFeed, UnSkipOnFail, UpdateManager, XFileSharingPro
08.02.2015 10:14:10 INFO      UpdateManager: No new pyLoad version available
08.02.2015 10:14:10 INFO      UpdateManager: No plugin updates available
^C08.02.2015 10:14:13 INFO      shutting down...
08.02.2015 10:14:13 INFO      killed pyLoad from Terminal

*** Just restart pyLoad ***

user@laptop:~/.pyload$ grep -A 7 UpdateMa plugin.conf 
UpdateManager - "UpdateManager":
    bool autorestart : "Automatically restart pyLoad when required" = True
    int interval : "Check interval in hours" = 360
    bool activated : "Activated" = True
    bool nodebugupdate : "Don't check for updates in debug mode" = False
    bool reloadplugins : "Monitor plugins for code changes in debug mode" = True
    pyLoad + plugins;plugins only mode : "Check updates for" = pyLoad + plugins

user@laptop:~/.pyload$
```

Take a look on "Automatically restart pyLoad when required" and "Don't check for updates in debug mode"

**Comment by kasperj** [comment] 2015-02-09 10:34
This seems to be a general issue, happens with ExtractArchive too https://github.com/pyload/pyload/issues/1122

**Comment by Gutz-Pilz** [comment] 2015-02-09 20:23
yes. i can copy both!

**Comment by wastez** [comment] 2015-02-11 17:26
It also appears on other plugins, so the issue seems to be a generell one.

**Comment by stickell** [comment] 2015-02-11 17:34
Changed the title

**Comment by stickell** [comment] 2015-02-25 17:59
This bug is really strange! 0.4.9 has some years, it's weird that a core bug suddendly reveals so frequently!

**Comment by immenz** [comment] 2015-03-25 19:59
Just made a fresh install on Windows and could reproduce this issue. 
But when I ran pyload directly from git source where I had deactivated updatemanager, there are no problems. Also activating updatemanager temporarily on git instance did not produce the bug. 

So bug seems only to occur on boolean Settings and when updatemanager is used. (So I think the bug is somewhere in updatemanager)

But in addition, with the new ExtractArchive version the option "delete after extraction" isn't a boolean value anymore, so this should calm most of the people that had this issue :)

**Comment by wastez** [comment] 2015-03-26 01:44
No, it´s again not saved...... Also not in the new version, so it doesn´t seem to be just boolean.
Also disabling the updatemanager don´t change something on it.

**Comment by chaosmaker** [comment] 2015-04-01 14:23
Now it seems that even during runtime settings are reset.

**Comment by vuolter** [comment] 2015-04-08 17:49
THE HOLY FIX FINALLY :sob:

**Comment by Gutz-Pilz** [comment] 2015-04-08 17:50
kidding me :+1: :dancers:

**Comment by wastez** [comment] 2015-04-08 17:58
It´s still not stored on my system.... :(

**Comment by Mister-XY** [comment] 2015-04-08 18:57
me too

**Comment by vuolter** [comment] 2015-04-08 20:57
When https://github.com/pyload/updatemanager/pull/25/files will be merged, all should go fine.

**Comment by Mister-XY** [comment] 2015-04-08 20:58
Save it also the option by extractarchive and update manager?

**Comment by vuolter** [comment] 2015-04-08 21:05
Yep.

**Comment by Mister-XY** [comment] 2015-04-10 05:43
No, id did not save in extractarcive and updatemanager. The only new thing i have, is many double namend plugins loks like rehost.o, rehost.to hook.

**Comment by vuolter** [comment] 2015-04-10 09:38
Works on my end. Maybe there're olther plugin conflicts...

**Comment by Mister-XY** [comment] 2015-04-10 10:31
with a fresh installed pyload?

**Comment by wastez** [comment] 2015-04-10 15:30
On my system it´s also not working, sorry.

**Comment by Mister-XY** [comment] 2015-04-12 06:35
I have tested pyload also on a Windows platform and have the same problem, that the setting did not save in updatemanager and Extractarchive.

**Comment by GammaC0de** [comment] 2018-10-07 22:11
Fixed long ago.

**Closed by GammaC0de** 2018-10-07 22:11 UTC
Labels: bug
