### ISSUE TITLE
Click & Load not working when using SSL Webinterface

### ISSUE THREAD

**Issue by milesbenson** [pyload/pyload#2157] opened 2015-11-06 23:11 UTC
Same issue: https://github.com/pyload/pyload/issues/1387

Not sure if this is really fixed as i cant get CNL to work when HTTPS is enabled.

**Comment by GammaC0de** [comment] 2015-11-07 16:34
@milesbenson Click N' Load does not use SSL (nor SSH) for processing requests even if you configure pyLoad webif to use SSL.
Maybe this should have to be implemented in the future but this is how it currently works.

**Comment by milesbenson** [comment] 2015-11-07 20:29
So there is no chance to use CNL when using HTTPS for the interface at the moment?

**Comment by GammaC0de** [comment] 2015-11-07 22:03
If you use HTTPS for the interface, CNL still uses HTTP
If you desire CNL over HTTPS, this s not implemented (not requested I guess)

**Comment by Michi-F** [comment] 2015-11-28 16:02
The bug is fixed, I've tested it a few months ago and also today with a fresh installation of pyload (raspberry pi, debian jessie, pyload-cli). So this can be closed as fixed.

@milesbenson:
check your "ClickNLoad.py".
The file should look like this: https://github.com/pyload/pyload/blob/stable/module/plugins/hooks/ClickNLoad.py
"
class ClickNLoad(Addon):
    __name__    = "ClickNLoad"
    __type__    = "hook"
    __version__ = "0.49"
    __status__  = "testing"
"
If not, maybe the "update manager" of pyload is not working correctly. Restart pyload & check your logs, you should see the following lines:
"
INFO	ADDON UpdateManager: pyLoad is up to date!
INFO	ADDON UpdateManager: All plugins are up to date!
INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666 
"

Try the "Click-And-Load V2"-Button on http://share-links.biz , this worked for me (maybe the button you tried on another website is not working).

Which setup do you use (Windows, Linux, pyload with GUI or pyload-cli) ?
Is the PC where you press the "CNL-Button" the same where pyload is running or are you using a port-forwarding ?

###########################################################
to clear things up:
1) https for the pyload webinterface -> if you activate this, your webinterface is only accessible with https.

2) CNL http request: CNL in general uses http. This can not be changed as the requests are done by scripts on websites where you click the "CNL-Button". So this has nothing to do with pyload.
E.g. the "Click-And-Load V2"-Button trigger a request to "http://localhost:9666/flash/addcrypted2"
@GammaC0de
"Maybe this should have to be implemented in the future" -> not necessary as CNL requests never uses https

3) pyload is listening to CNL request

The issue was (!) that activation of (1)"https for the pyload webinterface" affected also the way how (3) "pyload is listening to CNL request" and therefore the (2) "CNL http request" were rejected (as they were http request, but (3)"pyload is listening to CNL request" expected https requests).

This issue was succesfully fixed with the changes of this commit: https://github.com/pyload/pyload/pull/1405/files

Now activation of (1) doesn't affect (3) anymore, and (3) listens to http even if (1)webinterface uses https.

**Comment by milesbenson** [comment] 2015-11-28 23:00
I use pyload on a Gentoo system without X. And i use port forwarding, as pyload is running on a remote server.

My CNL version is 0.49 but when HTTPS is enabled, CNL through port forwarding is not working anymore.

**Comment by Michi-F** [comment] 2015-11-28 23:01
what about log messages when you restart pyload ?
Can you see "INFO ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666 " somewhere ?

**Comment by milesbenson** [comment] 2015-11-28 23:05
Yes:

29.11.2015 00:07:15 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666

My SSH tunnel:

ssh -L 9666:XXX.XXX.XXX.XXX:8181 -l username -N XXX.XXX.XXX.XXX -p 22000

**Comment by GammaC0de** [comment] 2015-11-28 23:11
Is'nt it possible to connect directly to port 9666 on the remote server without tunnel?

**Comment by milesbenson** [comment] 2015-11-28 23:30
Well i'm on a mac and i dont want to use any other tools then ssh to forward the requests to pyload. And it works perfectly without https enabled.

**Comment by GammaC0de** [comment] 2015-11-28 23:39
Please post debug log of sending a link to pyLoad with HTTPS enabled
Also, describe how exactly do you send links to CNL? (for example I use flashgot plugin for firefox)

**Comment by milesbenson** [comment] 2015-11-28 23:48
I create my SSH tunnel and afterwards i simply click on a CNL button.

Without HTTPS:
29.11.2015 00:45:43 DEBUG     Run Info Fetching for UploadedTo
29.11.2015 00:45:43 INFO      Added package http://blabla.html containing 2 links
29.11.2015 00:45:43 DEBUG     Finished Info Fetching for UploadedTo

With HTTPS enabled nothing happens.
I use Safari without any extension.

**Comment by GammaC0de** [comment] 2015-11-28 23:56
on the server:
1. stop `pyLoad`
2. run `pyLoadCore -d`
3. send a link to CNL
4. post ALL of the debug output

**Comment by GammaC0de** [comment] 2015-11-29 00:19
Also, why are you so concerned of using HTTPS when you are already using a secure tunnel?

**Comment by Michi-F** [comment] 2015-11-29 13:06
@GammaC0de 
"Also, why are you so concerned of using HTTPS when you are already using a secure tunnel?"
Because only CNL is tunneled, but access to the webinterface with the browser is not. At least that's how my setup is ;)

@milesbenson:
in addition to GammaC0de's comment (https://github.com/pyload/pyload/issues/2157#issuecomment-160347496), try the following to debug:
1) enable https on webinterface and run the following command on the server where pyload is running (Gentoo system)
2) run the command on your mac (I think curl is available for OSX, too ?).
3) post both results

Request command:
"
curl -v "http://127.0.0.1:9666/flash/addcrypted2" -H "Origin: http://share-links.biz" -H "Accept-Encoding: gzip, deflate" -H "Accept-Language: en-US,en;q=0.8" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: */*" -H "Connection: keep-alive" --data "passwords=autopostpw&jk=function"%"20f"%"28"%"29"%"7Ba"%"3Dnew"%"20Array"%"28"%"273831"%"27"%"2C"%"273830"%"27"%"2C"%"273032"%"27"%"2C"%"273832"%"27"%"2C"%"273034"%"27"%"2C"%"273733"%"27"%"2C"%"273530"%"27"%"2C"%"273832"%"27"%"29"%"3Bvar"%"20n"%"3D"%"27"%"27"%"3Bfor"%"28var"%"20i"%"3D7"%"3Bi"%"3E"%"3D0"%"3Bi"%"2D"%"2D"%"29n"%"3Dn"%"2Ba"%"5Bi"%"5D"%"2Esplit"%"28"%"27"%"27"%"29"%"2Ereverse"%"28"%"29"%"2Ejoin"%"28"%"27"%"27"%"29"%"2Esplit"%"28"%"27"%"27"%"29"%"2Ereverse"%"28"%"29"%"2Ejoin"%"28"%"27"%"27"%"29"%"2Esplit"%"28"%"27"%"27"%"29"%"2Ereverse"%"28"%"29"%"2Ejoin"%"28"%"27"%"27"%"29"%"3Breturn"%"20n"%"2Esplit"%"28"%"27"%"27"%"29"%"2Ereverse"%"28"%"29"%"2Ejoin"%"28"%"27"%"27"%"29"%"3B"%"7D&crypted=UCNPBTFqFjkAPmtvmhYotcyUqIbsHbh5g"%"2BobagssCh4"%"3D" --compressed
"

This is a http request that simulates a CNL request. The result should be that a package "golem.de" is added to the Collector-Queue in pyload.
If this works on your Gentoo, then the problem is not pyload. If not, it is. :)

This is what it looks like on my raspberrypi (debian jessie) -> response from pyload: success
"root@raspberrypi:/...path....# ./cnlSampleRequest.sh
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9666 (#0)
> POST /flash/addcrypted2 HTTP/1.1
> Host: 127.0.0.1:9666
> Origin: http://share-links.biz
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.8
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
> Content-Type: application/x-www-form-urlencoded
> Accept: */*
> Connection: keep-alive
> Content-Length: 542
>
* upload completely sent off: 542 out of 542 bytes
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Content-Length: 9
< Date: Sun, 29 Nov 2015 12:48:33 GMT
* Server CherryPy/3.1.2 WSGI Server is not blacklisted
< Server: CherryPy/3.1.2 WSGI Server
<
success
* Connection #0 to host 127.0.0.1 left intact
root@raspberrypi:/...path...#
"

**Closed** 2018-01-09 20:22 UTC
Labels: duplicate, plugin issue
