### ISSUE TITLE
Error importing PremiumizeMe: No module named MultiAccount

### ISSUE THREAD

**Issue by sosnet** [pyload/pyload#2376] opened 2016-03-07 12:18 UTC
When I try to add a Premiumize account I get this error in the terminal..
```
07.03.2016 13:12:36 ERROR     Error importing PremiumizeMe: No module named MultiAccount
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/usr/share/pyload/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 148, in updateAccount
    p = self.getAccountPlugin(plugin)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
An error occured while processing the request.
Traceback (most recent call last):
  File "/usr/share/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/usr/share/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/usr/share/pyload/module/web/utils.py", line 113, in _view
    return func(*args, **kwargs)
  File "/usr/share/pyload/module/web/json_app.py", line 276, in add_account
    PYLOAD.updateAccount(type, login, password)
  File "/usr/share/pyload/module/Api.py", line 894, in updateAccount
    self.core.accountManager.updateAccount(plugin, account, password, options)
  File "/usr/share/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 148, in updateAccount
    p = self.getAccountPlugin(plugin)
  File "/usr/share/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable
```
I'm on a raspberry pi with OSMC..
I did a fresh install of pyload-v0.4.9-all.deb, exchanged the UpdateManager.py so that it does updates. During startup I get this error aswell..
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/share/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 52, in periodical
    self.checkPlugins(updates)
  File "/usr/share/pyload/module/plugins/hooks/UpdateManager.py", line 136, in checkPlugins
    "version": float(version)
ValueError: could not convert string to float: 
```
Any solutions?

**Comment by GammaC0de** [comment] 2016-03-07 20:49
`Error importing PremiumizeMe: No module named MultiAccount`
This is duplicate of #2121

As for the second issue, see #2377

**Closed by GammaC0de** 2016-03-07 20:49 UTC
Labels: duplicate, plugin issue
