### ISSUE TITLE
MultiHost file download race condition

### ISSUE THREAD

**Issue by unknow010** [pyload/pyload#3033] opened 2017-11-28 19:26 UTC
In a scenario where the files there you want to download are on more as one hoster (the same files, on different onclick hoster) - if you had load a jdownloder container for example - 
you run in a race condition like problem. 
now it can happen that pyload download the same file from 2 or more different hosts at the same time.

Can you please create a check where you look at begin of a download if file with the exact same name is already in progress?

thank you

**Comment by GammaC0de** [comment] 2017-11-28 20:12
Can you provide the URLs and the name of the MultiHoster?

**Comment by unknow010** [comment] 2017-11-28 20:30
i can give you the dlc file, but maybe better not in public - after i cancel collisions by hand (break one of the donwloads) now there are no download collisions anymore.

**Comment by GammaC0de** [comment] 2017-11-28 20:54
send to nitzo2001 at yahoo dot com.

**Comment by unknow010** [comment] 2017-11-29 19:14
mail is send out, i had enabled this skip feature but it seams not to help in this case

**Comment by GammaC0de** [comment] 2017-11-30 14:21
OK, I will look at it soon.

**Comment by GammaC0de** [comment] 2017-12-04 10:12
Well, this seems to be a duplicate of #2365.

**Comment by GammaC0de** [comment] 2017-12-06 04:58
@unknow010 Can you please replace `userplugins/internal/Hoster.py` with https://gist.github.com/GammaC0de/ea0c0f118e2e9336347ead7c85f51bcb/raw/fcaf6a4133033a4b9a4e9da64db50192b1a7b4c9/Hoster.py and test the DLC file you have sent me?

Because I do not have a premium account and if I test it, it would take forever.

**Closed** 2018-01-21 10:22 UTC
Labels: duplicate, feedback wanted
