### ISSUE TITLE
No configuration possible

### ISSUE THREAD

**Issue by taker218** [pyload/pyload#1976] opened 2015-10-08 08:45 UTC
After the last update from pyload I don't have access to the configuration tab in the webinterface.

here the log (can't attach the file).
Is there a way to enable debug mode without getting to the settings?

08.10.2015 10:38:50	ERROR	Fehler beim importieren von BypassCaptcha: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:50	ERROR	Fehler beim importieren von ExternalScripts: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:50	ERROR	Fehler beim importieren von ExtractArchive: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:50	ERROR	Fehler beim importieren von UpdateManager: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:50	ERROR	Fehler beim importieren von LinkdecrypterComHook: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:50	ERROR	Fehler beim importieren von ImageTyperz: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:50	ERROR	Fehler beim importieren von ClickNLoad: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:50	ERROR	Fehler beim importieren von UnSkipOnFail: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:51	ERROR	Fehler beim importieren von XFileSharingPro: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:51	ERROR	Fehler beim importieren von UserAgentSwitcher: invalid syntax (Plugin.py, line 273)
08.10.2015 10:38:51	INFO	Aktivierte Plugins:
08.10.2015 10:38:51	INFO	Deaktivierte Plugins: AlldebridComHook, AndroidPhoneNotify, AntiStandby, AntiVirus, Captcha9Kw, CaptchaBrotherhood, Checksum, ClickAndLoad, DeathByCaptcha, DebridItaliaComHook, DeleteFinished, DownloadScheduler, EasybytezComHook, ExpertDecoders, FastixRuHook, FreeWayMeHook, HighWayMe, HighWayMeHook, HotFolder, IRCInterface, JustPremium, LinksnappyComHook, LogMarker, MegaDebridEuHook, MegaRapidoNetHook, MergeFiles, MultiHome, MultihostersComHook, MultishareCzHook, MyfastfileComHook, NoPremiumPlHook, OverLoadMeHook, PremiumToHook, PremiumizeMeHook, PutdriveComHook, RPNetBizHook, RapideoPlHook, RealdebridComHook, RehostToHook, RestartFailed, SimplyPremiumComHook, SimplydebridComHook, SkipRev, SmoozedComHook, TransmissionRPC, WindowsPhoneNotify, XMPPInterface, ZeveraComHook
08.10.2015 10:38:51	INFO	Downloadzeit: True
08.10.2015 10:38:51	INFO	Starte ThriftBackend: 0.0.0.0:7227
08.10.2015 10:38:51	INFO	Starting builtin webserver: 0.0.0.0:8000
08.10.2015 10:38:51	INFO	Free space: 2.14 TiB
08.10.2015 10:38:51	INFO	Activating Accounts...
08.10.2015 10:38:51	ERROR	Error importing ShareonlineBiz: invalid syntax (Plugin.py, line 273)

**Comment by joberreiter** [comment] 2015-10-08 08:55
Just pull the stable branch and/or delete "userplugins/internal/Plugin.py", this issue is already been fixed (duplicate of #1972)

> Is there a way to enable debug mode without getting to the settings?

Yes, just edit the file pyload.conf in your configuration folder and look for
```
general - "General":
        [...]
        bool debug_mode : "Debug Mode" = True
        [...]
```

**Closed** 2015-10-08 09:11 UTC
Labels: duplicate, issue not reproduced
