### ISSUE TITLE
Alldebrid.com login handshake failure

### ISSUE THREAD

**Issue by fey0** [pyload/pyload#2733] opened 2017-02-20 19:30 UTC
Hi,

trying to use the alldebrid plugin fails with the following log message:

63	20.02.2017 20:27:29	INFO	ACCOUNT AlldebridCom: Relogin user `ere*******`...
64	20.02.2017 20:27:29	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | redirect=True | cookies=True | get={'action': 'info_user', 'login': 'ere*******', 'pw': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
65	20.02.2017 20:27:29	ERROR	ACCOUNT AlldebridCom: Could not login user `ere*******` | Login handshake has failed

**Comment by GammaC0de** [comment] 2017-02-20 21:00
What plugin version are you using?

Please provide full log.

**Comment by fey0** [comment] 2017-02-20 21:27
The account plugin is 0.31. Its a freshly installed pyload.

32	20.02.2017 20:26:37	INFO	Starting pyLoad 0.4.9
33	20.02.2017 20:26:37	INFO	Using home directory: /home/feyo/.pyload
34	20.02.2017 20:26:37	DEBUG	Remote activated: True
35	20.02.2017 20:26:38	DEBUG	created index of plugins
36	20.02.2017 20:26:38	INFO	Activated plugins: ClickNLoad, EventMapper, ExternalScripts, ExtractArchive, MergeFiles, UnSkipOnFail, UpdateManager, UserAgentSwitcher, XFileSharing
37	20.02.2017 20:26:38	INFO	Deactivate plugins: AndroidPhoneNotify, AntiStandby, AntiVirus, BypassCaptcha, Captcha9Kw, CaptchaBrotherhood, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DownloadScheduler, ExpertDecoders, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, WindowsPhoneNotify, XMPP
38	20.02.2017 20:26:38	INFO	Downloadtime: True
39	20.02.2017 20:26:38	INFO	Starting ThriftBackend: 0.0.0.0:7227
40	20.02.2017 20:26:38	INFO	Starting threaded webserver: 0.0.0.0:8000
41	20.02.2017 20:26:38	INFO	free space: 135.95 GiB
42	20.02.2017 20:26:38	INFO	Activating Accounts...
43	20.02.2017 20:26:38	INFO	ACCOUNT AlldebridCom: Adding user `ere*******`...
44	20.02.2017 20:26:38	DEBUG	ACCOUNT AlldebridCom: Reached login timeout for user `ere*******`
45	20.02.2017 20:26:38	INFO	ACCOUNT AlldebridCom: Login user `ere*******`...
46	20.02.2017 20:26:38	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | redirect=True | cookies=True | get={'action': 'info_user', 'login': 'ere*******', 'pw': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
47	20.02.2017 20:26:39	ERROR	ACCOUNT AlldebridCom: Could not login user `ere*******` | Login handshake has failed
48	20.02.2017 20:26:39	INFO	Activating Plugins...
49	20.02.2017 20:26:39	DEBUG	ADDON ExternalScripts: No script found under folder `pyload_start`
50	20.02.2017 20:26:39	DEBUG	ADDON ExtractArchive: Found UnRar 5.30 | Found UnZip 2.7.12 | Found UnTar 2.7.12
51	20.02.2017 20:26:39	INFO	ADDON XFileSharing: Auto-discover new hosters
52	20.02.2017 20:26:39	DEBUG	ADDON XFileSharing: Pattern for hosters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:180upload\.com|cramit\.in|easybytez\.com|exashare\.com|filejoker\.net|fileom\.com|filerio\.com|hugefiles\.net|junocloud\.me|movreel\.com|nosupload\.com|novafile\.com|rapidfileshare\.net|rarefile\.net|safesharing\.eu|secureupload\.eu|streamcloud\.eu|tusfiles\.net|uploadrocket\.net|uptobox\.com|vidplay\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:embed-)?\w{12}(?:\W|$)
53	20.02.2017 20:26:39	INFO	ADDON XFileSharing: Auto-discover new crypters
54	20.02.2017 20:26:39	DEBUG	ADDON XFileSharing: Pattern for crypters: (?:https?://(?:www\.)?)(?!(?:www\.)?(?:easybytez\.com|tusfiles\.net))(?P(?:[\d.]+|[\w\-^_]{3,63}(?:\.[a-zA-Z]{2,})+)(?:\:\d+)?)/(?:user|folder)s?/\w+
55	20.02.2017 20:26:39	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
56	20.02.2017 20:26:39	INFO	pyLoad is up and running
57	20.02.2017 20:26:39	INFO	ADDON UpdateManager: pyLoad is up to date!
58	20.02.2017 20:26:39	DEBUG	ADDON UpdateManager: LOAD URL http://updatemanager-spyload.rhcloud.com | redirect=True | cookies=True | get={'v': '0.4.9'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
59	20.02.2017 20:26:39	DEBUG	ADDON UpdateManager: Requested deletion of plugins: [(u'accounts', u'BayfilesCom'), (u'accounts', u'BillionuploadsCom'), (u'accounts', u'BitshareCom'), (u'accounts', u'CyberlockerCh'), (u'accounts', u'DdlstorageCom'), (u'accounts', u'EgoFilesCom'), (u'accounts', u'File4safeCom'), (u'accounts', u'FileParadoxIn'), (u'accounts', u'HotfileCom'), (u'accounts', u'Keep2shareCc'), (u'accounts', u'LetitbitNet'), (u'accounts', u'LinestorageCom'), (u'accounts', u'LomafileCom'), (u'accounts', u'MegaDebrid'), (u'accounts', u'MultiDebridCom'), (u'accounts', u'NetloadIn'), (u'accounts', u'NowVideoAt'), (u'accounts', u'Premium4Me'), (u'accounts', u'RapidshareCom'), (u'accounts', u'ReloadCc'), (u'accounts', u'RyushareCom'), (u'accounts', u'ShareRapidCom'), (u'accounts', u'StahnuTo'), (u'accounts', u'UnrestrictLi'), (u'accounts', u'UploadableCh'), (u'accounts', u'UploadingCom'), (u'accounts', u'Vipleech4uCom'), (u'accounts', u'WarserverCz'), (u'accounts', u'XFileSharingPro'), (u'captcha', u'OCR'), (u'captcha', u'captcha'), (u'container', u'DLC_25'), (u'container', u'DLC_26'), (u'container', u'DLC_27'), (u'container', u'LinkList'), (u'crypter', u'C1neonCom'), (u'crypter', u'DailymotionBatch'), (u'crypter', u'DontKnowMe'), (u'crypter', u'DownloadVimeoCom'), (u'crypter', u'Go4Up'), (u'crypter', u'HotfileFolderCom'), (u'crypter', u'ImgurComAlbum'), (u'crypter', u'JunocloudMeFolder'), (u'crypter', u'Movie2kTo'), (u'crypter', u'OneKhDe'), (u'crypter', u'RapidfileshareNetFolder'), (u'crypter', u'ShareRapidComFolder'), (u'crypter', u'UploadableChFolder'), (u'crypter', u'XFileSharingProFolder'), (u'crypter', u'YoutubeBatch'), (u'hooks', u'AlldebridCom'), (u'hooks', u'AlldebridComHook'), (u'hooks', u'Captcha9kw'), (u'hooks', u'CaptchaTrader'), (u'hooks', u'ClickAndLoad'), (u'hooks', u'DebridItaliaCom'), (u'hooks', u'DebridItaliaComHook'), (u'hooks', u'EasybytezCom'), (u'hooks', u'EasybytezComHook'), (u'hooks', u'Ev0InFetcher'), (u'hooks', u'FastixRu'), (u'hooks', u'FastixRuHook'), (u'hooks', u'freeWayMe'), (u'hooks', u'freeWayMeHook'), (u'hooks', u'HighWayMe'), (u'hooks', u'HighWayMeHook'), (u'hooks', u'IRCInterface'), (u'hooks', u'LinkdecrypterCom'), (u'hooks', u'LinksnappyCom'), (u'hooks', u'LinksnappyComHook'), (u'hooks', u'MegaDebrid'), (u'hooks', u'MegaDebridEu'), (u'hooks', u'MegaDebridEuHook'), (u'hooks', u'MegaRapidoNet'), (u'hooks', u'MegaRapidoNetHook'), (u'hooks', u'MultiDebridCom'), (u'hooks', u'MultihostersCom'), (u'hooks', u'MultihostersComHook'), (u'hooks', u'MultishareCz'), (u'hooks', u'MultishareCzHook'), (u'hooks', u'MyfastfileCom'), (u'hooks', u'MyfastfileComHook'), (u'hooks', u'NoPremiumPl'), (u'hooks', u'NoPremiumPlHook'), (u'hooks', u'OverLoadMe'), (u'hooks', u'OverLoadMeHook'), (u'hooks', u'Premium4Me'), (u'hooks', u'PremiumTo'), (u'hooks', u'PremiumToHook'), (u'hooks', u'PremiumizeMe'), (u'hooks', u'PremiumizeMeHook'), (u'hooks', u'PutdriveCom'), (u'hooks', u'PutdriveComHook'), (u'hooks', u'RPNetBiz'), (u'hooks', u'RPNetBizHook'), (u'hooks', u'RapideoPl'), (u'hooks', u'RapideoPlHook'), (u'hooks', u'RealdebridCom'), (u'hooks', u'RealdebridComHook'), (u'hooks', u'RehostTo'), (u'hooks', u'RehostToHook'), (u'hooks', u'ReloadCc'), (u'hooks', u'RestartSlow'), (u'hooks', u'SimplyPremiumCom'), (u'hooks', u'SimplyPremiumComHook'), (u'hooks', u'SimplydebridCom'), (u'hooks', u'SimplydebridComHook'), (u'hooks', u'SmoozedCom'), (u'hooks', u'SmoozedComHook'), (u'hooks', u'UnrestrictLi'), (u'hooks', u'UnrestrictLiHook'), (u'hooks', u'Vipleech4uCom'), (u'hooks', u'WindowsPhoneToastNotify'), (u'hooks', u'XFileSharingPro'), (u'hooks', u'XMPPInterface'), (u'hooks', u'ZeveraCom'), (u'hooks', u'ZeveraComHook'), (u'hoster', u'File4safeCom'), (u'hoster', u'FileParadoxIn'), (u'hoster', u'Keep2shareCC'), (u'hoster', u'Keep2shareCc'), (u'hoster', u'MegaDebrid'), (u'hoster', u'MegaNz'), (u'hoster', u'MultiDebridCom'), (u'hoster', u'NowDownloadEu'), (u'hoster', u'NowVideoAt'), (u'hoster', u'PandaPlaNet'), (u'hoster', u'PandaPlanet'), (u'hoster', u'Premium4Me'), (u'hoster', u'PutlockerCom'), (u'hoster', u'RapidshareCom'), (u'hoster', u'ReloadCc'), (u'hoster', u'SendmywayCom'), (u'hoster', u'Share4webCom'), (u'hoster', u'ShareRapidCom'), (u'hoster', u'Solidfiles'), (u'hoster', u'UploadableCh'), (u'hoster', u'Vipleech4uCom'), (u'hoster', u'XFileSharingPro'), (u'internal', u'AbstractExtractor'), (u'internal', u'AdYouLike'), (u'internal', u'AdsCaptcha'), (u'internal', u'Hook'), (u'internal', u'MultiHook'), (u'internal', u'ReCaptcha'), (u'internal', u'SimpleDereferer'), (u'internal', u'SolveMedia'), (u'internal', u'XFSPAccount'), (u'internal', u'XFSPCrypter'), (u'internal', u'XFSPHoster'), (u'internal', u'utils')]
60	20.02.2017 20:26:39	INFO	ADDON UpdateManager: All plugins are up to date!
61	20.02.2017 20:26:45	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
62	20.02.2017 20:27:29	INFO	ACCOUNT AlldebridCom: Updating account info for user `ere*******`...
63	20.02.2017 20:27:29	INFO	ACCOUNT AlldebridCom: Relogin user `ere*******`...
64	20.02.2017 20:27:29	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | redirect=True | cookies=True | get={'action': 'info_user', 'login': 'ere*******', 'pw': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
65	20.02.2017 20:27:29	ERROR	ACCOUNT AlldebridCom: Could not login user `ere*******` | Login handshake has failed

**Comment by GammaC0de** [comment] 2017-02-20 21:38
Account information is needed for testing, please send account user and password to nitzo2001 at yahoo dot com.

**Comment by fey0** [comment] 2017-02-20 21:50
It is possible to create a 7day trial account that works on the alldebrid.com website.

**Comment by GammaC0de** [comment] 2017-02-20 23:20
Plugin updated, please retry now.

**Comment by fey0** [comment] 2017-02-20 23:30
No seeming change. 

175	21.02.2017 00:28:46	INFO	ACCOUNT AlldebridCom: Relogin user `ere*******`...
176	21.02.2017 00:28:46	DEBUG	ACCOUNT AlldebridCom: LOAD URL https://www.alldebrid.com/api.php | redirect=True | cookies=True | get={'action': 'info_user', 'login': 'ere*******', 'pw': '**********'} | req=None | decode=True | multipart=False | post={} | ref=True | just_header=False
177	21.02.2017 00:28:47	ERROR	ACCOUNT AlldebridCom: Could not login user `ere*******` | Login handshake has failed

**Comment by GammaC0de** [comment] 2017-02-20 23:32
Plugin version?

**Comment by fey0** [comment] 2017-02-20 23:34
The version you just uploaded. 0.32.

**Comment by GammaC0de** [comment] 2017-02-20 23:44
Well, it works fine here with the free account...

Restart pyload and then send full log again (please surround the log with triple quotes - \`\`\` so it will display nicly)

**Comment by fey0** [comment] 2017-02-21 00:48
In console I got this extra information regarding the handshake fail:

```Traceback (most recent call last):
  File "./pyLoadCore.py", line 667, in <module>
    main()
  File "./pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "./pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/home/feyo/.pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/home/feyo/.pyload/module/plugins/AccountManager.py", line 176, in getAccountInfos
    data[p.__name__] = p.getAllAccounts(force)
  File "/home/feyo/.pyload/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/feyo/.pyload/module/plugins/internal/Account.py", line 282, in getAllAccounts
    self.init_accounts()  #@TODO: Recheck in 0.4.10
  File "/home/feyo/.pyload/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/feyo/.pyload/module/plugins/internal/Account.py", line 268, in init_accounts
    self.add(user, info['password'], info['options'])
  File "/home/feyo/.pyload/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/feyo/.pyload/module/plugins/internal/Account.py", line 316, in add
    result = u['plugin'].choose(user)
  File "/home/feyo/.pyload/module/plugins/internal/misc.py", line 234, in new
    return fn(*args, **kwargs)
  File "/home/feyo/.pyload/module/plugins/internal/Account.py", line 430, in choose
    self.relogin()
  File "/home/feyo/.pyload/module/plugins/internal/Account.py", line 182, in relogin
    return self.login()
  File "/home/feyo/.pyload/module/plugins/internal/Account.py", line 121, in login
    self.signin(self.user, self.info['login']['password'], self.info['data'])
  File "/home/feyo/.pyload/module/plugins/accounts/AlldebridCom.py", line 55, in signin
    self.fail_login()
  File "/home/feyo/.pyload/module/plugins/internal/Account.py", line 446, in fail_login
    return self.fail(msg)
  File "/home/feyo/.pyload/module/plugins/internal/Plugin.py", line 167, in fail
    raise Fail(encode(msg))  #@TODO: Remove `encode` in 0.4.10
Fail: Login handshake has failed ```

**Comment by GammaC0de** [comment] 2017-02-21 13:08
Again, it works fine here, I cannot reproduce this issue.
If you are not willing to send your user and password (you can set to a temporary password if you like), please try to open a free account and try with it.

**Comment by GammaC0de** [comment] 2017-02-22 20:49
Have you tried with another account?

**Comment by damien599901** [comment] 2017-02-24 14:27
works with my account without issue. try to stop and restart pyload

**Comment by Velociraptor85** [comment] 2017-02-25 17:17
@fey0 did the restart work ? which python version are you using?

**Comment by fey0** [comment] 2017-02-25 17:21
@Velociraptor85  no, it did not. I gave up. Using a different solution. I was using 2.7 i think.

**Comment by Velociraptor85** [comment] 2017-02-25 17:31
@fey I will close this issue since it cant be reproduced and you are not using it 👍

**Closed by Velociraptor85** 2017-02-25 17:31 UTC
Labels: plugin issue
