### ISSUE TITLE
Issue with Downloads from share-online

### ISSUE THREAD

**Issue by vistalba** [pyload/pyload#3040] opened 2017-12-03 18:06 UTC
Hi together

Having issues to download files from share-online with premium account (valid). Account is working on other applications or in webbrowser:

```94	03.12.2017 18:01:12	INFO	HOSTER ShareonlineBiz[417]: Link status: online
95	03.12.2017 18:01:12	INFO	HOSTER ShareonlineBiz[417]: Processing url: http://www.share-online.biz/dl/AABBCCDDEEFF
96	03.12.2017 18:01:12	INFO	HOSTER ShareonlineBiz[417]: Looking for direct download link...
97	03.12.2017 18:01:12	INFO	HOSTER ShareonlineBiz[417]: Direct download link not found
98	03.12.2017 18:01:12	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `123*******`...
99	03.12.2017 18:01:12	INFO	HOSTER ShareonlineBiz[417]: Filesize: 307200 KiB | Traffic left for user `123*******`: 71638
71630000 KiB
100	03.12.2017 18:01:12	INFO	HOSTER ShareonlineBiz[417]: Processing as premium download...
101	03.12.2017 18:01:12	INFO	ACCOUNT ShareonlineBiz: Grabbing account info for user `123*******`...
102	03.12.2017 18:01:13	INFO	HOSTER ShareonlineBiz[417]: Downloading file...
103	03.12.2017 18:01:13	INFO	HOSTER ShareonlineBiz[417]: File saved
104	03.12.2017 18:01:13	INFO	HOSTER ShareonlineBiz[417]: Checking download...
105	03.12.2017 18:01:13	INFO	HOSTER ShareonlineBiz[417]: File is OK
106	03.12.2017 18:01:13	INFO	HOSTER ShareonlineBiz[417]: Waiting 5 minutes...
```

Log file says... file is downloaded. Any file is 14KB and if I take a look on it ... it is a Webpage :(

Any ideas how to solve this?

PyLoad 2.7.12 on Docker Container from here: https://hub.docker.com/r/writl/pyload/

**Comment by GammaC0de** [comment] 2017-12-03 19:52
Duplicate of https://github.com/pyload/pyload/issues/3035

**Closed by GammaC0de** 2017-12-03 19:52 UTC
Labels: bug, duplicate
