### ISSUE TITLE
[easybytez] - encode problem

### ISSUE THREAD

**Issue by erse80** [pyload/pyload#2119] opened 2015-10-26 20:41 UTC
Hi 

i have this error any solutions?

26.10.2015 21:39:26 WARNING   Download failed: http://www.easybytez.com/0fq54m9ca5a6 | 'ascii' codec can't encode character u'\xf9' in position 27: ordinal not in range(128)

**Comment by GammaC0de** [comment] 2015-10-26 23:13
duplicate of #1949

**Closed** 2015-10-27 17:19 UTC
Labels: duplicate
