### ISSUE TITLE
share-links.biz C'n'L v2 isn't recognized

### ISSUE THREAD

**Issue by gr0ebi** [pyload/pyload#2213] opened 2015-12-23 15:40 UTC
Hi again,
today I tried to use a C'n'L v2 Button from Share-Links.biz, but the Button is saying that I should start JDL.
When the Button is "warming up", I get incomming connections on pyload:

``` bash
23.12.2015 16:10:01 INFO      ADDON UpdateManager: All plugins are up to date!
23.12.2015 16:10:07 INFO      ADDON RestartFailed: Restarting all failed downloads...
23.12.2015 16:10:07 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9667
23.12.2015 16:11:13 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:20774
23.12.2015 16:11:13 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:20776
```

But the Button on share-links.biz won't be clickable.
I also tried to open the share-links.biz link directly in pyload, which sent me to https://github.com/pyload/pyload/issues/2091
The used link had no "link list" included, so you have to use C'n'L to download the content.
Is share-links broken or the C'n'L recognition in pyload?

**Comment by GammaC0de** [comment] 2015-12-23 17:37
URL?

**Comment by gr0ebi** [comment] 2015-12-23 18:54
like this http://share-links.biz/_11q2cmnghea23

**Comment by Velociraptor85** [comment] 2015-12-23 19:31
yap doesnt work on my end either ... but i did add some links via CnL today already

**Comment by gr0ebi** [comment] 2015-12-23 19:49
> yap doesnt work on my end either ... but i did add some links via CnL today already 
> Edit: looks like the button on sahre-links is some kind of flash?

other CnL are also working for me
Yes its Flash, but that shouldn't be the problem since it's connecting to pyload?!

**Comment by gr0ebi** [comment] 2015-12-24 01:41
It looks like it is a share-links.biz problem. I did test it with jdownloader on my laptop and it's also not working. Other CNL-Links are detected by JDL

**Comment by GammaC0de** [comment] 2015-12-27 19:31
Hi,
After a little research I can see those links are encrypted `CnL` links.
For the decryption, `pyLoad` needs a `Javascript` engine to be installed.
I have successfully managed to load those lins into `pyLoad` on linux.
On Windows I could not make the `Javascript` engine to run an so, `CnL` failed to load the links.
My guess is you are using windows and this is maybe why `JDownloader` failed too.

Maybe @vuolter can help on how to install `Javascript` engine on windows.

**Comment by gr0ebi** [comment] 2015-12-27 20:15
> On Windows I could not make the Javascript engine to run an so, CnL failed to load the links.
> My guess is you are using windows and this is maybe why JDownloader failed too.

Nope, pyload is running on debian 7 with JS engine "Rhino 1.7 release 3 2012 02 13".
The CNL-Link was clicked on a Windows 7 with portproxy to pyload.

**Comment by GammaC0de** [comment] 2015-12-27 20:19
@gr0ebi Please run `pyLoadCore -d`, retry and then send the log

**Comment by gr0ebi** [comment] 2015-12-27 20:22
just like my first post:
```bash
27.12.2015 21:20:23 INFO      ADDON UpdateManager: All plugins are up to date!
27.12.2015 21:20:29 INFO      ADDON RestartFailed: Restarting all failed downloads...
27.12.2015 21:20:29 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9667
27.12.2015 21:20:53 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:32397
27.12.2015 21:20:54 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:32399
```

**Comment by GammaC0de** [comment] 2015-12-27 20:23
Is this the log from the console or from log.txt file?

**Comment by gr0ebi** [comment] 2015-12-27 20:25
console

**Comment by gr0ebi** [comment] 2015-12-27 20:32
maybe this is useful:

```bash
root@xyz:/opt/pyload# tcpflow -p -c -i eth0 port 9667
tcpflow[9757]: listening on eth0
010.000.000.107.32720-010.000.000.252.09667: GET /crossdomain.xml HTTP/1.1
Host: localhost:9666
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
X-Requested-With: ShockwaveFlash/20.0.0.267
Accept: */*
Referer: http://share-links.biz/_11q2cmnghea23
Accept-Encoding: gzip, deflate, sdch
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4


010.000.000.252.09667-010.000.000.107.32720: HTTP/1.1 403 Forbidden
Content-Type: text/html; charset=UTF-8
content-encoding: gzip
Content-Length: 363
Date: Sun, 27 Dec 2015 20:28:55 GMT
Server: CherryPy/3.1.2 WSGI Server

..v...Z...4..)....K...=D. .....g.rAS...N.V....$I<.U.-..%h.3.=.......2...%....9U.L...j..|.gD...+.........~=gg.....6.f...T...."(...6.`.......7.O....%....Tj.N'........fbP...Z.M.H..^..T..].>).m(.N.............\[......
010.000.000.252.09667-010.000.000.107.32712: HTTP/1.1 408 Request Timeout
Content-Length: 0
Content-Type: text/plain


010.000.000.252.09667-010.000.000.107.32711: HTTP/1.1 408 Request Timeout
Content-Length: 0
Content-Type: text/plain


010.000.000.252.09667-010.000.000.107.32720: HTTP/1.1 408 Request Timeout
Content-Length: 0
Content-Type: text/plain


010.000.000.252.09667-010.000.000.107.32722: HTTP/1.1 408 Request Timeout
Content-Length: 0
Content-Type: text/plain

```
thats the complete output

**Comment by GammaC0de** [comment] 2015-12-27 20:40
1) Can you try on pure Linux GUI without portproxy?
2) Can you add this line
```python
 print "Got request for CnL"
```
to [cnl_app.py#L72](https://github.com/pyload/pyload/blob/stable/module/web/cnl_app.py#L72) and  then try?

**Comment by gr0ebi** [comment] 2015-12-27 20:43
I only got headless debian servers or Windows 7 Clients atm. I can setup 1 VM tommorow with a GUI

**Comment by GammaC0de** [comment] 2015-12-27 20:44
Ok, and what about 2?

**Comment by gr0ebi** [comment] 2015-12-27 20:46
Sry, I thought 1 is needed for 2 :-)
I will check later, got to go now
thanks in advance!

**Comment by GammaC0de** [comment] 2015-12-27 20:46
:+1:

**Comment by gr0ebi** [comment] 2015-12-28 16:41
> 2) Can you add this line
> 
>  print "Got request for CnL"
> to cnl_app.py#L72 and then try?

I did add this line but the log didnt change anything.
If I open a already working CNL Link, I get "Got request for CnL" in log

**Comment by J-Ha** [comment] 2016-01-09 10:41
Replace in 
pyload/module/web/cnl_app.py line 4

or request.environ.get('HTTP_HOST','0') == '127.0.0.1:9666' :

With:
or request.environ.get('HTTP_HOST','0') == '127.0.0.1:9666' \
 or request.environ.get('HTTP_HOST','0') == 'localhost:9666':

share-links.biz does the magic with localhost instead 127.0.0.1

**Comment by gr0ebi** [comment] 2016-01-14 02:50
> Replace in 
> pyload/module/web/cnl_app.py line 4
> 
> or request.environ.get('HTTP_HOST','0') == '127.0.0.1:9666' :
> 
> With:
> or request.environ.get('HTTP_HOST','0') == '127.0.0.1:9666' \
> or request.environ.get('HTTP_HOST','0') == 'localhost:9666':
> 
> share-links.biz does the magic with localhost instead 127.0.0.1

doesn't work for me

**Comment by gr0ebi** [comment] 2016-01-16 04:39
Today i tried another CnL that throw me this in debug mode:

```bash
16.01.2016 05:33:00 INFO      ADDON UpdateManager: All plugins are up to date!
16.01.2016 05:33:01 INFO      ADDON RestartFailed: Restarting all failed downloads...
16.01.2016 05:33:05 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9667
16.01.2016 05:33:33 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:45625
16.01.2016 05:33:33 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:45626
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
  File "/opt/pyload/module/web/cnl_app.py", line 72, in addcrypted2
    package = request.forms.get("source", None)
  File "/opt/pyload/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/opt/pyload/module/lib/bottle.py", line 928, in forms
    for name, item in self.POST.iterallitems():
  File "/opt/pyload/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/opt/pyload/module/lib/bottle.py", line 1018, in POST
    fb = self.body
  File "/opt/pyload/module/lib/bottle.py", line 999, in body
    self._body.seek(0)
  File "/opt/pyload/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
timeout: timed out
An error occured while processing the request.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
  File "/opt/pyload/module/web/cnl_app.py", line 72, in addcrypted2
    package = request.forms.get("source", None)
  File "/opt/pyload/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/opt/pyload/module/lib/bottle.py", line 928, in forms
    for name, item in self.POST.iterallitems():
  File "/opt/pyload/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/opt/pyload/module/lib/bottle.py", line 1018, in POST
    fb = self.body
  File "/opt/pyload/module/lib/bottle.py", line 999, in body
    self._body.seek(0)
  File "/opt/pyload/module/lib/bottle.py", line 152, in __get__
    if key not in storage: storage[key] = self.getter(obj)
timeout: timed out
```

maybe it can help, I used a fresh git clone with a fresh ```userplugins``` folder

**Comment by gr0ebi** [comment] 2016-03-11 10:28
any updates on this? can I provide anything to help?

**Comment by Velociraptor85** [comment] 2016-03-12 11:24
checked your link from above and found that after allowing flash and waiting for a Second it showed me add links to jdwonloader and with a clicked it sent it to pyload also I am usind more or less the same config as you w7 client + port redirect to debian + pyload

**Comment by GammaC0de** [comment] 2016-03-12 12:02
@gr0ebi 
- Open ssh shell
- Start `tcpdump -w dump.pcap`
- Send link to `ClickNLoad`
- Stop `tcpdump` by pressing `ctrl-c`
- Post the file `dump.pcap` here.

Also the output of `netstat -anp` would help

**Comment by gr0ebi** [comment] 2016-03-13 10:48
I used ```tcpdump -n dst port 9667 -w /tmp/dump.pcap```
stored both files in the zip
[cnl.zip](https://github.com/pyload/pyload/files/170914/cnl.zip)
thanks for response

**Comment by GammaC0de** [comment] 2016-03-13 14:20
@gr0ebi Haven't chance to check this yet but limiting the capture to `dst port 9667` might exclude valuable information..

**Comment by gr0ebi** [comment] 2016-03-13 20:15
@GammaC0de I can do that, but there is a lot of traffic on that server

**Comment by GammaC0de** [comment] 2016-03-14 00:42
@gr0ebi What command excatly did you used for portproxy?

**Comment by gr0ebi** [comment] 2016-03-14 00:48
@GammaC0de should be this one
```netsh interface portproxy add v4tov4 listenport=9666 connectaddress=10.0.0.252 connectport=9667 listenaddress=127.0.0.1```

**Comment by gr0ebi** [comment] 2016-03-14 15:38
> @gr0ebi Haven't chance to check this yet but limiting the capture to dst port 9667 might exclude valuable information..

do you still want this pcap?

**Comment by GammaC0de** [comment] 2016-03-14 15:43
Don't think so
I will try to setup an environment like yours and see what happens 

 ‏

**Comment by GammaC0de** [comment] 2016-03-14 21:06
http://share-links.biz/_11q2cmnghea23 DLC worked fine with portproxy.
the portproxy command was:
netsh interface portproxy add v4tov4 listenport=9666 connectaddress=10.0.0.252 connectport=**9666** listenaddress=127.0.0.1
and not as you mentioned above

**Comment by gr0ebi** [comment] 2016-03-14 22:06
so I changed the connectport for the ClickNLoad Plugin to 9666, deleted the old portproxy, rebooted, inserted the new portproxy, rebooted again and still got the same problems:
```bash 
586	14.03.2016 22:35:05	INFO	ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
587	14.03.2016 22:45:02	INFO	ADDON RestartFailed: Restarting all failed downloads...
588	14.03.2016 22:55:03	INFO	ADDON RestartFailed: Restarting all failed downloads...
589	14.03.2016 22:58:52	DEBUG	ADDON ClickNLoad: Connection from 10.0.0.107:1083
590	14.03.2016 22:58:52	DEBUG	ADDON ClickNLoad: Connection from 10.0.0.107:1085
```
thats the complete log

**Comment by GammaC0de** [comment] 2016-03-14 22:15
After going to http://share-links.biz/_11q2cmnghea23 and pressing the `ClickNLoad` button I get this:
```
14.03.2016 22:55:46 INFO      ADDON UpdateManager: All plugins are up to date!
14.03.2016 22:55:51 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
14.03.2016 22:56:13 DEBUG     ADDON ClickNLoad: Connection from 192.168.1.1:32175
14.03.2016 22:56:13 INFO      Added package ul.to containing 32 links
14.03.2016 22:56:13 INFO      Added package share-online.biz containing 32 links
```

**Comment by gr0ebi** [comment] 2016-03-16 22:31
I realy dont get it, I can't even select the button -> "Please start jdownloader"
Do you think it could be a MTU or fragmentation problem? Since it looks like its only my system/LAN that got this problem

**Comment by GammaC0de** [comment] 2016-03-16 22:49
If you see "Please start jdownloader" this means that the site could not detect pyload on 127.0.0.1 9666.
* Try to `telnet 127.0.0.1 9666` and see if you get `ADDON ClickNLoad: Connection from 127.0.0.1:` in the log
* Try disabling the firewall on your computer

**Comment by gr0ebi** [comment] 2016-03-16 22:53
@GammaC0de I just tried with PuTTY and get: "Network error:Software caused connection abort"
I have no firewall, either on win7 nor on my debian server

**Comment by GammaC0de** [comment] 2016-03-16 23:09
Try telneting directly to your debian box on port 9666

**Comment by gr0ebi** [comment] 2016-03-16 23:18
PuTTY opens with black screen, i get ```17.03.2016 00:16:21 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:50962``` in debug, but the window closes immediately

**Comment by GammaC0de** [comment] 2016-03-16 23:25
and `telnet 127.0.0.1 9666` now?

**Comment by gr0ebi** [comment] 2016-03-16 23:28
My comment I edited above is still running.
It shows this atm:
```
HTTP/1.1 408 Request Timeout
Cont
```
I'm waiting till it hopefully finishes...

**Comment by GammaC0de** [comment] 2016-03-16 23:34
Looks like some kind of a firewall on your windows computer
Maybe temporary turn off antivirus?
http://windows.microsoft.com/en-us/windows/turn-windows-firewall-on-off

**Comment by gr0ebi** [comment] 2016-03-16 23:46
Windows Firewall is disabled (service). I don't run a antivirus on my win7. Do you have IPv6 enabled on your test system?

**Comment by GammaC0de** [comment] 2016-03-16 23:48
try enabling the service, it may be responsible for portproxy also

**Comment by gr0ebi** [comment] 2016-03-16 23:56
> try enabling the service, it may be responsible for portproxy also

Did start windows firewall and activated IPv6 on win7 LAN port
If I telnet 127.0.0.1 I get "Network error: Connection timed out" 
telnet directly on debian didnt change anything

**Comment by GammaC0de** [comment] 2016-03-17 00:00
Make sure firewall is disabled (not the service)

**Comment by gr0ebi** [comment] 2016-03-17 00:03
No change :-/
But why do u think it's a firewall issue, since the connection is incomming on pyload?

**Comment by GammaC0de** [comment] 2016-03-17 00:05
if you telnet to your debian it works, correct?
if  you telnet to your windows it does not work, right?

**Comment by gr0ebi** [comment] 2016-03-17 00:13
> if you telnet to your debian it works, correct?

yes

> if you telnet to your windows it does not work, right?

I rebooted - since its windows - with firewall service disabled and getting `HTTP/1.1 408 Request Timeout` again

**Comment by GammaC0de** [comment] 2016-03-17 12:49
Both `telnet 127.0.0.1 9666` and `telnet ip.of.pyload 9666` works and I get `ADDON ClickNLoad: Connection from ` log

**Comment by gr0ebi** [comment] 2016-03-17 13:36
do u got ipv6 activated?

**Comment by gr0ebi** [comment] 2016-03-17 14:01
I resetted my TCP/IP and my Winsock on my Win7. If I open telnet now on either adrress, I get `ADDON ClickNLoad: Connection from 10.0.0.107:49264`. But the window stays black, and closes after about 15sec. Also getting this from time to time:
```
Exception in thread Thread-53:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 81, in forward
    forward(source, destination)
  File "/opt/pyload/module/plugins/internal/misc.py", line 817, in forward
    destination.shutdown(socket.SHUT_WR)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
```

**Comment by Velociraptor85** [comment] 2016-03-17 15:28
* Do you have some hardware switch between PC and Server?
* Do you use some kind of QoS on the Server?
* did you check if your Win PC has the correct Port forwarde rule? `netsh interface portproxy show all`
* why do you need ipv6 on your homeLAN?

The only thinks needed for this to work are the open port on the server and the portforward from your local IP to the Server IP `127.0.0.1:9666` to `server:9666`
So If the Port on the server is opend, maybe check via `netstat -tupln | grep 9666` 
And you telnet on your PC to `127.0.0.1:9666` this should work.
If that does not there must be
**A** and Firewall or some kind of Software preventing the Traffic
or 
**B** a miss configured PyLoad -> did you try a new Setup?

Hope you can figure it out and put the Solution somewhere =)

**Comment by gr0ebi** [comment] 2016-03-17 15:37
> Do you have some hardware switch between PC and Server?

Yes, Netgear GS108E

> Do you use some kind of QoS on the Server?

No

> did you check if your Win PC has the correct Port forwarde rule?

Yes, 127.0.0.1       9666        10.0.0.252      9666

> why do you need ipv6 on your homeLAN?

I dont need it, and I dont have it activated. I just read that portproxy needs IPv6 even its v4tov4

> netstat -tupln | grep 9666

root@server:~# netstat -tupln | grep 9666
tcp        0      0 0.0.0.0:9666            0.0.0.0:*               LISTEN      18781/python

> A and Firewall or some kind of Software preventing the Traffic

Still no Firewall (other portproxy to same IP is working)

> B a miss configured PyLoad -> did you try a new Setup?

I nearly git clone every week and resetting pyload config folder - i've got this problem since 2015

**Comment by Velociraptor85** [comment] 2016-03-17 17:04
What do you mean by other portproxy to same IP is working?

**Comment by GammaC0de** [comment] 2016-03-17 18:07
> I resetted my TCP/IP and my Winsock on my Win7. If I open telnet now on either adrress, I get ADDON ClickNLoad: Connection from 10.0.0.107:49264. But the window stays black, and closes after about 15sec.
This is the normal behavior, please try now  with http://share-links.biz/_11q2cmnghea23

**Comment by gr0ebi** [comment] 2016-03-17 21:58
> What do you mean by other portproxy to same IP is working?

I created a 2nd portproxy to the same server with an other port to apache. this portproxy is working.
So I dont think its a network nor a windows problem?!



> This is the normal behavior, please try now with http://share-links.biz/_11q2cmnghea23

I do get this every time:
```
17.03.2016 22:54:25 DEBUG     ADDON ClickNLoad: Connection from 10.0.0.107:54595
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 81, in forward
    forward(source, destination)
  File "/opt/pyload/module/plugins/internal/misc.py", line 817, in forward
    destination.shutdown(socket.SHUT_WR)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 107] Transport endpoint is not connected
```
The C'n'L button is still not clickable -> "Please start JDownloader"

**Comment by GammaC0de** [comment] 2016-03-17 22:42
check if you can browse to http://127.0.0.1:9666/flash/ ?

**Comment by gr0ebi** [comment] 2016-03-18 00:03
> check if you can browse to http://127.0.0.1:9666/flash/ ?

Output:
JDownloader

**Comment by GammaC0de** [comment] 2016-03-18 00:06
Try the tests in http://jdownloader.org/knowledge/wiki/glossary/cnl2

**Comment by gr0ebi** [comment] 2016-03-18 00:15
`http://127.0.0.1:9666/flash/addcrypted2` did work
`Plain CNL2` throw this error in the browser:
```
An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/opt/pyload/module/web/cnl_app.py", line 22, in _view
return function(*args, **kwargs)
TypeError: add() takes exactly 1 argument (0 given)
```

**Comment by GammaC0de** [comment] 2016-03-18 00:48
On `Plain CNL2` I have the same issue 
Please retry http://share-links.biz/_11q2cmnghea23
If that does not help, try deleting the two line in [misc.py#L816](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/misc.py#L816 ) and see what happens

**Comment by gr0ebi** [comment] 2016-03-18 01:10
> If that does not help, try deleting the two line in misc.py#L816 and see what happens

Bunch of errors:
```
18.03.2016 02:06:48 ERROR     Error importing UploadedTo: unexpected unindent (misc.py, line 818)
Traceback (most recent call last):
  File "/opt/pyload/module/plugins/PluginManager.py", line 268, in loadModule
    plugins[name]["name"])
  File "/opt/pyload/module/plugins/accounts/UploadedTo.py", line 6, in <module>
    from module.plugins.internal.Account import Account
  File "/opt/pyload/module/plugins/internal/Account.py", line 8, in <module>
    from module.plugins.internal.Plugin import Plugin, Skip
  File "/opt/pyload/module/plugins/internal/Plugin.py", line 17, in <module>
    from module.plugins.internal.misc import (Config, DB, decode, encode, exists, fixurl, fsjoin,
  File "/opt/pyload/module/plugins/internal/misc.py", line 818
    def compute_checksum(filename, hashtype):
                                            ^
IndentationError: unexpected unindent
Traceback (most recent call last):
  File "pyLoadCore.py", line 667, in <module>
    main()
  File "pyLoadCore.py", line 658, in main
    pyload_core.start()
  File "pyLoadCore.py", line 433, in start
    self.accountManager.getAccountInfos()
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/plugins/AccountManager.py", line 175, in getAccountInfos
    p = self.getAccountPlugin(p)
  File "/opt/pyload/module/plugins/AccountManager.py", line 55, in getAccountPlugin
    self.plugins[plugin] = self.core.pluginManager.loadClass("accounts", plugin)(self, self.accounts[plugin])
TypeError: 'NoneType' object is not callable

```

**Comment by GammaC0de** [comment] 2016-03-18 01:17
Revert back `misc.py` then change [misc.py#L817](https://github.com/pyload/pyload/blob/stable/module/plugins/internal/misc.py#L817) to
```
        pass
```

**Comment by gr0ebi** [comment] 2016-03-18 01:23
Errors are gone, but button still not clickable

**Comment by GammaC0de** [comment] 2016-03-18 01:29
‫Have you modified your hosts file?
Can you ping 'localhost'?
Surf to http://localhost:9666/flash ?

**Comment by gr0ebi** [comment] 2016-03-18 01:51
/etc/hosts on debian have minor name changes for 127.0.0.1 for bind9
ping to localhost sends me to 127.0.0.1 and is working

C:\Windows\System32\drivers\etc\hosts hasn't any changes
ping to localhost sends me to 127.0.0.1 and is working

> Surf to http://localhost:9666/flash ?

On Win7:
```
Error 403: Forbidden

Sorry, the requested URL 'http://localhost:9666/flash' caused an error:

Forbidden
```
It shows the pyload favicon, so I looks reachable

On debian with curl:
```
curl http://localhost:9666/flash

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error 403: Forbidden</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error 403: Forbidden</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:9666/flash&#039;</tt>
               caused an error:</p>
            <pre>Forbidden</pre>
        </body>
    </html>
```

**Comment by Velociraptor85** [comment] 2016-03-18 10:02
I cant shake the feeling that there must be some software on the server preventing the traffic or maybe on a router in between.
Did you check the file permissions?

Because it sure looks like the traffic is going to the server

**Comment by gr0ebi** [comment] 2016-03-18 14:33
> Did you check the file permissions?

I'm starting pyload as root atm, so what can I check here?
I can post my `ps aux` if you want

**Comment by GammaC0de** [comment] 2016-03-18 14:59
@gr0ebi `/etc/hosts` should have this line in it:
```
127.0.0.1       localhost
```

**Comment by gr0ebi** [comment] 2016-03-18 16:31
@GammaC0de it got this line in it:
`127.0.0.1     localhost     hostname     FQDN`

**Comment by gr0ebi** [comment] 2016-03-18 16:52
Is there any chance to debug the pyload webserver? Are there any log-files? So we can check if the pyload webserver itself forbid the connection?

**Comment by GammaC0de** [comment] 2016-03-18 16:58
Try changing [cnl_app.py#L21](https://github.com/pyload/pyload/blob/stable/module/web/cnl_app.py#L21)
from ` or request.environ.get('HTTP_HOST','0') == '127.0.0.1:9666':` to ` or request.environ.get('HTTP_HOST','0') in ('127.0.0.1', 'localhost'):` and see if it makes change

**Comment by gr0ebi** [comment] 2016-03-18 17:23
@GammaC0de 
```
18.03.2016 18:22:16 ERROR     ADDON ClickNLoad: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/pyload/module/PluginThread.py", line 466, in run
    self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/plugins/hooks/ClickNLoad.py", line 128, in _server
    server_socket.connect((self.web_ip, self.web_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```
Button still not clickable

**Comment by gr0ebi** [comment] 2016-03-24 15:53
> Is there any chance to debug the pyload webserver? Are there any log-files? So we can check if the pyload webserver itself forbid the connection?

Didn't get a answer, is there any log?

**Comment by vuolter** [comment] 2016-03-24 16:03
@gr0ebi Not in 0.4.9. Webui logging was introduced in 0.4.10 .

**Comment by Velociraptor85** [comment] 2016-03-24 21:43
@gr0ebi maybe you could check with some linuxtools like iftop or similar ?

**Comment by gr0ebi** [comment] 2016-03-25 17:12
> @gr0ebi maybe you could check with some linuxtools like iftop or similar ?

Never used that tool before, I gonna give it a try. Thanks!

**Comment by lukastribus** [comment] 2017-11-06 20:32
It doesn't affect share-links.biz anymore, because they upgraded from CNLv2 plain (/flash/add) to full encrypted CNLv2, however CNLv2 plain still does not work.

How to reproduce:
- go to http://jdownloader.org/knowledge/wiki/glossary/cnl2
- go to the bottom of the site, in the "Plain CNL2" section
- click on "Add Link to JDownloader"
- plain links are posted to "http://127.0.0.1:9666/flash/add"
- pyload crashes with:

```
An Error occured, please enable debug mode to get more details.
HTTP Response 500
Traceback (most recent call last):
  File "/media/pyload-stable/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/media/pyload-stable/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/media/pyload-stable/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
TypeError: add() takes exactly 1 argument (0 given)

```


The following diff fixes the issue for me:
```
--- module/web/cnl_app.py.org   2017-11-06 21:29:50.924221900 +0100
+++ module/web/cnl_app.py       2017-11-06 21:25:55.178125100 +0100
@@ -35,7 +35,7 @@

 @route("/flash/add", method="POST")
 @local_check
-def add(request):
+def add():
     package = request.POST.get('referer', None)
     urls = filter(lambda x: x != "", request.POST['urls'].split("\n"))


```


@GammaC0de can you commit this fix please?

**Comment by GammaC0de** [comment] 2017-11-06 23:51
Merged 👍

**Closed by GammaC0de** 2017-11-06 23:51 UTC
Labels: plugin issue

**Comment by lukastribus** [comment] 2017-11-06 23:59
Thank you!
