### ISSUE TITLE
Error executing periodical task: 'unicode' object has no attribute 'getText'

### ISSUE THREAD

**Issue by Gutz-Pilz** [pyload/pyload#2133] opened 2015-10-29 10:01 UTC
Hi There,
https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/TraktFetcher.py
my new Plugin doesnt work when i use pyload internal getUrl
thist title makes problem "Hitman Agent 47" and causes this error
```Error executing periodical task: 'unicode' object has no attribute 'getText'```

any idea how to prevent this ?

**Comment by GammaC0de** [comment] 2015-10-29 14:53
@Gutz-Pilz Obviously the problem is that you are calling `getText()`.
what does it supposed to do exactly?

**Comment by Gutz-Pilz** [comment] 2015-10-29 16:23
it works on title without numbers.
some people havent the python requests library 
https://github.com/Gutz-Pilz/pyLoad-stuff/commit/fe88b91088b2a857d598d1202a53025b49001f13#diff-3e740fc1f37a99fcd2c2ad6449af168f

^^so i changed to that.

**Comment by joberreiter** [comment] 2015-10-30 14:37
@Gutz-Pilz
Once more: Just google what `gettext()` is supposed to do ... (hint: i18n).

What do you expect when you write
```
releaseName = link.getText()
```
?

**Comment by Velociraptor85** [comment] 2016-05-27 13:59
@Gutz-Pilz @vuolter @GammaC0de 
since the main issue is linked here please close the issue

**Comment by GammaC0de** [comment] 2016-05-28 11:56
Closing, this issue is not from pyload

**Closed by GammaC0de** 2016-05-28 11:56 UTC
Labels: plugin issue
