### ISSUE TITLE
Click n Load doesn't work anymore

### ISSUE THREAD

**Issue by Hugur88** [pyload/pyload#2709] opened 2017-01-31 14:46 UTC
First at all i will say sorry for my bad english skills.

I have NSA325 with pyload.
And all worked for long time.
But 2 weeks ago, click n load doesn't work anymore.
When i click click n load buttons, no error appears but the collector is still empty

Port listening and forwarding is activated.
Hope someone can help

Thx

**Comment by GammaC0de** [comment] 2017-01-31 14:55
Stop pyLoad.
Start pyload debug mode from the console: `python pyLoadCore.py -d`.
Click the click n load button.
See if there is somthing useful in the console.

**Comment by Velociraptor85** [comment] 2017-02-05 21:22
https://github.com/pyload/pyload/pull/2717 does this solve the issue?

**Comment by Lalarian** [comment] 2017-03-08 21:03
ClicknLoad hasn't been working for me since a while, too.
If I try opening http://127.0.0.1/flashgot all I get is:
`An Error occured, please enable debug mode to get more details.

HTTP Response 500

Traceback (most recent call last):
File "/opt/share/pyload/module/lib/bottle.py", line 733, in _handle
return route.call(**args)
File "/opt/share/pyload/module/lib/bottle.py", line 1448, in wrapper
rv = callback(*a, **ka)
File "/opt/share/pyload/module/web/cnl_app.py", line 22, in _view
return function(*args, **kwargs)
File "/opt/share/pyload/module/web/cnl_app.py", line 123, in flashgot
if request.environ['HTTP_REFERER'] != "http://localhost:9666/flashgot" and request.environ['HTTP_REFERER'] != "http://127.0.0.1:9666/flashgot":
KeyError: 'HTTP_REFERER'`

I have debug enabled, but in Log it only says:
ADDON ClickNLoad: Connection from 192.168.1.2:37620

I have applied both patches (2717 and 1784).

**Comment by GammaC0de** [comment] 2017-03-08 21:07
Referrer should be either `http://localhost:9666/flashgot` or `http://127.0.0.1:9666/flashgot`

**Comment by Velociraptor85** [comment] 2017-03-09 08:19
Maybe you forgot to portforward? 
Linux https://superuser.com/questions/567715/port-forwarding-for-clicknload-remote-usage
Windows https://stackoverflow.com/a/11535395

**Comment by Lalarian** [comment] 2017-03-10 16:27
Ok, the problem is that only the flashgot site doesn't work when opened directly from web browser. Click n Load itself is working.

**Comment by Velociraptor85** [comment] 2017-03-13 14:26
so close ? or rename ?

**Comment by Hugur88** [comment] 2017-03-13 19:25
Don’t understand what you want…

 

Von: Velociraptor85 [mailto:notifications@github.com] 
Gesendet: Montag, 13. März 2017 15:27
An: pyload/pyload
Cc: Hugur88; Mention
Betreff: Re: [pyload/pyload] Click n Load doesn't work anymore (#2709)

 

so close ? or rename ?

**Comment by Lalarian** [comment] 2017-03-13 20:02
You still need to post your pyload debug log with debug enabled. Look at  GammaC0de's first post.

**Comment by JustinS-B** [comment] 2017-03-16 21:57
Hi, I get a Click n Load problem with some links. There is a special kind of hyphen which just causes it to blow chunks if the file name includes it. I think that it is the one the Microsoft word auto-replaces a "normal" minus sign with when two words are hyphenated. This is it: "–" (I hope that it can paste OK). I use Click n Load daily, & have done for several years. It is currently working, with the latest updates - except, of course, if it has a malignant hyphen in the page name/link. I'm sorry to say that this bug has existed for some years, it has just taken me a while to finally track it down to a unicode hyphen, as I didn't want to report a sporadic bug with an unknown cause that I couldn't reliably replicate. However, now that I can replicate this 100%, if you need a working example, pm me and I can provide a username, password, & link that you can test.

Here is the debug log of what happens. Note the file name in the logs "**Package \xe2\x80\x93 April 2017**" which originally was "**Package – April 2017**" on the link.

`16.03.2017 21:28:17 INFO      pyLoad is up and running
16.03.2017 21:28:17 INFO      ADDON UpdateManager: All plugins are up to date!
16.03.2017 21:28:23 INFO      ADDON ClickNLoad: Proxy listening on 0.0.0.0:9666
16.03.2017 21:28:52 DEBUG     ADDON ClickNLoad: Connection from 192.168.1.2:54916
Traceback (most recent call last):
  File "/opt/pyload/module/database/DatabaseBackend.py", line 96, in processJob
    self.result = self.f(*self.args, **self.kwargs)
  File "/opt/pyload/module/database/FileDatabase.py", line 630, in addPackage
    self.c.execute('INSERT INTO packages(name, folder, queue, packageorder) VALUES(?,?,?,?)', (name, folder, queue, order))
ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
Database Error @ addPackage ('Package \xe2\x80\x93 April 2017', 'Package \xe2\x80\x93 April 2017', 1) {} You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
  File "/opt/pyload/module/web/cnl_app.py", line 132, in flashgot
    PYLOAD.addPackage(package, urls, autostart)
  File "/opt/pyload/module/Api.py", line 326, in addPackage
    pid = self.core.files.addPackage(name, folder, dest)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 141, in addPackage
    e = InsertEvent("pack", lastID, p.order, "collector" if not queue else "queue")
AttributeError: 'NoneType' object has no attribute 'order'
An error occured while processing the request.
Traceback (most recent call last):
  File "/opt/pyload/module/lib/bottle.py", line 733, in _handle
    return route.call(**args)
  File "/opt/pyload/module/lib/bottle.py", line 1448, in wrapper
    rv = callback(*a, **ka)
  File "/opt/pyload/module/web/cnl_app.py", line 22, in _view
    return function(*args, **kwargs)
  File "/opt/pyload/module/web/cnl_app.py", line 132, in flashgot
    PYLOAD.addPackage(package, urls, autostart)
  File "/opt/pyload/module/Api.py", line 326, in addPackage
    pid = self.core.files.addPackage(name, folder, dest)
  File "/opt/pyload/module/utils.py", line 165, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 68, in new
    return func(*args)
  File "/opt/pyload/module/database/FileDatabase.py", line 141, in addPackage
    e = InsertEvent("pack", lastID, p.order, "collector" if not queue else "queue")
AttributeError: 'NoneType' object has no attribute 'order'`

**Comment by JustinS-B** [comment] 2017-03-16 22:07
Oh yes, I forgot something important. If you use the "add" button on the webinterface & manually paste in the link/s along with manually pasting in the name with the offending hyphen, it works normally, & doesn't complain at all. It only errors when you load it through Click n Load. 

`16.03.2017 22:03:47 INFO      Added package Package – April 2017 containing 1 links`

**Comment by Velociraptor85** [comment] 2017-11-17 23:57
@Hugur88 is this Problem still valid?

**Comment by Hugur88** [comment] 2017-11-18 14:01
Yeah unfortunally the problem is still valid


Am 18. November 2017 00:57:40 schrieb Velociraptor85 
<notifications@github.com>:

**Comment by Velociraptor85** [comment] 2017-11-18 15:53
did you already update to the new update server ? like described in https://github.com/pyload/pyload/issues/2994 @Hugur88 ?

**Comment by Hugur88** [comment] 2017-11-27 13:45
The Problem is, my english is very bad and i have a zyxel NAS, pyload is running

 

Von: Velociraptor85 [mailto:notifications@github.com] 
Gesendet: Freitag, 24. November 2017 14:14
An: pyload/pyload
Cc: Hugur88; Assign
Betreff: Re: [pyload/pyload] Click n Load doesn't work anymore (#2709)

 

Assigned #2709 <https://github.com/pyload/pyload/issues/2709>  to @Hugur88 <https://github.com/hugur88> .

**Comment by d30r** [comment] 2018-01-03 09:49
[pyload click n load.zip](https://github.com/pyload/pyload/files/1599962/pyload.click.n.load.zip)
Hi,
had the same problem long ago. The fix was in an Click'n Load.py-File. I attached a working one plus the new UpdateManager.
Just Stop the pyload Service in the NSA-32. Extract and copy the files into the pyload-installation-folder 
(mine is in: /i-data/9771ee4c/***/zy-pkgs/pyLoad/etc/pyload/userplugins/hooks)
and restart the Pyload-service, after that click'nload should work as expected.

Hi, ich denke, dass ich dir mit deutsch weiterhelfen kann.
Ich hatte dasselbe Problem, Lösen konnte ich das mit einer angepassten Click'nLoad.py-Datei. Ich habe eine funktionierende angehängt, außerdem habe ich die Datei für den neuen updatemanager angehängt.
Stoppe einfach den Pyload-Service in der Oberfläche des NSA-325 und entpacke und kopiere angehängte Dateien in in das Pyload-Pluginverzeichnis:
(meins liegt in "/i-data/9771ee4c/***/zy-pkgs/pyLoad/etc/pyload/userplugins/hooks" )
danach startest du den Pyload wieder und Click n load sollte wieder wie gewohnt laufen.

**Comment by GammaC0de** [comment] 2018-01-03 10:07
@d30r 
Two points:
1. ClickNLoad.py that you have attached is exactly the same as the one on the repo so I don't know how can it help solving the issue above.
2. UpdateManager.py that you have attached is out of date, this is the current one https://github.com/pyload/pyload/raw/353c6692afdec4b6108555725cb5db46d02ed816/module/plugins/hooks/UpdateManager.py and you should replace it to receive plugin updates.

**Comment by Velociraptor85** [comment] 2018-08-20 07:38
@Hugur88 can we close this ? did you update the current UpdateManager.py

**Comment by Hugur88** [comment] 2018-08-20 07:40
My skills are to low to Do this.
You can close

Am 20. August 2018 09:38:51 schrieb Velociraptor85 <notifications@github.com>:

**Closed** 2018-08-20 07:41 UTC
Labels: log wanted, question
